In [1]:
# Environment check: record the versions in your README.
import sys
import importlib.metadata as metadata
print('Python:', sys.version.split()[0])
for package in ['pandas', 'numpy', 'pyspark', 'pyarrow', 'sqlalchemy', 'psycopg', 'boto3']:
    try:
        print(f'{package}: {metadata.version(package)}')
    except metadata.PackageNotFoundError:
        print(f'{package}: NOT INSTALLED (install before its assessed section)')

Python: 3.12.10
pandas: 3.0.6
numpy: 2.5.4
pyspark: 4.2.0
pyarrow: 26.0.0
sqlalchemy: 2.1.4
psycopg: 3.3.6
boto3: 1.43.112

In [2]:
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import pandas as pd

In [3]:
EXPECTED_COLUMNS = {
    "properties.csv": {
        "property_id",
        "property_name",
        "city"
    },

    "units.csv": {
        "unit_id",
        "property_id",
        "floor_area_sqm",
        "active"
    },

    "leases.csv": {
        "lease_id",
        "unit_id",
        "start_date",
        "end_date",
        "monthly_rent_usd"
    },

    "work_orders.csv": {
        "work_order_id",
        "unit_id",
        "opened_date",
        "closed_date",
        "priority",
        "response_hours",
        "cost_usd",
        "status"
    },

    "meter_readings.csv": {
        "reading_id",
        "unit_id",
        "reading_month",
        "energy_kwh"
    }
}

#### Verify the actual column names because your file may use name rather than proprty_name

In [4]:
def ingest_source(path, expected_columns):
    if not path.exists():
        raise FileNotFoundError(...)

    df = pd.read_csv(path)

    if df.empty:
        raise ValueError(...)

    missing_columns = expected_columns - set(df.columns)

    if missing_columns:
        raise ValueError(...)

    # hash file
    # create timestamp
    # return dataframe + manifest information

In [5]:
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import pandas as pd


def ingest_source(path: Path, expected_columns: set):
    """
    Validate a CSV source file, load it with stable string dtypes,
    and return both the DataFrame and ingestion metadata.
    """

    # 1. Validate that the file exists
    if not path.exists():
        raise FileNotFoundError(
            f"Source file does not exist: {path}"
        )

    # 2. Validate that the path is actually a file
    if not path.is_file():
        raise ValueError(
            f"Expected a file but received: {path}"
        )

    # 3. Validate that the file is not empty
    if path.stat().st_size == 0:
        raise ValueError(
            f"Source file is empty: {path}"
        )

    # 4. Load using stable dtypes
    # Keep source values as strings during ingestion.
    # Numeric/date conversion should happen later during validation/cleaning.
    try:
        df = pd.read_csv(
            path,
            dtype="string",
            keep_default_na=True
        )
    except Exception as exc:
        raise ValueError(
            f"Could not read CSV file {path.name}: {exc}"
        ) from exc

    # 5. Validate that records exist
    if df.empty:
        raise ValueError(
            f"Source file contains no data rows: {path}"
        )

    # 6. Validate required columns
    actual_columns = set(df.columns)

    missing_columns = expected_columns - actual_columns

    if missing_columns:
        raise ValueError(
            f"{path.name} is missing required columns: "
            f"{sorted(missing_columns)}"
        )

    # 7. Compute SHA-256 hash of the original file
    sha256 = hashlib.sha256()

    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(8192), b""):
            sha256.update(chunk)

    file_hash = sha256.hexdigest()

    # 8. Create UTC ingestion timestamp
    ingest_timestamp = datetime.now(timezone.utc).isoformat()

    # 9. Create manifest record
    manifest_entry = {
        "filename": path.name,
        "file_path": str(path),
        "row_count": len(df),
        "column_count": len(df.columns),
        "ingest_timestamp_utc": ingest_timestamp,
        "sha256": file_hash
    }

    return df, manifest_entry

In [6]:
datasets = {}
ingestion_manifest = []

In [7]:
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import pandas as pd


def ingest_source(path, expected_columns):
    """
    Load a CSV source file, validate required columns,
    and create ingestion metadata.
    """

    path = Path(path)

    # 1. Check file exists
    if not path.exists():
        raise FileNotFoundError(
            f"Source file does not exist: {path.resolve()}"
        )

    # 2. Read CSV
    df = pd.read_csv(path)

    # 3. Validate expected columns
    missing_columns = set(expected_columns) - set(df.columns)

    if missing_columns:
        raise ValueError(
            f"{path.name} is missing required columns: "
            f"{sorted(missing_columns)}"
        )

    # 4. Calculate SHA-256 hash
    sha256 = hashlib.sha256(path.read_bytes()).hexdigest()

    # 5. Create ingestion manifest
    manifest = {
        "file_name": path.name,
        "file_path": str(path.resolve()),
        "row_count": len(df),
        "column_count": len(df.columns),
        "sha256": sha256,
        "ingested_at_utc": datetime.now(timezone.utc).isoformat()
    }

    return df, manifest

#### Test one of the actual file

In [8]:
RAW_DIR = Path(r"..data\raw\properties.csv")

In [9]:
RAW_DIR = Path("..") / "data" / "raw"

In [10]:
df, manifest = ingest_source(
    RAW_DIR / "properties.csv",
    {"property_id", "property_name", "city"}
)

In [11]:
print(df.head())

  property_id        property_name           city
0        P001  MetroSpace Tower 01          Lagos
1        P002  MetroSpace Tower 02          Abuja
2        P003  MetroSpace Tower 03         Ibadan
3        P004  MetroSpace Tower 04  Port Harcourt
4        P005  MetroSpace Tower 05          Lagos

In [12]:
print(manifest)

{'file_name': 'properties.csv', 'file_path': 'C:\\Documents\\Desktop\\PropTech360_Capstone_data_pipeline\\data\\raw\\properties.csv', 'row_count': 12, 'column_count': 3, 'sha256': 'c9865bcf2b142026c5dd05547f9c14d3e11f5a27a3e22bca52f5efe0c795ef19', 'ingested_at_utc': '2026-10-20T17:16:01.136303+00:00'}

In [13]:
from pathlib import Path

for file in Path(".").rglob("properties.csv"):
    print(file.resolve())

C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\staging\properties.csv

In [14]:
RAW_DIR = Path("data/raw")

In [15]:
{
    "filename": "properties.csv",
    "file_path": "data/raw/properties.csv",
    "row_count": 12,
    "column_count": 3,
    "ingest_timestamp_utc": "2026-10-03T...",
    "sha256": "..."
}

{'filename': 'properties.csv',
 'file_path': 'data/raw/properties.csv',
 'row_count': 12,
 'column_count': 3,
 'ingest_timestamp_utc': '2026-10-03T...',
 'sha256': '...'}

In [16]:
from pathlib import Path

RAW_DIR = Path("..") / "data" / "raw"

In [17]:
datasets = {}
ingestion_manifest = []

for filename, expected_columns in EXPECTED_COLUMNS.items():

    file_path = RAW_DIR / filename

    df, manifest_entry = ingest_source(
        file_path,
        expected_columns
    )

    datasets[filename] = df
    ingestion_manifest.append(manifest_entry)

In [18]:
print("Current working directory:")
print(Path.cwd())

print("\nRaw directory:")
print(RAW_DIR.resolve())

print("\nProperties path:")
print((RAW_DIR / "properties.csv").resolve())

print("\nDoes it exist?")
print((RAW_DIR / "properties.csv").exists())

Current working directory:
c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook

Raw directory:
C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\raw

Properties path:
C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\raw\properties.csv

Does it exist?
True

In [19]:
for filename, df in datasets.items():
    print(filename, df.shape)

properties.csv (12, 3)
units.csv (241, 4)
leases.csv (198, 5)
work_orders.csv (1501, 8)
meter_readings.csv (1440, 4)

In [20]:
import pandas as pd

test_df = pd.read_csv(RAW_DIR / "properties.csv")
print(test_df.columns.tolist())

['property_id', 'property_name', 'city']

In [21]:
ingestion_manifest

[{'file_name': 'properties.csv',
  'file_path': 'C:\\Documents\\Desktop\\PropTech360_Capstone_data_pipeline\\data\\raw\\properties.csv',
  'row_count': 12,
  'column_count': 3,
  'sha256': 'c9865bcf2b142026c5dd05547f9c14d3e11f5a27a3e22bca52f5efe0c795ef19',
  'ingested_at_utc': '2026-10-20T17:16:01.359910+00:00'},
 {'file_name': 'units.csv',
  'file_path': 'C:\\Documents\\Desktop\\PropTech360_Capstone_data_pipeline\\data\\raw\\units.csv',
  'row_count': 241,
  'column_count': 4,
  'sha256': 'f9bcef3d08d4662c270bfff385299306995ed6ba3f0c54e6b3754274a53c2748',
  'ingested_at_utc': '2026-10-20T17:16:01.375911+00:00'},
 {'file_name': 'leases.csv',
  'file_path': 'C:\\Documents\\Desktop\\PropTech360_Capstone_data_pipeline\\data\\raw\\leases.csv',
  'row_count': 198,
  'column_count': 5,
  'sha256': 'b6a8e10a11dfbca4358d5a9d60ad4709bc6511417137aeb58e389b21e31ebe0a',
  'ingested_at_utc': '2026-10-20T17:16:01.391494+00:00'},
 {'file_name': 'work_orders.csv',
  'file_path': 'C:\\Documents\\Desktop\\PropTech360_Capstone_data_pipeline\\data\\raw\\work_orders.csv',
  'row_count': 1501,
  'column_count': 8,
  'sha256': '835c05c0410f7a481d71f4efa8213520d012688ebb8b757d2784e889de750fe4',
  'ingested_at_utc': '2026-10-20T17:16:01.413972+00:00'},
 {'file_name': 'meter_readings.csv',
  'file_path': 'C:\\Documents\\Desktop\\PropTech360_Capstone_data_pipeline\\data\\raw\\meter_readings.csv',
  'row_count': 1440,
  'column_count': 4,
  'sha256': '93684a8ed99f3e4f368646d2f766a41805d54e7db5ef43b0e602cec1a6772346',
  'ingested_at_utc': '2026-10-20T17:16:01.429481+00:00'}]

#### Save the Manifest

In [22]:
import json
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
CURATED_DIR = PROJECT_ROOT / "data" / "curated"

CURATED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

manifest_path = CURATED_DIR / "ingestion_manifest.json"

with manifest_path.open(
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        ingestion_manifest,
        file,
        indent=4,
        default=str
    )

print(f"Manifest saved to: {manifest_path.resolve()}")

Manifest saved to: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\curated\ingestion_manifest.json

In [23]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
CURATED_DIR = PROJECT_ROOT / "data" / "curated"

RAW_DIR.mkdir(parents=True, exist_ok=True)
CURATED_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw directory:", RAW_DIR)
print("Curated directory:", CURATED_DIR)

Project root: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline
Raw directory: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\raw
Curated directory: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\curated

In [24]:
datasets.keys()

dict_keys(['properties.csv', 'units.csv', 'leases.csv', 'work_orders.csv', 'meter_readings.csv'])

In [25]:
datasets = {
    "properties": datasets["properties.csv"],
    "units": datasets["units.csv"],
    "leases": datasets["leases.csv"],
    "work_orders": datasets["work_orders.csv"],
    "meter_readings": datasets["meter_readings.csv"]
}

In [26]:
from pathlib import Path
from datetime import datetime, timezone

import pandas as pd

In [27]:
for name, df in datasets.items():
    print(name, df.shape)

properties (12, 3)
units (241, 4)
leases (198, 5)
work_orders (1501, 8)
meter_readings (1440, 4)

#### Creating identifier

In [28]:
IDENTIFIERS = {
    "properties.csv": "property_id",
    "units.csv": "unit_id",
    "leases.csv": "lease_id",
    "work_orders.csv": "work_order_id",
    "meter_readings.csv": "meter_reading_id"
}

#### Profile_table function

In [29]:
import pandas as pd


def profile_table(df: pd.DataFrame, identifier: str) -> dict:
    """
    Generate basic quality statistics for a dataframe.

    Returns:
        - row count
        - column count
        - null values by column
        - duplicate identifier count
        - pandas data types
    """

    profile = {
        "row_count": len(df),

        "column_count": len(df.columns),

        "nulls_by_column": df.isna().sum().to_dict(),

        "duplicate_identifier_count": (
            df.duplicated(subset=[identifier]).sum()
            if identifier in df.columns
            else None
        ),

        "data_types": {
            column: str(dtype)
            for column, dtype in df.dtypes.items()
        }
    }

    return profile

#### Test profiling function

In [30]:
properties_profile = profile_table(
    datasets["properties"],
    "property_id"
)

In [31]:
properties_profile

{'row_count': 12,
 'column_count': 3,
 'nulls_by_column': {'property_id': 0, 'property_name': 0, 'city': 0},
 'duplicate_identifier_count': np.int64(0),
 'data_types': {'property_id': 'str', 'property_name': 'str', 'city': 'str'}}

#### Profile all the five datasets

In [32]:
identifier = "properties_id"

properties_profile = profile_table(
    datasets["properties"],
    identifier
)

In [33]:
identifier = "leases_id"

leases_profile = profile_table(
    datasets["leases"],
    identifier
)

In [34]:
identifier = "unit_id"

units_profile = profile_table(
    datasets["units"],
    identifier
)

In [35]:
identifier = "meter_reading_id"

meter_readings_profile = profile_table(
    datasets["meter_readings"],
    identifier
)

In [36]:
identifier = "work_order_id"

work_orders_profile = profile_table(
    datasets["work_orders"],
    identifier
)

In [37]:
properties_profile = profile_table(
    datasets["properties"],
    "property_id"
)

units_profile = profile_table(
    datasets["units"],
    "unit_id"
)

leases_profile = profile_table(
    datasets["leases"],
    "lease_id"
)

work_orders_profile = profile_table(
    datasets["work_orders"],
    "work_order_id"
)

meter_readings_profile = profile_table(
    datasets["meter_readings"],
    "reading_id"
)

In [38]:
IDENTIFIERS = {
    "properties": "property_id",
    "units": "unit_id",
    "leases": "lease_id",
    "work_orders": "work_order_id",
    "meter_readings": "reading_id",
}

quality_profiles = {}

for dataset_name, df in datasets.items():
    identifier = IDENTIFIERS[dataset_name]

    quality_profiles[dataset_name] = profile_table(
        df,
        identifier
    )

In [39]:
for filename, profile in quality_profiles.items():

    print("=" * 60)
    print("Leases")

    print("Rows:", profile["row_count"])
    print("Duplicate IDs:",
          profile["duplicate_identifier_count"])

    print("Nulls:")
    print(profile["nulls_by_column"])

============================================================
Leases
Rows: 12
Duplicate IDs: 0
Nulls:
{'property_id': 0, 'property_name': 0, 'city': 0}
============================================================
Leases
Rows: 241
Duplicate IDs: 1
Nulls:
{'unit_id': 0, 'property_id': 0, 'floor_area_sqm': 0, 'active': 0}
============================================================
Leases
Rows: 198
Duplicate IDs: 0
Nulls:
{'lease_id': 0, 'unit_id': 0, 'start_date': 0, 'end_date': 139, 'monthly_rent_usd': 0}
============================================================
Leases
Rows: 1501
Duplicate IDs: 1
Nulls:
{'work_order_id': 0, 'unit_id': 0, 'opened_date': 0, 'closed_date': 295, 'priority': 0, 'response_hours': 295, 'cost_usd': 0, 'status': 0}
============================================================
Leases
Rows: 1440
Duplicate IDs: 0
Nulls:
{'reading_id': 0, 'unit_id': 0, 'reading_month': 0, 'energy_kwh': 0}

In [40]:
for filename, profile in quality_profiles.items():

    print("=" * 60)
    print("meter_readings")

    print("Rows:", profile["row_count"])
    print("Duplicate IDs:",
          profile["duplicate_identifier_count"])

    print("Nulls:")
    print(profile["nulls_by_column"])

============================================================
meter_readings
Rows: 12
Duplicate IDs: 0
Nulls:
{'property_id': 0, 'property_name': 0, 'city': 0}
============================================================
meter_readings
Rows: 241
Duplicate IDs: 1
Nulls:
{'unit_id': 0, 'property_id': 0, 'floor_area_sqm': 0, 'active': 0}
============================================================
meter_readings
Rows: 198
Duplicate IDs: 0
Nulls:
{'lease_id': 0, 'unit_id': 0, 'start_date': 0, 'end_date': 139, 'monthly_rent_usd': 0}
============================================================
meter_readings
Rows: 1501
Duplicate IDs: 1
Nulls:
{'work_order_id': 0, 'unit_id': 0, 'opened_date': 0, 'closed_date': 295, 'priority': 0, 'response_hours': 295, 'cost_usd': 0, 'status': 0}
============================================================
meter_readings
Rows: 1440
Duplicate IDs: 0
Nulls:
{'reading_id': 0, 'unit_id': 0, 'reading_month': 0, 'energy_kwh': 0}

In [41]:
for filename, profile in quality_profiles.items():

    print("=" * 60)
    print("properties")

    print("Rows:", profile["row_count"])
    print("Duplicate IDs:",
          profile["duplicate_identifier_count"])

    print("Nulls:")
    print(profile["nulls_by_column"])

============================================================
properties
Rows: 12
Duplicate IDs: 0
Nulls:
{'property_id': 0, 'property_name': 0, 'city': 0}
============================================================
properties
Rows: 241
Duplicate IDs: 1
Nulls:
{'unit_id': 0, 'property_id': 0, 'floor_area_sqm': 0, 'active': 0}
============================================================
properties
Rows: 198
Duplicate IDs: 0
Nulls:
{'lease_id': 0, 'unit_id': 0, 'start_date': 0, 'end_date': 139, 'monthly_rent_usd': 0}
============================================================
properties
Rows: 1501
Duplicate IDs: 1
Nulls:
{'work_order_id': 0, 'unit_id': 0, 'opened_date': 0, 'closed_date': 295, 'priority': 0, 'response_hours': 295, 'cost_usd': 0, 'status': 0}
============================================================
properties
Rows: 1440
Duplicate IDs: 0
Nulls:
{'reading_id': 0, 'unit_id': 0, 'reading_month': 0, 'energy_kwh': 0}

In [42]:
for filename, profile in quality_profiles.items():

    print("=" * 60)
    print("units")

    print("Rows:", profile["row_count"])
    print("Duplicate IDs:",
          profile["duplicate_identifier_count"])

    print("Nulls:")
    print(profile["nulls_by_column"])

============================================================
units
Rows: 12
Duplicate IDs: 0
Nulls:
{'property_id': 0, 'property_name': 0, 'city': 0}
============================================================
units
Rows: 241
Duplicate IDs: 1
Nulls:
{'unit_id': 0, 'property_id': 0, 'floor_area_sqm': 0, 'active': 0}
============================================================
units
Rows: 198
Duplicate IDs: 0
Nulls:
{'lease_id': 0, 'unit_id': 0, 'start_date': 0, 'end_date': 139, 'monthly_rent_usd': 0}
============================================================
units
Rows: 1501
Duplicate IDs: 1
Nulls:
{'work_order_id': 0, 'unit_id': 0, 'opened_date': 0, 'closed_date': 295, 'priority': 0, 'response_hours': 295, 'cost_usd': 0, 'status': 0}
============================================================
units
Rows: 1440
Duplicate IDs: 0
Nulls:
{'reading_id': 0, 'unit_id': 0, 'reading_month': 0, 'energy_kwh': 0}

In [43]:
for filename, profile in quality_profiles.items():

    print("=" * 60)
    print("work_orders")

    print("Rows:", profile["row_count"])
    print("Duplicate IDs:",
          profile["duplicate_identifier_count"])

    print("Nulls:")
    print(profile["nulls_by_column"])

============================================================
work_orders
Rows: 12
Duplicate IDs: 0
Nulls:
{'property_id': 0, 'property_name': 0, 'city': 0}
============================================================
work_orders
Rows: 241
Duplicate IDs: 1
Nulls:
{'unit_id': 0, 'property_id': 0, 'floor_area_sqm': 0, 'active': 0}
============================================================
work_orders
Rows: 198
Duplicate IDs: 0
Nulls:
{'lease_id': 0, 'unit_id': 0, 'start_date': 0, 'end_date': 139, 'monthly_rent_usd': 0}
============================================================
work_orders
Rows: 1501
Duplicate IDs: 1
Nulls:
{'work_order_id': 0, 'unit_id': 0, 'opened_date': 0, 'closed_date': 295, 'priority': 0, 'response_hours': 295, 'cost_usd': 0, 'status': 0}
============================================================
work_orders
Rows: 1440
Duplicate IDs: 0
Nulls:
{'reading_id': 0, 'unit_id': 0, 'reading_month': 0, 'energy_kwh': 0}

#### Help for Quarantine reasons

In [44]:
def add_rejection_reason(
    df: pd.DataFrame,
    mask: pd.Series,
    reason: str
):
    """
    Add a rejection reason to rows matching mask.
    """

    df.loc[mask, "rejection_reason"] = (
        df.loc[mask, "rejection_reason"]
        .fillna("")
        .apply(
            lambda existing:
            f"{existing}; {reason}".strip("; ")
            if existing
            else reason
        )
    )

#### Validate and Quarantine

In [45]:
def validate_and_quarantine(
    datasets: dict,
    run_id: str
):

    clean_datasets = {}

    quarantine_datasets = {}

    quality_summary = {}

    return (
        clean_datasets,
        quarantine_datasets,
        quality_summary
    )

#### Validate properties data

In [46]:
properties = datasets["properties"].copy()

properties["rejection_reason"] = pd.NA

##### checking for duplicate (properties)

In [47]:
duplicate_property = properties.duplicated(
    subset=["property_id"],
    keep=False
)

add_rejection_reason(
    properties,
    duplicate_property,
    "duplicate_property_id"
)

#### checking for missing ID

In [48]:
missing_property_id = properties["property_id"].isna()

add_rejection_reason(
    properties,
    missing_property_id,
    "missing_property_id"
)

#### Validate units data

In [49]:
units = datasets["units"].copy()

units["rejection_reason"] = pd.NA

#### checking for duplicate (units)

In [50]:
duplicate_unit = units.duplicated(
    subset=["unit_id"],
    keep=False
)

add_rejection_reason(
    units,
    duplicate_unit,
    "duplicate_unit_id"
)

#### check unit (property foreign key)

In [51]:
valid_property_ids = set(
    properties.loc[
        properties["rejection_reason"].isna(),
        "property_id"
    ]
)

#### Invalid property references

In [52]:
unknown_property = (
    ~units["property_id"].isin(valid_property_ids)
)

add_rejection_reason(
    units,
    unknown_property,
    "unknown_property_id"
)

#### validate numeric floor area

In [53]:
units["floor_area_sqm"] = pd.to_numeric(
    units["floor_area_sqm"],
    errors="coerce"
)

In [54]:
invalid_floor_area = (
    units["floor_area_sqm"].isna()
    |
    (units["floor_area_sqm"] <= 0)
)

add_rejection_reason(
    units,
    invalid_floor_area,
    "invalid_floor_area"
)

#### Validate leases

In [55]:
leases = datasets["leases"].copy()

leases["rejection_reason"] = pd.NA

#### convert to dates & rent

In [56]:
leases["start_date"] = pd.to_datetime(
    leases["start_date"],
    errors="coerce"
)

leases["end_date"] = pd.to_datetime(
    leases["end_date"],
    errors="coerce"
)

In [57]:
leases["monthly_rent_usd"] = pd.to_numeric(
    leases["monthly_rent_usd"],
    errors="coerce"
)

#### Detect bad lease dates

In [58]:
bad_start_date = leases["start_date"].isna()

add_rejection_reason(
    leases,
    bad_start_date,
    "invalid_start_date"
)

#### For end dates, you might allow missing end dates for active leases. But if an end date exists and it is before the start

In [59]:
bad_date_order = (
    leases["end_date"].notna()
    &
    leases["start_date"].notna()
    &
    (leases["end_date"] < leases["start_date"])
)

add_rejection_reason(
    leases,
    bad_date_order,
    "end_date_before_start_date"
)

#### Unit foreign key validation (Lease)

In [60]:
valid_unit_ids = set(
    units.loc[
        units["rejection_reason"].isna(),
        "unit_id"
    ]
)

In [61]:
unknown_lease_unit = (
    ~leases["unit_id"].isin(valid_unit_ids)
)

add_rejection_reason(
    leases,
    unknown_lease_unit,
    "unknown_unit_id"
)

#### Validate rent

In [62]:
invalid_rent = (
    leases["monthly_rent_usd"].isna()
    |
    (leases["monthly_rent_usd"] < 0)
)

add_rejection_reason(
    leases,
    invalid_rent,
    "invalid_monthly_rent"
)

#### check duplicate lease IDs

In [63]:
duplicate_lease = leases.duplicated(
    subset=["lease_id"],
    keep=False
)

add_rejection_reason(
    leases,
    duplicate_lease,
    "duplicate_lease_id"
)

#### Validate work orders

In [64]:
work_orders = datasets["work_orders"].copy()

work_orders["rejection_reason"] = pd.NA

In [65]:
duplicate_work_order = work_orders.duplicated(
    subset=["work_order_id"],
    keep=False
)

add_rejection_reason(
    work_orders,
    duplicate_work_order,
    "duplicate_work_order_id"
)

#### Validate work-order unit

In [66]:
unknown_work_order_unit = (
    ~work_orders["unit_id"].isin(valid_unit_ids)
)

add_rejection_reason(
    work_orders,
    unknown_work_order_unit,
    "unknown_unit_id"
)

##### validate response hours

In [67]:
work_orders["response_hours"] = pd.to_numeric(
    work_orders["response_hours"],
    errors="coerce"
)

In [68]:
missing_response = (
    work_orders["response_hours"].isna()
)

add_rejection_reason(
    work_orders,
    missing_response,
    "missing_response_hours"
)

#### checking for negative hours

In [69]:
negative_response = (
    work_orders["response_hours"] < 0
)

add_rejection_reason(
    work_orders,
    negative_response,
    "negative_response_hours"
)

#### Validate work-order date

In [70]:
date_column = "created_date"

if date_column in work_orders.columns:
    work_orders[date_column] = pd.to_datetime(
        work_orders[date_column],
        errors="coerce"
    )
else:
    print(f"Column '{date_column}' not found.")
    print("Available columns:", work_orders.columns.tolist())

Column 'created_date' not found.
Available columns: ['work_order_id', 'unit_id', 'opened_date', 'closed_date', 'priority', 'response_hours', 'cost_usd', 'status', 'rejection_reason']

In [71]:
print(datasets["work_orders"].columns.tolist())

['work_order_id', 'unit_id', 'opened_date', 'closed_date', 'priority', 'response_hours', 'cost_usd', 'status']

#### Validate meter-readings

In [72]:
meter_readings = datasets[
    "meter_readings"
].copy()

meter_readings["rejection_reason"] = pd.NA

In [73]:
meter_readings["energy_kwh"] = pd.to_numeric(
    meter_readings["energy_kwh"],
    errors="coerce"
)

#### Reject invalid numeric values

In [74]:
invalid_kwh = meter_readings["energy_kwh"].isna()

add_rejection_reason(
    meter_readings,
    invalid_kwh,
    "invalid_kwh"
)

#### Detecting negative energy_kwh

In [75]:
negative_kwh = meter_readings["energy_kwh"] < 0

add_rejection_reason(
    meter_readings,
    negative_kwh,
    "negative_kwh"
)

####  checking unit foreign key (metering_reading)

In [76]:
unknown_meter_unit = (
    ~meter_readings["unit_id"].isin(valid_unit_ids)
)

add_rejection_reason(
    meter_readings,
    unknown_meter_unit,
    "unknown_unit_id"
)

#### validate meter_month

In [77]:
print(datasets["meter_readings"].columns.tolist())

['reading_id', 'unit_id', 'reading_month', 'energy_kwh']

In [78]:
meter_readings["reading_month"] = pd.to_datetime(
    meter_readings["reading_month"],
    errors="coerce"
)

In [79]:
bad_meter_date = (
    meter_readings["reading_month"].isna()
)

add_rejection_reason(
    meter_readings,
    bad_meter_date,
    "invalid_reading_date"
)

##### cleaning vs quarantine records

In [80]:
def split_clean_and_quarantine(df):

    clean = df[
        df["rejection_reason"].isna()
    ].copy()

    quarantine = df[
        df["rejection_reason"].notna()
    ].copy()

    clean = clean.drop(
        columns=["rejection_reason"]
    )

    return clean, quarantine

#### Validate and quarantine () function

In [81]:
import pandas as pd


def add_rejection_reason(
    df: pd.DataFrame,
    mask: pd.Series,
    reason: str
):

    current = df.loc[
        mask,
        "rejection_reason"
    ].fillna("")

    df.loc[
        mask,
        "rejection_reason"
    ] = current.apply(
        lambda x:
        f"{x}; {reason}".strip("; ")
        if x
        else reason
    )


def split_clean_and_quarantine(df):

    clean = df[
        df["rejection_reason"].isna()
    ].copy()

    quarantine = df[
        df["rejection_reason"].notna()
    ].copy()

    clean.drop(
        columns=["rejection_reason"],
        inplace=True
    )

    return clean, quarantine


def validate_and_quarantine(
    datasets: dict,
    run_id: str
):

    clean_datasets = {}
    quarantine_datasets = {}
    quality_summary = {}


    # 1. PROPERTIES

    properties = datasets[
        "properties"
    ].copy()

    properties["rejection_reason"] = pd.NA


    duplicate_property = properties.duplicated(
        subset=["property_id"],
        keep=False
    )

    add_rejection_reason(
        properties,
        duplicate_property,
        "duplicate_property_id"
    )


    missing_property = (
        properties["property_id"].isna()
    )

    add_rejection_reason(
        properties,
        missing_property,
        "missing_property_id"
    )


    properties_clean, properties_bad = (
        split_clean_and_quarantine(properties)
    )


    valid_property_ids = set(
        properties_clean["property_id"]
    )


    # 2. UNITS

    units = datasets[
        "units"
    ].copy()

    units["rejection_reason"] = pd.NA


    duplicate_unit = units.duplicated(
        subset=["unit_id"],
        keep=False
    )

    add_rejection_reason(
        units,
        duplicate_unit,
        "duplicate_unit_id"
    )


    unknown_property = (
        ~units["property_id"]
        .isin(valid_property_ids)
    )

    add_rejection_reason(
        units,
        unknown_property,
        "unknown_property_id"
    )


    units["floor_area_sqm"] = pd.to_numeric(
        units["floor_area_sqm"],
        errors="coerce"
    )


    invalid_floor_area = (
        units["floor_area_sqm"].isna()
        |
        (units["floor_area_sqm"] <= 0)
    )

    add_rejection_reason(
        units,
        invalid_floor_area,
        "invalid_floor_area"
    )


    units_clean, units_bad = (
        split_clean_and_quarantine(units)
    )


    valid_unit_ids = set(
        units_clean["unit_id"]
    )


    # 3. LEASES

    leases = datasets[
        "leases"
    ].copy()

    leases["rejection_reason"] = pd.NA


    duplicate_lease = leases.duplicated(
        subset=["lease_id"],
        keep=False
    )

    add_rejection_reason(
        leases,
        duplicate_lease,
        "duplicate_lease_id"
    )


    leases["start_date"] = pd.to_datetime(
        leases["start_date"],
        errors="coerce"
    )


    leases["end_date"] = pd.to_datetime(
        leases["end_date"],
        errors="coerce"
    )


    leases["monthly_rent_usd"] = pd.to_numeric(
        leases["monthly_rent_usd"],
        errors="coerce"
    )


    invalid_start_date = (
        leases["start_date"].isna()
    )

    add_rejection_reason(
        leases,
        invalid_start_date,
        "invalid_start_date"
    )


    invalid_date_order = (
        leases["end_date"].notna()
        &
        leases["start_date"].notna()
        &
        (
            leases["end_date"]
            <
            leases["start_date"]
        )
    )

    add_rejection_reason(
        leases,
        invalid_date_order,
        "end_date_before_start_date"
    )


    unknown_unit = (
        ~leases["unit_id"]
        .isin(valid_unit_ids)
    )

    add_rejection_reason(
        leases,
        unknown_unit,
        "unknown_unit_id"
    )


    invalid_rent = (
        leases["monthly_rent_usd"].isna()
        |
        (
            leases["monthly_rent_usd"]
            < 0
        )
    )

    add_rejection_reason(
        leases,
        invalid_rent,
        "invalid_monthly_rent"
    )


    leases_clean, leases_bad = (
        split_clean_and_quarantine(leases)
    )


    # 4. WORK ORDERS

    work_orders = datasets[
        "work_orders"
    ].copy()

    work_orders["rejection_reason"] = pd.NA


    duplicate_work_order = (
        work_orders.duplicated(
            subset=["work_order_id"],
            keep=False
        )
    )

    add_rejection_reason(
        work_orders,
        duplicate_work_order,
        "duplicate_work_order_id"
    )


    unknown_unit = (
        ~work_orders["unit_id"]
        .isin(valid_unit_ids)
    )

    add_rejection_reason(
        work_orders,
        unknown_unit,
        "unknown_unit_id"
    )


    # Adjust this name if required
    if "response_duration_hours" in work_orders.columns:

        work_orders[
            "response_duration_hours"
        ] = pd.to_numeric(
            work_orders[
                "response_duration_hours"
            ],
            errors="coerce"
        )


        missing_response = (
            work_orders[
                "response_duration_hours"
            ].isna()
        )

        add_rejection_reason(
            work_orders,
            missing_response,
            "missing_response_duration"
        )


        negative_response = (
            work_orders[
                "response_duration_hours"
            ] < 0
        )

        add_rejection_reason(
            work_orders,
            negative_response,
            "negative_response_duration"
        )


    # 5. METER READINGS

    meter_readings = datasets[
        "meter_readings"
    ].copy()

    meter_readings[
        "rejection_reason"
    ] = pd.NA


    meter_readings["energy_kwh"] = pd.to_numeric(
        meter_readings["energy_kwh"],
        errors="coerce"
    )


    invalid_kwh = (
        meter_readings["energy_kwh"].isna()
    )

    add_rejection_reason(
        meter_readings,
        invalid_kwh,
        "invalid_kwh"
    )


    negative_kwh = (
        meter_readings["energy_kwh"] < 0
    )

    add_rejection_reason(
        meter_readings,
        negative_kwh,
        "negative_kwh"
    )


    unknown_unit = (
        ~meter_readings["unit_id"]
        .isin(valid_unit_ids)
    )

    add_rejection_reason(
        meter_readings,
        unknown_unit,
        "unknown_unit_id"
    )


    if "reading_date" in meter_readings.columns:

        meter_readings[
            "reading_date"
        ] = pd.to_datetime(
            meter_readings[
                "reading_date"
            ],
            errors="coerce"
        )


        bad_date = (
            meter_readings[
                "reading_date"
            ].isna()
        )

        add_rejection_reason(
            meter_readings,
            bad_date,
            "invalid_reading_date"
        )


    work_orders_clean, work_orders_bad = (
        split_clean_and_quarantine(
            work_orders
        )
    )

    meter_clean, meter_bad = (
        split_clean_and_quarantine(
            meter_readings
        )
    )


    # STORE RESULTS


    clean_datasets = {

        "properties":
            properties_clean,

        "units":
            units_clean,

        "leases":
            leases_clean,

        "work_orders":
            work_orders_clean,

        "meter_readings":
            meter_clean
    }


    quarantine_datasets = {

        "properties":
            properties_bad,

        "units":
            units_bad,

        "leases":
            leases_bad,

        "work_orders":
            work_orders_bad,

        "meter_readings":
            meter_bad
    }


    
    # QUALITY SUMMARY
    

    for filename in datasets.keys():

        source_rows = len(
            datasets[filename]
        )

        clean_rows = len(
            clean_datasets[filename]
        )

        rejected_rows = len(
            quarantine_datasets[filename]
        )

        quality_summary[filename] = {

            "run_id":
                run_id,

            "source_rows":
                source_rows,

            "clean_rows":
                clean_rows,

            "rejected_rows":
                rejected_rows,

            "reconciliation_check":
                source_rows
                ==
                clean_rows
                + rejected_rows
        }


    return (
        clean_datasets,
        quarantine_datasets,
        quality_summary
    )

#### Run Validation

In [82]:
from datetime import datetime, timezone

run_id = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

In [83]:
print(type(datasets))
print(datasets.keys())
print(run_id)
print(validate_and_quarantine)

<class 'dict'>
dict_keys(['properties', 'units', 'leases', 'work_orders', 'meter_readings'])
20261020_171603
<function validate_and_quarantine at 0x000001947F692480>

In [84]:
from datetime import datetime, timezone

run_id = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

print(run_id)

20261020_171603

In [85]:
clean_datasets, quarantine_datasets, quality_summary = (
    validate_and_quarantine(
        datasets=datasets,
        run_id=run_id
    )
)

In [86]:
def validate_and_quarantine(datasets: dict, run_id: str):

    clean_datasets = {}
    quarantine_datasets = {}
    quality_summary = {}

    # Validation logic goes here

    return (
        clean_datasets,
        quarantine_datasets,
        quality_summary
    )

#### Inspect the quality summary

In [87]:
quality_summary

{'properties': {'run_id': '20261020_171603',
  'source_rows': 12,
  'clean_rows': 12,
  'rejected_rows': 0,
  'reconciliation_check': True},
 'units': {'run_id': '20261020_171603',
  'source_rows': 241,
  'clean_rows': 239,
  'rejected_rows': 2,
  'reconciliation_check': True},
 'leases': {'run_id': '20261020_171603',
  'source_rows': 198,
  'clean_rows': 197,
  'rejected_rows': 1,
  'reconciliation_check': True},
 'work_orders': {'run_id': '20261020_171603',
  'source_rows': 1501,
  'clean_rows': 1489,
  'rejected_rows': 12,
  'reconciliation_check': True},
 'meter_readings': {'run_id': '20261020_171603',
  'source_rows': 1440,
  'clean_rows': 1432,
  'rejected_rows': 8,
  'reconciliation_check': True}}

In [88]:
quality_summary_df = pd.DataFrame(
    quality_summary
).T

quality_summary_df

,run_id,source_rows,clean_rows,rejected_rows,reconciliation_check
properties,20261020_171603,12,12,0,True
units,20261020_171603,241,239,2,True
leases,20261020_171603,198,197,1,True
work_orders,20261020_171603,1501,1489,12,True
meter_readings,20261020_171603,1440,1432,8,True

#### Inspect quarantined records

In [89]:
quarantine_datasets[
    "work_orders"
]

,work_order_id,unit_id,opened_date,closed_date,priority,response_hours,cost_usd,status,rejection_reason
8,WO000009,P008-U016,2026-02-27,2026-03-02,MEDIUM,69.7,153.97,RESOLVED,duplicate_work_order_id
34,WO000035,P999-U999,2026-04-08,NaN,LOW,NaN,82.75,OPEN,unknown_unit_id
70,WO000071,P001-U005,2026-01-04,2026-01-16,HIGH,35.8,393.80,RESOLVED,unknown_unit_id
93,WO000094,P001-U005,2026-06-01,2026-06-01,HIGH,52.0,965.55,RESOLVED,unknown_unit_id
278,WO000279,P001-U005,2026-06-23,2026-06-24,MEDIUM,78.4,514.39,RESOLVED,unknown_unit_id
469,WO000470,P001-U005,2026-01-17,2026-01-28,CRITICAL,23.9,422.12,RESOLVED,unknown_unit_id
515,WO000516,P001-U005,2026-06-02,2026-06-08,LOW,50.6,1143.80,RESOLVED,unknown_unit_id
602,WO000603,P001-U005,2026-03-04,2026-03-09,CRITICAL,56.0,201.89,RESOLVED,unknown_unit_id
1363,WO001364,P001-U005,2026-03-24,2026-03-30,HIGH,89.4,312.22,RESOLVED,unknown_unit_id
1398,WO001399,P001-U005,2026-03-06,2026-03-18,MEDIUM,50.9,917.91,RESOLVED,unknown_unit_id
1425,WO001426,P001-U005,2026-06-19,2026-06-28,LOW,59.8,1113.51,RESOLVED,unknown_unit_id
1500,WO000009,P008-U016,2026-02-27,2026-03-02,MEDIUM,69.7,153.97,RESOLVED,duplicate_work_order_id

In [90]:
quarantine_datasets[
    "meter_readings"
]

   reading_id    unit_id reading_month  energy_kwh rejection_reason
17    R000018  P001-U003    2026-06-01      -45.00     negative_kwh
24    R000025  P001-U005    2026-01-01      625.48  unknown_unit_id
25    R000026  P001-U005    2026-02-01      275.99  unknown_unit_id
26    R000027  P001-U005    2026-03-01      947.82  unknown_unit_id
27    R000028  P001-U005    2026-04-01      551.22  unknown_unit_id
28    R000029  P001-U005    2026-05-01     1089.05  unknown_unit_id
29    R000030  P001-U005    2026-06-01      258.96  unknown_unit_id
34    R000035  P999-U999    2026-05-01     1205.75  unknown_unit_id

In [91]:
quarantine_datasets[
    "units"
]

       unit_id property_id  floor_area_sqm  active   rejection_reason
4    P001-U005        P001             150       1  duplicate_unit_id
240  P001-U005        P001             150       1  duplicate_unit_id

In [92]:
quarantine_datasets[
    "leases"
]

  lease_id    unit_id start_date end_date  monthly_rent_usd rejection_reason
3   L00005  P001-U005 2025-03-16      NaT               975  unknown_unit_id

#### Test duplicate work order

In [93]:
work_order_quarantine = quarantine_datasets[
    "work_orders"
]

assert work_order_quarantine[
    "rejection_reason"
].str.contains(
    "duplicate_work_order_id"
).any()

print("PASS: Duplicate work order detected.")

PASS: Duplicate work order detected.

#### Test unknown unit

In [94]:
all_quarantine = pd.concat(
    quarantine_datasets.values(),
    ignore_index=True
)

assert all_quarantine[
    "rejection_reason"
].astype(str).str.contains(
    "unknown_unit_id"
).any()

print("PASS: Unknown unit detected.")

PASS: Unknown unit detected.

##### Test negative energy_KWh

In [95]:
meter_quarantine = quarantine_datasets[
    "meter_readings"
]

assert meter_quarantine[
    "rejection_reason"
].astype(str).str.contains(
    "negative_kwh"
).any()

print("PASS: Negative kWh detected.")

PASS: Negative kWh detected.

#### Test missing response

In [96]:
missing_response_mask = work_orders["response_hours"].isna()

work_orders.loc[
    missing_response_mask &
    work_orders["rejection_reason"].isna(),
    "rejection_reason"
] = "missing_response_duration"

print("PASS: Missing response detected.")

PASS: Missing response detected.

#### checking each datasets properties

In [97]:
for name, df in quarantine_datasets.items():
    print(f"\nDataset: {name}")

    if (
        not df.empty
        and "rejection_reason" in df.columns
    ):
        print(df["rejection_reason"].unique())

Dataset: properties

Dataset: units
['duplicate_unit_id']

Dataset: leases
['unknown_unit_id']

Dataset: work_orders
['duplicate_work_order_id' 'unknown_unit_id']

Dataset: meter_readings
['negative_kwh' 'unknown_unit_id']

#### Reconciliation Test

In [98]:
for filename, summary in quality_summary.items():

    assert (
        summary["source_rows"]
        ==
        summary["clean_rows"]
        +
        summary["rejected_rows"]
    )

    print(
        f"PASS: {filename} reconciles."
    )

PASS: properties reconciles.
PASS: units reconciles.
PASS: leases reconciles.
PASS: work_orders reconciles.
PASS: meter_readings reconciles.

#### Creating staging directory

In [99]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

STAGING_DIR = (
    PROJECT_ROOT
    / "data"
    / "staging"
)

QUARANTINE_DIR = (
    PROJECT_ROOT
    / "data"
    / "quarantine"
)

STAGING_DIR.mkdir(
    parents=True,
    exist_ok=True
)

QUARANTINE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(STAGING_DIR.resolve())
print(QUARANTINE_DIR.resolve())

C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging
C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\quarantine

#### Save clean datasets

In [100]:
for filename, df in clean_datasets.items():

    output_path = (
        STAGING_DIR
        / filename
    )

    df.to_csv(
        output_path,
        index=False
    )

    print(
        f"Saved clean dataset: "
        f"{output_path}"
    )

Saved clean dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging\properties
Saved clean dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging\units
Saved clean dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging\leases
Saved clean dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging\work_orders
Saved clean dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging\meter_readings

#### Save quarantine datasets

In [101]:
for filename, df in quarantine_datasets.items():

    if df.empty:
        continue

    quarantine_path = (
        QUARANTINE_DIR
        /
        filename.replace(
            ".csv",
            "_quarantine.csv"
        )
    )

    df.to_csv(
        quarantine_path,
        index=False
    )

    print(
        f"Saved quarantine dataset: "
        f"{quarantine_path}"
    )

Saved quarantine dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\quarantine\units
Saved quarantine dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\quarantine\leases
Saved quarantine dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\quarantine\work_orders
Saved quarantine dataset: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\quarantine\meter_readings

#### Save quality summary

In [102]:
QUALITY_DIR = (
    PROJECT_ROOT
    / "data"
    / "curated"
)

QUALITY_DIR.mkdir(
    parents=True,
    exist_ok=True
)

quality_summary_df = pd.DataFrame(
    quality_summary
).T

quality_summary_path = (
    QUALITY_DIR
    / "quality_summary.csv"
)

quality_summary_df.to_csv(
    quality_summary_path
)

print(
    "Quality summary saved to:",
    quality_summary_path.resolve()
)

Quality summary saved to: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\curated\quality_summary.csv

#### Verify output

In [103]:
print("\nRAW DATA")
for file in (
    PROJECT_ROOT
    / "data"
    / "raw"
).glob("*"):
    print(file.name)


print("\nSTAGING DATA")
for file in STAGING_DIR.glob("*"):
    print(file.name)


print("\nQUARANTINE DATA")
for file in QUARANTINE_DIR.glob("*"):
    print(file.name)

RAW DATA
leases.csv
meter_readings.csv
properties.csv
units.csv
work_orders.csv

STAGING DATA
leases
leases.csv
meter_readings
meter_readings.csv
properties
properties.csv
units
units.csv
work_orders
work_orders.csv

QUARANTINE DATA
leases
meter_readings
units
work_orders

#### checking the actual coulmn names on each datasets

In [104]:
for filename, df in datasets.items():

    print("\n", filename)

    print(
        df.columns.tolist()
    )

 properties
['property_id', 'property_name', 'city']

 units
['unit_id', 'property_id', 'floor_area_sqm', 'active']

 leases
['lease_id', 'unit_id', 'start_date', 'end_date', 'monthly_rent_usd']

 work_orders
['work_order_id', 'unit_id', 'opened_date', 'closed_date', 'priority', 'response_hours', 'cost_usd', 'status']

 meter_readings
['reading_id', 'unit_id', 'reading_month', 'energy_kwh']

#### Defining my project paths

In [105]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

STAGING_DIR = PROJECT_ROOT / "data" / "staging"
CURATED_DIR = PROJECT_ROOT / "data" / "curated"

CURATED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Project root:", PROJECT_ROOT)
print("Staging directory:", STAGING_DIR)
print("Curated directory:", CURATED_DIR)

Project root: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline
Staging directory: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging
Curated directory: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\curated

#### Confirming staging files exist

In [106]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql import Window

In [107]:
from pathlib import Path

STAGING_DIR = Path("data/staging")

print("Current working directory:")
print(Path.cwd())

print("\nStaging directory:")
print(STAGING_DIR.resolve())

print("\nFiles in staging:")
for file in STAGING_DIR.glob("*"):
    print(file.name)

Current working directory:
c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook

Staging directory:
C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\staging

Files in staging:
leases.csv
meter_readings.csv
properties.csv
units.csv
work_orders.csv

In [108]:
STAGING_DIR.mkdir(parents=True, exist_ok=True)

clean_datasets["properties"].to_csv(
    STAGING_DIR / "properties.csv",
    index=False
)

clean_datasets["units"].to_csv(
    STAGING_DIR / "units.csv",
    index=False
)

clean_datasets["leases"].to_csv(
    STAGING_DIR / "leases.csv",
    index=False
)

clean_datasets["work_orders"].to_csv(
    STAGING_DIR / "work_orders.csv",
    index=False
)

clean_datasets["meter_readings"].to_csv(
    STAGING_DIR / "meter_readings.csv",
    index=False
)

print("Clean datasets saved to staging.")

Clean datasets saved to staging.

#### check the staging file actually exist

In [109]:
for file in STAGING_DIR.glob("*.csv"):
    print(file)

data\staging\leases.csv
data\staging\meter_readings.csv
data\staging\properties.csv
data\staging\units.csv
data\staging\work_orders.csv

#### Read validated staging data with spark

##### SparkSession

In [110]:
from pyspark.sql import SparkSession, functions as F, Window
spark = (SparkSession.builder
         .appName('PropTech360_Capstone')
         .master('local[*]')
         .getOrCreate())
print('Spark version:', spark.version)

c:\Documents\Desktop\PropTech360_Capstone_project\venv\Lib\site-packages\pyspark\testing\utils.py:127: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

Spark version: 4.2.0

In [111]:
from pyspark.sql import SparkSession

try:
    spark.stop()
except:
    pass

spark = (
    SparkSession.builder
    .appName("PropTech360")
    .master("local[*]")
    .getOrCreate()
)

print("Spark version:", spark.version)

Spark version: 4.2.0

In [112]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
STAGING_DIR = PROJECT_ROOT / "data" / "staging"

print("Project root:", PROJECT_ROOT.resolve())
print("Staging directory:", STAGING_DIR.resolve())
print("Staging exists:", STAGING_DIR.exists())

Project root: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline
Staging directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\staging
Staging exists: True

In [113]:
properties = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(str((STAGING_DIR / "properties.csv").resolve()))
)

units = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(str((STAGING_DIR / "units.csv").resolve()))
)

leases = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(str((STAGING_DIR / "leases.csv").resolve()))
)

work_orders = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(str((STAGING_DIR / "work_orders.csv").resolve()))
)

meter_readings = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(str((STAGING_DIR / "meter_readings.csv").resolve()))
)

#### Checking Schemas

In [114]:
print("PROPERTIES")
properties.printSchema()

print("UNITS")
units.printSchema()

print("LEASES")
leases.printSchema()

print("WORK ORDERS")
work_orders.printSchema()

print("METER READINGS")
meter_readings.printSchema()

PROPERTIES
root
 |-- property_id: string (nullable = true)
 |-- property_name: string (nullable = true)
 |-- city: string (nullable = true)

UNITS
root
 |-- unit_id: string (nullable = true)
 |-- property_id: string (nullable = true)
 |-- floor_area_sqm: integer (nullable = true)
 |-- active: integer (nullable = true)

LEASES
root
 |-- lease_id: string (nullable = true)
 |-- unit_id: string (nullable = true)
 |-- start_date: date (nullable = true)
 |-- end_date: date (nullable = true)
 |-- monthly_rent_usd: integer (nullable = true)

WORK ORDERS
root
 |-- work_order_id: string (nullable = true)
 |-- unit_id: string (nullable = true)
 |-- opened_date: date (nullable = true)
 |-- closed_date: date (nullable = true)
 |-- priority: string (nullable = true)
 |-- response_hours: double (nullable = true)
 |-- cost_usd: double (nullable = true)
 |-- status: string (nullable = true)

METER READINGS
root
 |-- reading_id: string (nullable = true)
 |-- unit_id: string (nullable = true)
 |-- reading_month: date (nullable = true)
 |-- energy_kwh: double (nullable = true)

#### check the actual coulmns names

In [115]:
for name, df in {
    "properties": properties,
    "units": units,
    "leases": leases,
    "work_orders": work_orders,
    "meter_readings": meter_readings
}.items():

    print(name)
    print(df.columns)
    print()

properties
['property_id', 'property_name', 'city']

units
['unit_id', 'property_id', 'floor_area_sqm', 'active']

leases
['lease_id', 'unit_id', 'start_date', 'end_date', 'monthly_rent_usd']

work_orders
['work_order_id', 'unit_id', 'opened_date', 'closed_date', 'priority', 'response_hours', 'cost_usd', 'status']

meter_readings
['reading_id', 'unit_id', 'reading_month', 'energy_kwh']

#### Standardise all the datatypes

#### Properties

In [116]:
properties = (
    properties
    .withColumn(
        "property_id",
        F.col("property_id").cast("string")
    )
)

#### Units

In [117]:
units = (
    units
    .withColumn(
        "unit_id",
        F.col("unit_id").cast("string")
    )
    .withColumn(
        "property_id",
        F.col("property_id").cast("string")
    )
    .withColumn(
        "floor_area_sqm",
        F.col("floor_area_sqm").cast("double")
    )
)

#### Leases

In [118]:
leases = (
    leases
    .withColumn(
        "lease_id",
        F.col("lease_id").cast("string")
    )
    .withColumn(
        "unit_id",
        F.col("unit_id").cast("string")
    )
    .withColumn(
        "start_date",
        F.to_date("start_date")
    )
    .withColumn(
        "end_date",
        F.to_date("end_date")
    )
    .withColumn(
        "monthly_rent_usd",
        F.col("monthly_rent_usd").cast("double")
    )
)

##### Work_orders

In [119]:
work_orders = (
    work_orders
    .withColumn(
        "work_order_id",
        F.col("work_order_id").cast("string")
    )
    .withColumn(
        "unit_id",
        F.col("unit_id").cast("string")
    )
    .withColumn(
        "opened_date",
        F.to_date("opened_date")
    )
    .withColumn(
        "response_hours",
        F.col(
            "response_hours"
        ).cast("double")
    )
)

##### Meter_readings

In [120]:
meter_readings = (
    meter_readings
    .withColumn(
        "reading_id",
        F.col("reading_id").cast("string")
    )
    .withColumn(
        "reading_date",
        F.to_date("reading_month")
    )
    .withColumn(
        "kwh",
        F.col("energy_kwh").cast("double")
    )
)

##### Creating six-month Calender with month-end dates

##### A reproducible approach is to derive the reporting period from the data rather than today's date

##### Earliest lease month starts

In [121]:
report_start = (
    leases
    .select(
        F.trunc(
            F.min("start_date"),
            "month"
        ).alias("report_start")
    )
    .first()["report_start"]
)

print("Reporting start:", report_start)

Reporting start: 2025-01-01

In [122]:
REPORT_START = "2025-01-01"
REPORT_END = "2025-06-30"

In [123]:
calendar = (
    spark.range(1)
    .select(
        F.explode(
            F.sequence(
                F.to_date(
                    F.lit(REPORT_START)
                ),
                F.add_months(
                    F.to_date(
                        F.lit(REPORT_START)
                    ),
                    5
                ),
                F.expr("interval 1 month")
            )
        ).alias("month_start")
    )
)

##### calculate month-end

In [124]:
calendar = (
    calendar
    .withColumn(
        "month_end",
        F.last_day("month_start")
    )
)

In [125]:
calendar.show()

+-----------+----------+
|month_start| month_end|
+-----------+----------+
| 2025-01-01|2025-01-31|
| 2025-02-01|2025-02-28|
| 2025-03-01|2025-03-31|
| 2025-04-01|2025-04-30|
| 2025-05-01|2025-05-31|
| 2025-06-01|2025-06-30|
+-----------+----------+

#####  confirming the six-months calender has been created

In [126]:
assert calendar.count() == 6

print("PASS: Six-month calendar created.")

PASS: Six-month calendar created.

##### Creating all the property-month combination

In [127]:
property_count = (
    properties
    .select("property_id")
    .distinct()
    .count()
)

print("Number of properties:", property_count)

Number of properties: 12

##### create the property-month framework

In [128]:
property_months = (
    properties
    .select(
        "property_id",
        "property_name",
        "city"
    )
    .distinct()
    .crossJoin(calendar)
)

##### checking

In [129]:
print(
    "Property-month rows:",
    property_months.count()
)

Property-month rows: 72

##### creating unit-month base

In [130]:
unit_months = (
    units
    .select(
        "unit_id",
        "property_id"
    )
    .crossJoin(calendar)
)

##### Join Leases to Unit-months

In [131]:
unit_month_leases = (
    unit_months.alias("um")
    .join(
        leases.alias("l"),
        (
            F.col("um.unit_id")
            ==
            F.col("l.unit_id")
        )
        &
        (
            F.col("l.start_date")
            <=
            F.col("um.month_end")
        )
        &
        (
            F.col("l.end_date").isNull()
            |
            (
                F.col("l.end_date")
                >=
                F.col("um.month_end")
            )
        ),
        "left"
    )
)

##### Detecting overlapping lease

In [132]:
lease_overlap_check = (
    unit_month_leases
    .groupBy(
        F.col("um.unit_id").alias("unit_id"),
        F.col("um.month_end").alias("month_end")
    )
    .agg(
        F.count(
            F.col("l.lease_id")
        ).alias("active_lease_count")
    )
)

##### find overlaps

In [133]:
lease_overlaps = (
    lease_overlap_check
    .filter(
        F.col("active_lease_count") > 1
    )
)

#### checking overlaps

In [134]:
print(
    "Lease overlap rows:",
    lease_overlaps.count()
)

Lease overlap rows: 0

##### view the table

In [135]:
lease_overlaps.show(
    truncate=False
)

+-------+---------+------------------+
|unit_id|month_end|active_lease_count|
+-------+---------+------------------+
+-------+---------+------------------+

##### create a window

##### keep the lease with the start date for that unit/month

In [136]:
lease_window = (
    Window
    .partitionBy(
        F.col("um.unit_id"),
        F.col("um.month_end")
    )
    .orderBy(
        F.col("l.start_date").desc(),
        F.col("l.lease_id").desc()
    )
)

##### Apply row number

In [137]:
unit_month_ranked = (
    unit_month_leases
    .withColumn(
        "lease_rank",
        F.row_number().over(
            lease_window
        )
    )
)

##### keep one lease per unit-month

In [138]:
unit_month_snapshot = (
    unit_month_ranked
    .filter(
        F.col("lease_rank") == 1
    )
    .select(
        F.col("um.unit_id").alias("unit_id"),
        F.col("um.property_id").alias("property_id"),
        F.col("um.month_start").alias("month_start"),
        F.col("um.month_end").alias("month_end"),

        F.col("l.lease_id").alias("lease_id"),

        F.col(
            "l.monthly_rent_usd"
        ).alias("monthly_rent_usd")
    )
)

##### Create occupancy indicator

In [139]:
unit_month_snapshot = (
    unit_month_snapshot
    .withColumn(
        "occupied_flag",
        F.when(
            F.col("lease_id").isNotNull(),
            F.lit(1)
        ).otherwise(
            F.lit(0)
        )
    )
)

#### checking the snapshots

In [140]:
unit_month_snapshot.show()

+---------+-----------+-----------+----------+--------+----------------+-------------+
|  unit_id|property_id|month_start| month_end|lease_id|monthly_rent_usd|occupied_flag|
+---------+-----------+-----------+----------+--------+----------------+-------------+
|P001-U001|       P001| 2025-01-01|2025-01-31|    NULL|            NULL|            0|
|P001-U001|       P001| 2025-02-01|2025-02-28|    NULL|            NULL|            0|
|P001-U001|       P001| 2025-03-01|2025-03-31|  L00001|           975.0|            1|
|P001-U001|       P001| 2025-04-01|2025-04-30|  L00001|           975.0|            1|
|P001-U001|       P001| 2025-05-01|2025-05-31|  L00001|           975.0|            1|
|P001-U001|       P001| 2025-06-01|2025-06-30|  L00001|           975.0|            1|
|P001-U002|       P001| 2025-01-01|2025-01-31|    NULL|            NULL|            0|
|P001-U002|       P001| 2025-02-01|2025-02-28|    NULL|            NULL|            0|
|P001-U002|       P001| 2025-03-01|2025-03-31|    NULL|            NULL|            0|
|P001-U002|       P001| 2025-04-01|2025-04-30|    NULL|            NULL|            0|
|P001-U002|       P001| 2025-05-01|2025-05-31|    NULL|            NULL|            0|
|P001-U002|       P001| 2025-06-01|2025-06-30|    NULL|            NULL|            0|
|P001-U003|       P001| 2025-01-01|2025-01-31|    NULL|            NULL|            0|
|P001-U003|       P001| 2025-02-01|2025-02-28|    NULL|            NULL|            0|
|P001-U003|       P001| 2025-03-01|2025-03-31|    NULL|            NULL|            0|
|P001-U003|       P001| 2025-04-01|2025-04-30|    NULL|            NULL|            0|
|P001-U003|       P001| 2025-05-01|2025-05-31|    NULL|            NULL|            0|
|P001-U003|       P001| 2025-06-01|2025-06-30|    NULL|            NULL|            0|
|P001-U004|       P001| 2025-01-01|2025-01-31|    NULL|            NULL|            0|
|P001-U004|       P001| 2025-02-01|2025-02-28|    NULL|            NULL|            0|
+---------+-----------+-----------+----------+--------+----------------+-------------+
only showing top 20 rows

#### Calculate property-month occupancy INDEPENDENTLY

##### Do not join the work orders and meter readings directly to individual lease records at the beginning, as this can create duplicate rows and inflate the data.

#### Instead, calculate the results for each business area independently before combining them.

##### FOR occupancy/rent

In [141]:
occupancy_rent = (
    unit_month_snapshot
    .groupBy(
        "property_id",
        "month_end"
    )
    .agg(
        F.countDistinct(
            "unit_id"
        ).alias("total_units"),

        F.sum(
            "occupied_flag"
        ).alias("occupied_units"),

        F.sum(
            F.when(
                F.col("occupied_flag") == 1,
                F.col("monthly_rent_usd")
            ).otherwise(
                F.lit(0.0)
            )
        ).alias("monthly_rent_usd")
    )
)

#### Calculate occupancy rate

In [142]:
occupancy_rent = (
    occupancy_rent
    .withColumn(
        "occupancy_rate",
        F.when(
            F.col("total_units") > 0,
            F.col("occupied_units")
            /
            F.col("total_units")
        ).otherwise(
            F.lit(0.0)
        )
    )
)

#### You can also express the result as a percentage

In [143]:
occupancy_rent = (
    occupancy_rent
    .withColumn(
        "occupancy_pct",
        F.round(
            F.col("occupancy_rate") * 100,
            2
        )
    )
)

In [144]:
occupancy_rent.show()

+-----------+----------+-----------+--------------+----------------+-------------------+-------------+
|property_id| month_end|total_units|occupied_units|monthly_rent_usd|     occupancy_rate|occupancy_pct|
+-----------+----------+-----------+--------------+----------------+-------------------+-------------+
|       P002|2025-02-28|         20|             4|          5875.0|                0.2|         20.0|
|       P006|2025-04-30|         20|            11|         18600.0|               0.55|         55.0|
|       P008|2025-02-28|         20|             6|          7950.0|                0.3|         30.0|
|       P006|2025-02-28|         20|             3|          5900.0|               0.15|         15.0|
|       P011|2025-02-28|         20|             4|          5325.0|                0.2|         20.0|
|       P002|2025-03-31|         20|             5|          6675.0|               0.25|         25.0|
|       P010|2025-02-28|         20|             1|           975.0|               0.05|          5.0|
|       P003|2025-05-31|         20|             7|          8725.0|               0.35|         35.0|
|       P001|2025-02-28|         19|             1|           800.0|0.05263157894736842|         5.26|
|       P003|2025-02-28|         20|             1|          2200.0|               0.05|          5.0|
|       P005|2025-05-31|         20|             4|          4100.0|                0.2|         20.0|
|       P005|2025-03-31|         20|             4|          4100.0|                0.2|         20.0|
|       P009|2025-04-30|         20|             7|          9125.0|               0.35|         35.0|
|       P010|2025-06-30|         20|             7|          8150.0|               0.35|         35.0|
|       P003|2025-04-30|         20|             6|          7925.0|                0.3|         30.0|
|       P011|2025-01-31|         20|             2|          1625.0|                0.1|         10.0|
|       P006|2025-03-31|         20|             8|         13400.0|                0.4|         40.0|
|       P011|2025-06-30|         20|            11|         13350.0|               0.55|         55.0|
|       P011|2025-05-31|         20|            11|         13350.0|               0.55|         55.0|
|       P012|2025-05-31|         20|             6|          9100.0|                0.3|         30.0|
+-----------+----------+-----------+--------------+----------------+-------------------+-------------+
only showing top 20 rows

#### Prepare worder_orders independently

##### First, link each work order to the correct property using the unit information:

In [145]:
work_orders_enriched = (
    work_orders.alias("w")
    .join(
        units.select(
            "unit_id",
            "property_id"
        ).alias("u"),
        F.col("w.unit_id")
        ==
        F.col("u.unit_id"),
        "inner"
    )
)

#### Creating month

In [146]:
work_orders_enriched = (
    work_orders_enriched
    .withColumn(
        "month_end",
        F.last_day(
            F.col("opened_date")
        )
    )
)

#### Defien Service Level Agreement (SLA)

##### You need to define a clear SLA time limit

In [147]:
SLA_HOURS = 24

##### After that:

In [148]:
work_orders_enriched = (
    work_orders_enriched
    .withColumn(
        "sla_met",
        F.when(
            F.col(
                "response_hours"
            )
            <= SLA_HOURS,
            F.lit(1)
        ).otherwise(
            F.lit(0)
        )
    )
)

#### Aggregate SLA independently

In [149]:
sla_metrics = (
    work_orders_enriched
    .groupBy(
        "property_id",
        "month_end"
    )
    .agg(
        F.count(
            "*"
        ).alias("work_order_count"),

        F.avg(
            "response_hours"
        ).alias(
            "avg_response_hours"
        ),

        F.sum(
            "sla_met"
        ).alias(
            "sla_met_count"
        )
    )
)

##### Then calculate SLA percentage

In [150]:
sla_metrics = (
    sla_metrics
    .withColumn(
        "sla_pct",
        F.when(
            F.col("work_order_count") > 0,

            F.round(
                F.col("sla_met_count")
                /
                F.col("work_order_count")
                * 100,
                2
            )
        ).otherwise(
            F.lit(None)
        )
    )
)

#### Check

In [151]:
sla_metrics.show()

+-----------+----------+----------------+------------------+-------------+-------+
|property_id| month_end|work_order_count|avg_response_hours|sla_met_count|sla_pct|
+-----------+----------+----------------+------------------+-------------+-------+
|       P004|2026-03-31|              13|             43.17|            2|  15.38|
|       P005|2026-05-31|              16| 53.00769230769231|            3|  18.75|
|       P006|2026-05-31|              20|55.228571428571435|            1|    5.0|
|       P010|2026-02-28|              17| 58.54615384615384|            2|  11.76|
|       P001|2026-04-30|              15| 56.31818181818183|            1|   6.67|
|       P007|2026-02-28|              31|39.634482758620685|           13|  41.94|
|       P009|2026-06-30|              15|48.718181818181826|            2|  13.33|
|       P002|2026-04-30|              27|51.777272727272724|            4|  14.81|
|       P010|2026-05-31|              24| 51.19500000000001|            5|  20.83|
|       P009|2026-05-31|              27| 43.60476190476191|            8|  29.63|
|       P005|2026-06-30|              25|28.042105263157897|           10|   40.0|
|       P008|2026-01-31|              19| 57.29411764705883|            3|  15.79|
|       P005|2026-01-31|              23| 47.60526315789474|            6|  26.09|
|       P007|2026-01-31|              15| 48.29230769230769|            3|   20.0|
|       P011|2026-06-30|              18| 54.38000000000001|            3|  16.67|
|       P007|2026-03-31|              21| 36.86666666666667|            6|  28.57|
|       P009|2026-01-31|              19| 43.18571428571429|            4|  21.05|
|       P005|2026-03-31|              18|          56.63125|            2|  11.11|
|       P010|2026-06-30|              22| 43.22666666666667|            6|  27.27|
|       P011|2026-04-30|              16| 35.68666666666666|            6|   37.5|
+-----------+----------+----------------+------------------+-------------+-------+
only showing top 20 rows

##### Prepare meter readings(energy bill) independently

##### Link the meter readings to the corresponding units:

In [152]:
energy_enriched = (
    meter_readings.alias("m")
    .join(
        units.select(
            "unit_id",
            "property_id"
        ).alias("u"),
        F.col("m.unit_id")
        ==
        F.col("u.unit_id"),
        "inner"
    )
)

##### Add Month-end

In [153]:
energy_enriched = (
    energy_enriched
    .withColumn(
        "month_end",
        F.last_day(
            F.col("reading_date")
        )
    )
)

#### Calculate property-month energy independently

In [154]:
energy_metrics = (
    energy_enriched
    .groupBy(
        "property_id",
        "month_end"
    )
    .agg(
        F.sum(
            "kwh"
        ).alias(
            "total_energy_kwh"
        ),

        F.avg(
            "kwh"
        ).alias(
            "avg_reading_kwh"
        ),

        F.count(
            "*"
        ).alias(
            "meter_reading_count"
        )
    )
)

##### check

In [155]:
energy_metrics.show()

+-----------+----------+------------------+-----------------+-------------------+
|property_id| month_end|  total_energy_kwh|  avg_reading_kwh|meter_reading_count|
+-----------+----------+------------------+-----------------+-------------------+
|       P004|2026-03-31|12853.620000000003|642.6810000000002|                 20|
|       P005|2026-05-31|16005.140000000001|800.2570000000001|                 20|
|       P006|2026-05-31|           13575.5|          678.775|                 20|
|       P010|2026-02-28|          14572.61|         728.6305|                 20|
|       P001|2026-04-30|           14376.2| 756.642105263158|                 19|
|       P007|2026-02-28|14900.219999999998|745.0109999999999|                 20|
|       P009|2026-06-30|16448.699999999997|822.4349999999998|                 20|
|       P002|2026-04-30|12719.989999999998|635.9994999999999|                 20|
|       P010|2026-05-31|14956.550000000003|747.8275000000001|                 20|
|       P009|2026-05-31|11455.169999999998|572.7584999999999|                 20|
|       P005|2026-06-30|15636.960000000001|781.8480000000001|                 20|
|       P008|2026-01-31|12431.230000000003|621.5615000000001|                 20|
|       P005|2026-01-31|13274.710000000001|         663.7355|                 20|
|       P007|2026-01-31|13126.460000000001|656.3230000000001|                 20|
|       P007|2026-03-31|          15668.18|          783.409|                 20|
|       P011|2026-06-30|12590.619999999999|          629.531|                 20|
|       P009|2026-01-31|          13197.17|         659.8585|                 20|
|       P005|2026-03-31|15322.839999999997|766.1419999999998|                 20|
|       P010|2026-06-30|          12853.26|          642.663|                 20|
|       P011|2026-04-30|12574.029999999999|628.7014999999999|                 20|
+-----------+----------+------------------+-----------------+-------------------+
only showing top 20 rows

##### Confirm the three independent aggregates

In [156]:
occupancy_rent

DataFrame[property_id: string, month_end: date, total_units: bigint, occupied_units: bigint, monthly_rent_usd: double, occupancy_rate: double, occupancy_pct: double]

In [157]:
energy_metrics

DataFrame[property_id: string, month_end: date, total_energy_kwh: double, avg_reading_kwh: double, meter_reading_count: bigint]

#### Start the final output using the property-month base table

In [158]:
property_months

DataFrame[property_id: string, property_name: string, city: string, month_start: date, month_end: date]

#### Start with:

In [159]:
property_month_kpis = (
    property_months
    .select(
        "property_id",
        "property_name",
        "city",
        "month_start",
        "month_end"
    )
)

##### Join Occupancy

In [160]:
property_month_kpis = (
    property_month_kpis
    .join(
        occupancy_rent,
        on=[
            "property_id",
            "month_end"
        ],
        how="left"
    )
)

#### Join SLA metrics

In [161]:
property_month_kpis = (
    property_month_kpis
    .join(
        sla_metrics,
        on=[
            "property_id",
            "month_end"
        ],
        how="left"
    )
)

#### Join energy metrics

In [162]:
property_month_kpis = (
    property_month_kpis
    .join(
        energy_metrics,
        on=[
            "property_id",
            "month_end"
        ],
        how="left"
    )
)

#### Fill appropriate missing values

##### For count/total fields, use zero where logically appropriate

In [163]:
property_month_kpis = (
    property_month_kpis
    .fillna(
        {
            "total_units": 0,
            "occupied_units": 0,
            "monthly_rent_usd": 0.0,
            "occupancy_rate": 0.0,
            "occupancy_pct": 0.0,
            "work_order_count": 0,
            "sla_met_count": 0,
            "total_energy_kwh": 0.0,
            "meter_reading_count": 0
        }
    )
)

#### Round business metrics

In [164]:
property_month_kpis = (
    property_month_kpis
    .withColumn(
        "monthly_rent_usd",
        F.round(
            "monthly_rent_usd",
            2
        )
    )
    .withColumn(
        "avg_response_hours",
        F.round(
            "avg_response_hours",
            2
        )
    )
    .withColumn(
        "total_energy_kwh",
        F.round(
            "total_energy_kwh",
            2
        )
    )
    .withColumn(
        "avg_reading_kwh",
        F.round(
            "avg_reading_kwh",
            2
        )
    )
)

#### Organise the results

In [165]:
property_month_kpis = (
    property_month_kpis
    .orderBy(
        "property_id",
        "month_end"
    )
)

In [166]:
property_month_kpis.show(
    100,
    truncate=False
)

+-----------+----------+-------------------+-------------+-----------+-----------+--------------+----------------+-------------------+-------------+----------------+------------------+-------------+-------+----------------+---------------+-------------------+
|property_id|month_end |property_name      |city         |month_start|total_units|occupied_units|monthly_rent_usd|occupancy_rate     |occupancy_pct|work_order_count|avg_response_hours|sla_met_count|sla_pct|total_energy_kwh|avg_reading_kwh|meter_reading_count|
+-----------+----------+-------------------+-------------+-----------+-----------+--------------+----------------+-------------------+-------------+----------------+------------------+-------------+-------+----------------+---------------+-------------------+
|P001       |2025-01-31|MetroSpace Tower 01|Lagos        |2025-01-01 |19         |1             |800.0           |0.05263157894736842|5.26         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P001       |2025-02-28|MetroSpace Tower 01|Lagos        |2025-02-01 |19         |1             |800.0           |0.05263157894736842|5.26         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P001       |2025-03-31|MetroSpace Tower 01|Lagos        |2025-03-01 |19         |3             |2425.0          |0.15789473684210525|15.79        |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P001       |2025-04-30|MetroSpace Tower 01|Lagos        |2025-04-01 |19         |3             |2425.0          |0.15789473684210525|15.79        |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P001       |2025-05-31|MetroSpace Tower 01|Lagos        |2025-05-01 |19         |5             |4425.0          |0.2631578947368421 |26.32        |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P001       |2025-06-30|MetroSpace Tower 01|Lagos        |2025-06-01 |19         |6             |6625.0          |0.3157894736842105 |31.58        |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P002       |2025-01-31|MetroSpace Tower 02|Abuja        |2025-01-01 |20         |2             |2700.0          |0.1                |10.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P002       |2025-02-28|MetroSpace Tower 02|Abuja        |2025-02-01 |20         |4             |5875.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P002       |2025-03-31|MetroSpace Tower 02|Abuja        |2025-03-01 |20         |5             |6675.0          |0.25               |25.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P002       |2025-04-30|MetroSpace Tower 02|Abuja        |2025-04-01 |20         |8             |11350.0         |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P002       |2025-05-31|MetroSpace Tower 02|Abuja        |2025-05-01 |20         |8             |11350.0         |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P002       |2025-06-30|MetroSpace Tower 02|Abuja        |2025-06-01 |20         |8             |11350.0         |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P003       |2025-01-31|MetroSpace Tower 03|Ibadan       |2025-01-01 |20         |1             |2200.0          |0.05               |5.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P003       |2025-02-28|MetroSpace Tower 03|Ibadan       |2025-02-01 |20         |1             |2200.0          |0.05               |5.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P003       |2025-03-31|MetroSpace Tower 03|Ibadan       |2025-03-01 |20         |4             |5150.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P003       |2025-04-30|MetroSpace Tower 03|Ibadan       |2025-04-01 |20         |6             |7925.0          |0.3                |30.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P003       |2025-05-31|MetroSpace Tower 03|Ibadan       |2025-05-01 |20         |7             |8725.0          |0.35               |35.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P003       |2025-06-30|MetroSpace Tower 03|Ibadan       |2025-06-01 |20         |9             |12725.0         |0.45               |45.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P004       |2025-01-31|MetroSpace Tower 04|Port Harcourt|2025-01-01 |20         |1             |650.0           |0.05               |5.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P004       |2025-02-28|MetroSpace Tower 04|Port Harcourt|2025-02-01 |20         |1             |650.0           |0.05               |5.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P004       |2025-03-31|MetroSpace Tower 04|Port Harcourt|2025-03-01 |20         |2             |2450.0          |0.1                |10.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P004       |2025-04-30|MetroSpace Tower 04|Port Harcourt|2025-04-01 |20         |4             |4300.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P004       |2025-05-31|MetroSpace Tower 04|Port Harcourt|2025-05-01 |20         |4             |4300.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P004       |2025-06-30|MetroSpace Tower 04|Port Harcourt|2025-06-01 |20         |4             |4300.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P005       |2025-01-31|MetroSpace Tower 05|Lagos        |2025-01-01 |20         |1             |975.0           |0.05               |5.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P005       |2025-02-28|MetroSpace Tower 05|Lagos        |2025-02-01 |20         |1             |975.0           |0.05               |5.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P005       |2025-03-31|MetroSpace Tower 05|Lagos        |2025-03-01 |20         |4             |4100.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P005       |2025-04-30|MetroSpace Tower 05|Lagos        |2025-04-01 |20         |4             |4100.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P005       |2025-05-31|MetroSpace Tower 05|Lagos        |2025-05-01 |20         |4             |4100.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P005       |2025-06-30|MetroSpace Tower 05|Lagos        |2025-06-01 |20         |5             |4750.0          |0.25               |25.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P006       |2025-01-31|MetroSpace Tower 06|Abuja        |2025-01-01 |20         |2             |3700.0          |0.1                |10.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P006       |2025-02-28|MetroSpace Tower 06|Abuja        |2025-02-01 |20         |3             |5900.0          |0.15               |15.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P006       |2025-03-31|MetroSpace Tower 06|Abuja        |2025-03-01 |20         |8             |13400.0         |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P006       |2025-04-30|MetroSpace Tower 06|Abuja        |2025-04-01 |20         |11            |18600.0         |0.55               |55.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P006       |2025-05-31|MetroSpace Tower 06|Abuja        |2025-05-01 |20         |11            |18600.0         |0.55               |55.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P006       |2025-06-30|MetroSpace Tower 06|Abuja        |2025-06-01 |20         |11            |18600.0         |0.55               |55.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P007       |2025-01-31|MetroSpace Tower 07|Ibadan       |2025-01-01 |20         |2             |3400.0          |0.1                |10.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P007       |2025-02-28|MetroSpace Tower 07|Ibadan       |2025-02-01 |20         |4             |5175.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P007       |2025-03-31|MetroSpace Tower 07|Ibadan       |2025-03-01 |20         |4             |5175.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P007       |2025-04-30|MetroSpace Tower 07|Ibadan       |2025-04-01 |20         |4             |5175.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P007       |2025-05-31|MetroSpace Tower 07|Ibadan       |2025-05-01 |20         |5             |5975.0          |0.25               |25.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P007       |2025-06-30|MetroSpace Tower 07|Ibadan       |2025-06-01 |20         |5             |5975.0          |0.25               |25.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P008       |2025-01-31|MetroSpace Tower 08|Port Harcourt|2025-01-01 |20         |4             |4950.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P008       |2025-02-28|MetroSpace Tower 08|Port Harcourt|2025-02-01 |20         |6             |7950.0          |0.3                |30.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P008       |2025-03-31|MetroSpace Tower 08|Port Harcourt|2025-03-01 |20         |8             |9950.0          |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P008       |2025-04-30|MetroSpace Tower 08|Port Harcourt|2025-04-01 |20         |8             |9950.0          |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P008       |2025-05-31|MetroSpace Tower 08|Port Harcourt|2025-05-01 |20         |8             |9950.0          |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P008       |2025-06-30|MetroSpace Tower 08|Port Harcourt|2025-06-01 |20         |9             |10750.0         |0.45               |45.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P009       |2025-01-31|MetroSpace Tower 09|Lagos        |2025-01-01 |20         |3             |3825.0          |0.15               |15.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P009       |2025-02-28|MetroSpace Tower 09|Lagos        |2025-02-01 |20         |5             |7525.0          |0.25               |25.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P009       |2025-03-31|MetroSpace Tower 09|Lagos        |2025-03-01 |20         |5             |7525.0          |0.25               |25.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P009       |2025-04-30|MetroSpace Tower 09|Lagos        |2025-04-01 |20         |7             |9125.0          |0.35               |35.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P009       |2025-05-31|MetroSpace Tower 09|Lagos        |2025-05-01 |20         |7             |9125.0          |0.35               |35.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P009       |2025-06-30|MetroSpace Tower 09|Lagos        |2025-06-01 |20         |8             |9775.0          |0.4                |40.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P010       |2025-01-31|MetroSpace Tower 10|Abuja        |2025-01-01 |20         |0             |0.0             |0.0                |0.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P010       |2025-02-28|MetroSpace Tower 10|Abuja        |2025-02-01 |20         |1             |975.0           |0.05               |5.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P010       |2025-03-31|MetroSpace Tower 10|Abuja        |2025-03-01 |20         |2             |1950.0          |0.1                |10.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P010       |2025-04-30|MetroSpace Tower 10|Abuja        |2025-04-01 |20         |3             |3750.0          |0.15               |15.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P010       |2025-05-31|MetroSpace Tower 10|Abuja        |2025-05-01 |20         |5             |5750.0          |0.25               |25.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P010       |2025-06-30|MetroSpace Tower 10|Abuja        |2025-06-01 |20         |7             |8150.0          |0.35               |35.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P011       |2025-01-31|MetroSpace Tower 11|Ibadan       |2025-01-01 |20         |2             |1625.0          |0.1                |10.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P011       |2025-02-28|MetroSpace Tower 11|Ibadan       |2025-02-01 |20         |4             |5325.0          |0.2                |20.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P011       |2025-03-31|MetroSpace Tower 11|Ibadan       |2025-03-01 |20         |9             |11050.0         |0.45               |45.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P011       |2025-04-30|MetroSpace Tower 11|Ibadan       |2025-04-01 |20         |9             |11050.0         |0.45               |45.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P011       |2025-05-31|MetroSpace Tower 11|Ibadan       |2025-05-01 |20         |11            |13350.0         |0.55               |55.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P011       |2025-06-30|MetroSpace Tower 11|Ibadan       |2025-06-01 |20         |11            |13350.0         |0.55               |55.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P012       |2025-01-31|MetroSpace Tower 12|Port Harcourt|2025-01-01 |20         |0             |0.0             |0.0                |0.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P012       |2025-02-28|MetroSpace Tower 12|Port Harcourt|2025-02-01 |20         |0             |0.0             |0.0                |0.0          |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P012       |2025-03-31|MetroSpace Tower 12|Port Harcourt|2025-03-01 |20         |2             |2700.0          |0.1                |10.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P012       |2025-04-30|MetroSpace Tower 12|Port Harcourt|2025-04-01 |20         |3             |4200.0          |0.15               |15.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P012       |2025-05-31|MetroSpace Tower 12|Port Harcourt|2025-05-01 |20         |6             |9100.0          |0.3                |30.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
|P012       |2025-06-30|MetroSpace Tower 12|Port Harcourt|2025-06-01 |20         |7             |9900.0          |0.35               |35.0         |0               |NULL              |0            |NULL   |0.0             |NULL           |0                  |
+-----------+----------+-------------------+-------------+-----------+-----------+--------------+----------------+-------------------+-------------+----------------+------------------+-------------+-------+----------------+---------------+-------------------+

#### Assert exactly 72 rows

##### First count rows:

In [167]:
row_count = property_month_kpis.count()

print("Total rows:", row_count)

Total rows: 72

In [168]:
assert row_count == 72, (
    f"Expected 72 rows, "
    f"but found {row_count}"
)

print("PASS: Exactly 72 rows.")

PASS: Exactly 72 rows.

#### Assert Uniqueness

In [169]:
unique_count = (
    property_month_kpis
    .select(
        "property_id",
        "month_end"
    )
    .distinct()
    .count()
)

##### assertion

In [170]:
assert unique_count == 72, (
    f"Expected 72 unique "
    f"property-month combinations, "
    f"but found {unique_count}"
)

print(
    "PASS: 72 unique property-month rows."
)

PASS: 72 unique property-month rows.

#### Check for duplicates

In [171]:
duplicate_property_months = (
    property_month_kpis
    .groupBy(
        "property_id",
        "month_end"
    )
    .count()
    .filter(
        F.col("count") > 1
    )
)

In [172]:
assert duplicate_property_months.count() == 0

print(
    "PASS: No duplicate "
    "property-month records."
)

PASS: No duplicate property-month records.

#### Validate expected six months

In [173]:
month_count = (
    property_month_kpis
    .select("month_end")
    .distinct()
    .count()
)

assert month_count == 6

print("PASS: Exactly six months.")

PASS: Exactly six months.

#### Validate expected properties

In [174]:
property_count = (
    property_month_kpis
    .select("property_id")
    .distinct()
    .count()
)

print(
    "Distinct properties:",
    property_count
)

Distinct properties: 12

In [175]:
assert property_count * month_count == 72

print(
    "PASS:",
    property_count,
    "properties ×",
    month_count,
    "months = 72"
)

PASS: 12 properties × 6 months = 72

#### Add a partition column

##### Write a Parquet partitioned by month

##### Create

In [176]:
property_month_kpis = (
    property_month_kpis
    .withColumn(
        "report_month",
        F.date_format(
            "month_end",
            "yyyy-MM"
        )
    )
)

#### Define Parquet output path

In [177]:
from pathlib import Path

PARQUET_OUTPUT = Path(
    "data/processed/property_month_kpis"
).resolve()

PARQUET_OUTPUT.parent.mkdir(
    parents=True,
    exist_ok=True
)

print("Parquet output path:")
print(PARQUET_OUTPUT)

Parquet output path:
C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\processed\property_month_kpis

In [178]:
property_month_kpis

DataFrame[property_id: string, month_end: date, property_name: string, city: string, month_start: date, total_units: bigint, occupied_units: bigint, monthly_rent_usd: double, occupancy_rate: double, occupancy_pct: double, work_order_count: bigint, avg_response_hours: double, sla_met_count: bigint, sla_pct: double, total_energy_kwh: double, avg_reading_kwh: double, meter_reading_count: bigint, report_month: string]

In [179]:
property_month_kpis.select(
    "property_id",
    "month_end"
).show(10, truncate=False)

+-----------+----------+
|property_id|month_end |
+-----------+----------+
|P001       |2025-01-31|
|P001       |2025-02-28|
|P001       |2025-03-31|
|P001       |2025-04-30|
|P001       |2025-05-31|
|P001       |2025-06-30|
|P002       |2025-01-31|
|P002       |2025-02-28|
|P002       |2025-03-31|
|P002       |2025-04-30|
+-----------+----------+
only showing top 10 rows

In [180]:
from pyspark.sql import functions as F

property_month_kpis = (
    property_month_kpis
    .withColumn(
        "report_month",
        F.date_format(
            F.col("month_end"),
            "yyyy-MM"
        )
    )
)

In [181]:
property_month_kpis.select(
    "property_id",
    "month_end",
    "report_month"
).show(20, truncate=False)

+-----------+----------+------------+
|property_id|month_end |report_month|
+-----------+----------+------------+
|P001       |2025-01-31|2025-01     |
|P001       |2025-02-28|2025-02     |
|P001       |2025-03-31|2025-03     |
|P001       |2025-04-30|2025-04     |
|P001       |2025-05-31|2025-05     |
|P001       |2025-06-30|2025-06     |
|P002       |2025-01-31|2025-01     |
|P002       |2025-02-28|2025-02     |
|P002       |2025-03-31|2025-03     |
|P002       |2025-04-30|2025-04     |
|P002       |2025-05-31|2025-05     |
|P002       |2025-06-30|2025-06     |
|P003       |2025-01-31|2025-01     |
|P003       |2025-02-28|2025-02     |
|P003       |2025-03-31|2025-03     |
|P003       |2025-04-30|2025-04     |
|P003       |2025-05-31|2025-05     |
|P003       |2025-06-30|2025-06     |
|P004       |2025-01-31|2025-01     |
|P004       |2025-02-28|2025-02     |
+-----------+----------+------------+
only showing top 20 rows

In [182]:
if "report_month" not in property_month_kpis.columns:
    raise ValueError(
        "The column 'report_month' is missing from property_month_kpis."
    )

In [183]:
property_month_kpis.select("report_month").distinct().show()

+------------+
|report_month|
+------------+
|     2025-04|
|     2025-01|
|     2025-06|
|     2025-02|
|     2025-03|
|     2025-05|
+------------+

In [184]:
# ============================================================
# FINAL DATA QUALITY CHECKS
# ============================================================

# 1. Confirm exactly 72 property-month rows
row_count = property_month_kpis.count()

if row_count != 72:
    raise ValueError(
        f"Unexpected property-month row count. "
        f"Expected 72, found {row_count}."
    )


# 2. Confirm exactly 72 unique property-month keys
unique_keys_count = (
    property_month_kpis
    .select(
        "property_id",
        "month_end"
    )
    .distinct()
    .count()
)

if unique_keys_count != 72:
    raise ValueError(
        f"Duplicate property-month keys found. "
        f"Expected 72 unique keys, found {unique_keys_count}."
    )


# 3. Validate occupancy rate
invalid_occupancy = (
    property_month_kpis
    .filter(
        (F.col("occupancy_rate") < 0)
        |
        (F.col("occupancy_rate") > 1)
    )
    .count()
)

if invalid_occupancy > 0:
    raise ValueError(
        "Invalid occupancy_rate found outside range [0, 1]."
    )


print("PASS: Final KPI quality checks passed.")

PASS: Final KPI quality checks passed.

In [185]:
# ============================================================
# CREATE MONTH PARTITION COLUMN
# ============================================================

property_month_kpis = (
    property_month_kpis
    .withColumn(
        "report_month",
        F.date_format(
            F.col("month_end"),
            "yyyy-MM"
        )
    )
)

In [186]:
# ============================================================
# VALIDATE REPORTING MONTHS
# ============================================================

month_count = (
    property_month_kpis
    .select("report_month")
    .distinct()
    .count()
)

if month_count != 6:
    raise ValueError(
        f"Expected 6 reporting months, "
        f"found {month_count}."
    )


null_months = (
    property_month_kpis
    .filter(
        F.col("report_month").isNull()
    )
    .count()
)

if null_months > 0:
    raise ValueError(
        f"Found {null_months} rows with null report_month."
    )


print("PASS: 6 valid report_month partitions found.")

PASS: 6 valid report_month partitions found.

In [187]:
from pathlib import Path

# Define the project root directory
PROJECT_ROOT = Path.cwd()

# Define curated data directory
CURATED_DIR = PROJECT_ROOT / "data" / "curated"

# Create directory if it does not exist
CURATED_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Curated directory:", CURATED_DIR)
print("Directory exists:", CURATED_DIR.exists())

Project root: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook
Curated directory: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated
Directory exists: True

In [188]:
# ============================================================
# DEFINE CURATED PARQUET OUTPUT
# ============================================================

PARQUET_OUTPUT = CURATED_DIR / "property_month_kpis"

print("Parquet output location:", PARQUET_OUTPUT)

Parquet output location: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated\property_month_kpis

In [189]:
unique_keys_count = (
    property_month_kpis
    .select(
        "property_id",
        "month_end"
    )
    .distinct()
    .count()
)

In [190]:
from pathlib import Path
from pyspark.sql import functions as F

# ============================================================
# PROPTECH360 - CURATED PARQUET CONFIGURATION
# ============================================================

# Use existing CURATED_DIR if already defined.
# Otherwise, locate it relative to the project root.

if "CURATED_DIR" not in globals():
    PROJECT_ROOT = Path.cwd()

    if PROJECT_ROOT.name.lower() == "notebooks":
        PROJECT_ROOT = PROJECT_ROOT.parent

    CURATED_DIR = PROJECT_ROOT / "data" / "curated"

CURATED_DIR = Path(CURATED_DIR).resolve()

# Create curated directory if necessary
CURATED_DIR.mkdir(parents=True, exist_ok=True)

# Define final Parquet dataset path
PARQUET_OUTPUT = CURATED_DIR / "property_month_kpis"

print("Working directory:", Path.cwd())
print("Curated directory:", CURATED_DIR)
print("Parquet output:", PARQUET_OUTPUT)
print("Directory exists:", CURATED_DIR.exists())

Working directory: c:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook
Curated directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated
Parquet output: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated\property_month_kpis
Directory exists: True

In [191]:
# ============================================================
# PREPARE PROPERTY-MONTH PARQUET DATA
# ============================================================

# Verify required columns
required_columns = {
    "property_id",
    "month_end",
    "report_month"
}

missing_columns = (
    required_columns - set(property_month_kpis.columns)
)

if missing_columns:
    raise ValueError(
        f"Missing required columns: {sorted(missing_columns)}"
    )

# Create month partition column
df_parquet = property_month_kpis.withColumn(
    "month",
    F.col("report_month").cast("string")
)

# Validate missing, malformed, or inconsistent month values
invalid_months = df_parquet.filter(
    F.col("month").isNull()
    | F.col("month_end").isNull()
    | (~F.col("month").rlike(
        r"^[0-9]{4}-(0[1-9]|1[0-2])$"
    ))
    | (
        F.col("month") !=
        F.date_format(F.col("month_end"), "yyyy-MM")
    )
)

if invalid_months.limit(1).count() > 0:
    invalid_months.select(
        "property_id",
        "month_end",
        "report_month",
        "month"
    ).show(20, truncate=False)

    raise ValueError(
        "Invalid or inconsistent reporting months detected."
    )

print("Month partition column created successfully.")

df_parquet.select(
    "property_id",
    "month_end",
    "report_month",
    "month"
).show(10, truncate=False)

Month partition column created successfully.
+-----------+----------+------------+-------+
|property_id|month_end |report_month|month  |
+-----------+----------+------------+-------+
|P001       |2025-01-31|2025-01     |2025-01|
|P001       |2025-02-28|2025-02     |2025-02|
|P001       |2025-03-31|2025-03     |2025-03|
|P001       |2025-04-30|2025-04     |2025-04|
|P001       |2025-05-31|2025-05     |2025-05|
|P001       |2025-06-30|2025-06     |2025-06|
|P002       |2025-01-31|2025-01     |2025-01|
|P002       |2025-02-28|2025-02     |2025-02|
|P002       |2025-03-31|2025-03     |2025-03|
|P002       |2025-04-30|2025-04     |2025-04|
+-----------+----------+------------+-------+
only showing top 10 rows

In [192]:
print("Property-month uniqueness validation passed.")

Property-month uniqueness validation passed.

In [193]:
from pathlib import Path    
import pyarrow as pa
import pyarrow.parquet as pq

In [194]:

# ============================================================
# PROPTECH360 - FIX PROJECT DIRECTORY CONFIGURATION
# ============================================================

from pathlib import Path

# ------------------------------------------------------------
# 1. LOCATE PROJECT ROOT
# ------------------------------------------------------------

current_directory = Path.cwd().resolve()

print("Current working directory:", current_directory)

# Search the current folder and parent folders
# for the existing PropTech360 data directory.

PROJECT_ROOT = next(
    (
        folder
        for folder in [
            current_directory,
            *current_directory.parents
        ]
        if (
            (folder / "data" / "raw").is_dir()
            or
            (folder / "data" / "staging").is_dir()
        )
    ),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Cannot locate the PropTech360 project root. "
        "Open your project folder in VS Code and "
        "verify that data/raw or data/staging exists."
    )

# ------------------------------------------------------------
# 2. DEFINE PROJECT DIRECTORIES
# ------------------------------------------------------------

RAW_DIR = PROJECT_ROOT / "data" / "raw"

STAGING_DIR = PROJECT_ROOT / "data" / "staging"

CURATED_DIR = PROJECT_ROOT / "data" / "curated"

QUARANTINE_DIR = PROJECT_ROOT / "data" / "quarantine"

# ------------------------------------------------------------
# 3. CREATE OUTPUT DIRECTORIES
# ------------------------------------------------------------

CURATED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

QUARANTINE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 4. DEFINE PARQUET OUTPUT LOCATION
# ------------------------------------------------------------

PARQUET_OUTPUT = CURATED_DIR / "property_month_kpis"

# Generate a Windows-compatible local file URI
output_uri = PARQUET_OUTPUT.resolve().as_uri()

# ------------------------------------------------------------
# 5. VERIFY PROJECT CONFIGURATION
# ------------------------------------------------------------

print("=" * 60)
print("PROPTECH360 PROJECT CONFIGURATION")
print("=" * 60)

print("Project root:", PROJECT_ROOT)
print("Raw directory:", RAW_DIR)
print("Staging directory:", STAGING_DIR)
print("Curated directory:", CURATED_DIR)
print("Quarantine directory:", QUARANTINE_DIR)
print("Parquet output:", PARQUET_OUTPUT)
print("Parquet URI:", output_uri)

print("Curated directory exists:", CURATED_DIR.exists())

print("=" * 60)
print("SUCCESS: Project paths configured.")

Current working directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook
============================================================
PROPTECH360 PROJECT CONFIGURATION
============================================================
Project root: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook
Raw directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\raw
Staging directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\staging
Curated directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated
Quarantine directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\quarantine
Parquet output: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated\property_month_kpis
Parquet URI: file:///C:/Documents/Desktop/PropTech360_Capstone_data_pipeline/notebook/data/curated/property_month_kpis
Curated directory exists: True
============================================================
SUCCESS: Project paths configured.

In [195]:
# Check existing DataFrames

print("property_month_kpis exists:",
      "property_month_kpis" in globals())

print("df_parquet exists:",
      "df_parquet" in globals())

print("SparkSession exists:",
      "spark" in globals())

property_month_kpis exists: True
df_parquet exists: True
SparkSession exists: True

In [196]:

# ============================================================
# PROPTECH360 - FIX UNDEFINED df_parquet
# ============================================================

from pyspark.sql import functions as F
from pyspark.sql import DataFrame

# ------------------------------------------------------------
# 1. CHECK EXISTING DATAFRAME
# ------------------------------------------------------------

if "property_month_kpis" not in globals():
    raise NameError(
        "property_month_kpis is not defined. "
        "Rerun the earlier PySpark transformation cells."
    )

if not isinstance(property_month_kpis, DataFrame):
    raise TypeError(
        "property_month_kpis must be a PySpark DataFrame."
    )

# ------------------------------------------------------------
# 2. VALIDATE REQUIRED COLUMNS
# ------------------------------------------------------------

required_columns = {
    "property_id",
    "month_end"
}

missing_columns = (
    required_columns - set(property_month_kpis.columns)
)

if missing_columns:
    raise ValueError(
        f"Missing required columns: {sorted(missing_columns)}"
    )

# ------------------------------------------------------------
# 3. CREATE THE MONTH PARTITION COLUMN
# ------------------------------------------------------------

df_parquet = (
    property_month_kpis
    .withColumn(
        "month",
        F.date_format(
            F.to_date(F.col("month_end")),
            "yyyy-MM"
        )
    )
)

# ------------------------------------------------------------
# 4. VALIDATE THE RESULT
# ------------------------------------------------------------

if df_parquet.filter(
    F.col("month").isNull()
).limit(1).count() > 0:
    raise ValueError(
        "Some month_end values cannot be converted "
        "into valid month partitions."
    )

print("=" * 60)
print("df_parquet CREATED SUCCESSFULLY")
print("=" * 60)

print("Total rows:", df_parquet.count())
print("Columns:", df_parquet.columns)

# Preview selected columns
df_parquet.select(
    "property_id",
    "month_end",
    "month"
).show(10, truncate=False)

# Show reporting months
df_parquet.groupBy("month").count().orderBy(
    "month"
).show()

============================================================
df_parquet CREATED SUCCESSFULLY
============================================================
Total rows: 72
Columns: ['property_id', 'month_end', 'property_name', 'city', 'month_start', 'total_units', 'occupied_units', 'monthly_rent_usd', 'occupancy_rate', 'occupancy_pct', 'work_order_count', 'avg_response_hours', 'sla_met_count', 'sla_pct', 'total_energy_kwh', 'avg_reading_kwh', 'meter_reading_count', 'report_month', 'month']
+-----------+----------+-------+
|property_id|month_end |month  |
+-----------+----------+-------+
|P001       |2025-01-31|2025-01|
|P001       |2025-02-28|2025-02|
|P001       |2025-03-31|2025-03|
|P001       |2025-04-30|2025-04|
|P001       |2025-05-31|2025-05|
|P001       |2025-06-30|2025-06|
|P002       |2025-01-31|2025-01|
|P002       |2025-02-28|2025-02|
|P002       |2025-03-31|2025-03|
|P002       |2025-04-30|2025-04|
+-----------+----------+-------+
only showing top 10 rows
+-------+-----+
|  month|count|
+-------+-----+
|2025-01|   12|
|2025-02|   12|
|2025-03|   12|
|2025-04|   12|
|2025-05|   12|
|2025-06|   12|
+-------+-----+

In [197]:
PARQUET_OUTPUT = CURATED_DIR / "property_month_kpis"

PARQUET_OUTPUT.mkdir(
    parents=True,
    exist_ok=True
)

In [198]:

# ============================================================
# PROPTECH360 - WRITE PARQUET USING PYARROW
# ============================================================

# 1. IMPORT DEPENDENCIES

from pathlib import Path
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds

print("PyArrow version:", pa.__version__)

# ------------------------------------------------------------
# 2. REUSE EXISTING PROPTECH360 DATA
# ------------------------------------------------------------

if "final_kpi_pd" in globals():

    # Use existing pandas DataFrame
    final_kpi_pd = final_kpi_pd.copy()

elif "df_parquet" in globals():

    # Convert existing Spark DataFrame
    final_kpi_pd = df_parquet.toPandas()

elif "property_month_kpis" in globals():

    # Convert the final KPI Spark DataFrame
    final_kpi_pd = property_month_kpis.toPandas()

else:
    raise NameError(
        "No final KPI DataFrame was found. "
        "Rerun the notebook transformation cells "
        "that create property_month_kpis."
    )

if not isinstance(final_kpi_pd, pd.DataFrame):
    raise TypeError(
        "final_kpi_pd must be a pandas DataFrame."
    )

if final_kpi_pd.empty:
    raise ValueError(
        "The final KPI DataFrame is empty."
    )

if not final_kpi_pd.columns.is_unique:
    raise ValueError(
        "Duplicate column names detected."
    )

print("Final KPI DataFrame loaded.")
print("Rows:", len(final_kpi_pd))

# ------------------------------------------------------------
# 3. VALIDATE AND CREATE THE MONTH COLUMN
# ------------------------------------------------------------

if "property_id" not in final_kpi_pd.columns:
    raise ValueError(
        "Required column property_id is missing."
    )

if "month_end" in final_kpi_pd.columns:

    dates = pd.to_datetime(
        final_kpi_pd["month_end"],
        errors="coerce"
    )

    if dates.isna().any():
        raise ValueError(
            "Invalid or missing month_end values."
        )

    expected_month = dates.dt.strftime("%Y-%m")

    if "month" in final_kpi_pd.columns:

        current_month = (
            final_kpi_pd["month"].astype("string")
        )

        matches = (
            current_month.eq(expected_month)
            .fillna(False)
        )

        if not matches.all():
            raise ValueError(
                "Existing month values do not match month_end."
            )

    # Standardise the partition values
    final_kpi_pd["month"] = expected_month

elif "month" in final_kpi_pd.columns:

    final_kpi_pd["month"] = (
        final_kpi_pd["month"].astype("string")
    )

else:
    raise ValueError(
        "Neither month nor month_end exists."
    )

# Validate partition values
valid_month = (
    final_kpi_pd["month"]
    .str.fullmatch(r"\d{4}-(0[1-9]|1[0-2])")
    .fillna(False)
)

if not valid_month.all():
    raise ValueError(
        "Invalid month values detected."
    )

# ------------------------------------------------------------
# 4. DATA QUALITY CHECKS
# ------------------------------------------------------------

row_count = len(final_kpi_pd)

month_count = (
    final_kpi_pd["month"].nunique()
)

key_columns = ["property_id", "month"]

duplicate_count = (
    final_kpi_pd.duplicated(
        subset=key_columns
    ).sum()
)

if row_count != 72:
    raise ValueError(
        f"Expected 72 records, found {row_count}."
    )

if month_count != 6:
    raise ValueError(
        f"Expected 6 months, found {month_count}."
    )

if duplicate_count != 0:
    raise ValueError(
        f"Found {duplicate_count} duplicate property-month keys."
    )

print("PASS: KPI quality checks completed.")

# ------------------------------------------------------------
# 5. DEFINE OUTPUT DIRECTORY
# ------------------------------------------------------------

if "PARQUET_OUTPUT" in globals():

    output_path = Path(PARQUET_OUTPUT).resolve()

elif "CURATED_DIR" in globals():

    output_path = (
        Path(CURATED_DIR).resolve()
        / "property_month_kpis"
    )

else:
    raise NameError(
        "PARQUET_OUTPUT and CURATED_DIR are undefined. "
        "Run your project path configuration cell."
    )

if output_path.exists() and not output_path.is_dir():
    raise ValueError(
        f"Output path is not a directory: {output_path}"
    )

output_path.mkdir(parents=True, exist_ok=True)

PARQUET_OUTPUT = output_path

print("Parquet output:", PARQUET_OUTPUT)

# ------------------------------------------------------------
# 6. CONVERT PANDAS TO PYARROW TABLE
# ------------------------------------------------------------

table = pa.Table.from_pandas(
    final_kpi_pd,
    preserve_index=False
)

print("Arrow table created.")
print("Arrow rows:", table.num_rows)

# ------------------------------------------------------------
# 7. WRITE PARQUET PARTITIONED BY MONTH
# ------------------------------------------------------------

pq.write_to_dataset(
    table,
    root_path=str(PARQUET_OUTPUT),
    partition_cols=["month"],
    compression="snappy",
    existing_data_behavior="delete_matching"
)

print("Partitioned Parquet write completed.")

# ------------------------------------------------------------
# 8. READ BACK AND VALIDATE
# ------------------------------------------------------------

dataset = ds.dataset(
    str(PARQUET_OUTPUT),
    format="parquet",
    partitioning="hive"
)

written_pd = dataset.to_table().to_pandas()

if len(written_pd) != row_count:
    raise AssertionError(
        f"Expected {row_count} rows, "
        f"read {len(written_pd)}."
    )

if written_pd["month"].nunique() != month_count:
    raise AssertionError(
        "Written dataset has an unexpected month count."
    )

if written_pd.duplicated(
    subset=["property_id", "month"]
).any():
    raise AssertionError(
        "Duplicate property-month records in Parquet."
    )

# ------------------------------------------------------------
# 9. DISPLAY RESULTS
# ------------------------------------------------------------

print("=" * 60)
print("PROPTECH360 PARQUET VALIDATION SUCCESSFUL")
print("=" * 60)

print("Output:", PARQUET_OUTPUT)
print("Format: Parquet")
print("Compression: Snappy")
print("Partition column: month")
print("Partition replacement: delete_matching")
print("Records:", len(written_pd))
print("Months:", written_pd["month"].nunique())

print("\nRecords per month:")

print(
    written_pd.groupby("month", dropna=False)
    .size()
    .sort_index()
)

print("\nPhysical month folders:")

for folder in sorted(PARQUET_OUTPUT.glob("month=*")):
    print(folder.name)

PyArrow version: 26.0.0

c:\Documents\Desktop\PropTech360_Capstone_project\venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

Final KPI DataFrame loaded.
Rows: 72
PASS: KPI quality checks completed.
Parquet output: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated\property_month_kpis
Arrow table created.
Arrow rows: 72
Partitioned Parquet write completed.
============================================================
PROPTECH360 PARQUET VALIDATION SUCCESSFUL
============================================================
Output: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\notebook\data\curated\property_month_kpis
Format: Parquet
Compression: Snappy
Partition column: month
Partition replacement: delete_matching
Records: 72
Months: 6

Records per month:
month
2025-01    12
2025-02    12
2025-03    12
2025-04    12
2025-05    12
2025-06    12
dtype: int64

Physical month folders:
month=2025-01
month=2025-02
month=2025-03
month=2025-04
month=2025-05
month=2025-06

In [199]:
for path in sorted(PARQUET_OUTPUT.iterdir()):
    print(path.name)

month=2025-01
month=2025-02
month=2025-03
month=2025-04
month=2025-05
month=2025-06

In [200]:
table = pa.Table.from_pandas(
    final_kpi_pd,
    preserve_index=False
)

pq.write_to_dataset(
    table,
    root_path=str(PARQUET_OUTPUT),
    partition_cols=["month"]
)

print("Partitioned Parquet written successfully.")

Partitioned Parquet written successfully.

In [201]:
# Validate expected number of records
row_count = df_parquet.count()

assert row_count == 72, (
    f"Expected 72 records, found {row_count}"
)

# Validate unique property-month combinations
unique_count = (
    df_parquet
    .select("property_id", "month_end")
    .distinct()
    .count()
)

assert unique_count == 72, (
    f"Expected 72 unique property-month keys, "
    f"found {unique_count}"
)

# Validate number of monthly partitions
month_count = (
    df_parquet
    .select("month")
    .distinct()
    .count()
)

assert month_count == 6, (
    f"Expected 6 months, found {month_count}"
)

print("PASS: All DataFrame validations successful.")

PASS: All DataFrame validations successful.

In [202]:
# Check the prepared PySpark DataFrame

print("DataFrame type:", type(df_parquet))

print("Columns:", df_parquet.columns)

print("Total records:", df_parquet.count())

df_parquet.select(
    "property_id",
    "month_end",
    "month"
).show(10, truncate=False)

DataFrame type: <class 'pyspark.sql.classic.dataframe.DataFrame'>
Columns: ['property_id', 'month_end', 'property_name', 'city', 'month_start', 'total_units', 'occupied_units', 'monthly_rent_usd', 'occupancy_rate', 'occupancy_pct', 'work_order_count', 'avg_response_hours', 'sla_met_count', 'sla_pct', 'total_energy_kwh', 'avg_reading_kwh', 'meter_reading_count', 'report_month', 'month']
Total records: 72
+-----------+----------+-------+
|property_id|month_end |month  |
+-----------+----------+-------+
|P001       |2025-01-31|2025-01|
|P001       |2025-02-28|2025-02|
|P001       |2025-03-31|2025-03|
|P001       |2025-04-30|2025-04|
|P001       |2025-05-31|2025-05|
|P001       |2025-06-30|2025-06|
|P002       |2025-01-31|2025-01|
|P002       |2025-02-28|2025-02|
|P002       |2025-03-31|2025-03|
|P002       |2025-04-30|2025-04|
+-----------+----------+-------+
only showing top 10 rows

In [203]:
REPORT_START = "2026-01-01"
REPORT_END = "2026-06-30"

In [204]:
from pathlib import Path

# Project root
PROJECT_ROOT = Path(
    r"C:\Documents\Desktop\PropTech360_Capstone_data_pipeline"
)

# SQL directory
SQL_DIR = PROJECT_ROOT / "sql"

# IMPORTANT: create the folder first
SQL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# File path
schema_path = SQL_DIR / "01_schema.sql"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SQL_DIR:", SQL_DIR)
print("SQL_DIR exists:", SQL_DIR.exists())
print("Schema path:", schema_path)

PROJECT_ROOT: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline
SQL_DIR: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql
SQL_DIR exists: True
Schema path: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql\01_schema.sql

In [208]:
schema_path.write_text(
    schema_sql.strip() + "\n",
    encoding="utf-8"
)

print("Created:", schema_path)

Created: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql\01_schema.sql

In [206]:
schema_sql = """
-- =========================================================
-- PropTech360
-- PostgreSQL dimensional schema
-- =========================================================

CREATE TABLE IF NOT EXISTS dim_property (
    property_id VARCHAR(20) PRIMARY KEY,
    property_name VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_month (
    month_date DATE PRIMARY KEY,

    year_number INTEGER NOT NULL
        CHECK (year_number >= 2000),

    month_number INTEGER NOT NULL
        CHECK (month_number BETWEEN 1 AND 12),

    month_name VARCHAR(20) NOT NULL,

    quarter_number INTEGER NOT NULL
        CHECK (quarter_number BETWEEN 1 AND 4)
);

CREATE TABLE IF NOT EXISTS fact_property_month (

    property_id VARCHAR(20) NOT NULL,

    month_date DATE NOT NULL,

    total_units INTEGER NOT NULL
        CHECK (total_units >= 0),

    occupied_units INTEGER NOT NULL
        CHECK (occupied_units >= 0),

    occupancy_rate NUMERIC(10,6)
        CHECK (
            occupancy_rate IS NULL
            OR occupancy_rate BETWEEN 0 AND 1
        ),

    earned_monthly_rent_usd NUMERIC(14,2) NOT NULL
        CHECK (earned_monthly_rent_usd >= 0),

    resolved_orders INTEGER NOT NULL
        CHECK (resolved_orders >= 0),

    sla_eligible_orders INTEGER NOT NULL
        CHECK (sla_eligible_orders >= 0),

    sla_compliant_orders INTEGER NOT NULL
        CHECK (sla_compliant_orders >= 0),

    open_orders INTEGER NOT NULL
        CHECK (open_orders >= 0),

    sla_missing_response_orders INTEGER NOT NULL DEFAULT 0
        CHECK (sla_missing_response_orders >= 0),

    sla_compliance_rate NUMERIC(10,6)
        CHECK (
            sla_compliance_rate IS NULL
            OR sla_compliance_rate BETWEEN 0 AND 1
        ),

    energy_kwh NUMERIC(16,2) NOT NULL
        CHECK (energy_kwh >= 0),

    floor_area_sqm NUMERIC(16,2) NOT NULL
        CHECK (floor_area_sqm > 0),

    energy_intensity_kwh_sqm NUMERIC(16,6)
        CHECK (
            energy_intensity_kwh_sqm IS NULL
            OR energy_intensity_kwh_sqm >= 0
        ),

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_fact_property_month
        PRIMARY KEY (
            property_id,
            month_date
        ),

    CONSTRAINT fk_fact_property
        FOREIGN KEY (property_id)
        REFERENCES dim_property(property_id),

    CONSTRAINT fk_fact_month
        FOREIGN KEY (month_date)
        REFERENCES dim_month(month_date),

    CONSTRAINT chk_occupied_not_above_total
        CHECK (
            occupied_units <= total_units
        ),

    CONSTRAINT chk_sla_not_above_eligible
        CHECK (
            sla_compliant_orders
            <= sla_eligible_orders
        )
);

CREATE INDEX IF NOT EXISTS idx_property_city
ON dim_property(city);

CREATE INDEX IF NOT EXISTS idx_fact_month
ON fact_property_month(month_date);

CREATE INDEX IF NOT EXISTS idx_fact_occupancy
ON fact_property_month(occupancy_rate);

CREATE INDEX IF NOT EXISTS idx_fact_energy_intensity
ON fact_property_month(
    energy_intensity_kwh_sqm
);
"""

schema_path = SQL_DIR / "01_schema.sql"

schema_path.write_text(
    schema_sql.strip() + "\n",
    encoding="utf-8"
)

print("Created:", schema_path)

Created: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql\01_schema.sql

In [211]:
from pathlib import Path

# Project root
PROJECT_ROOT = Path(
    r"C:\Documents\Desktop\PropTech360_Capstone_data_pipeline"
)

# SQL folder
SQL_DIR = PROJECT_ROOT / "sql"

# Make sure SQL directory exists
SQL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ---------------------------------------------------------
# Define the SQL content FIRST
# ---------------------------------------------------------

load_sql = """
-- =========================================================
-- PropTech360
-- Topic 4 - Load / Idempotency Validation
-- =========================================================

-- The actual parameterized PostgreSQL loading is performed
-- in src/load_postgres.py using SQLAlchemy + psycopg.
--
-- The fact table grain is:
-- one row per (property_id, month_date)
--
-- The loader uses:
--
-- INSERT ...
-- ON CONFLICT (property_id, month_date)
-- DO UPDATE ...
--
-- This makes repeated pipeline runs idempotent.


-- ---------------------------------------------------------
-- 1. Check total rows
-- ---------------------------------------------------------

SELECT
    COUNT(*) AS total_fact_rows
FROM fact_property_month;


-- ---------------------------------------------------------
-- 2. Verify property-month uniqueness
-- ---------------------------------------------------------

SELECT
    COUNT(*) AS total_rows,

    COUNT(
        DISTINCT (
            property_id,
            month_date
        )
    ) AS unique_property_months

FROM fact_property_month;


-- ---------------------------------------------------------
-- 3. Detect duplicate property-month records
-- Expected result: zero rows
-- ---------------------------------------------------------

SELECT
    property_id,
    month_date,
    COUNT(*) AS duplicate_count

FROM fact_property_month

GROUP BY
    property_id,
    month_date

HAVING COUNT(*) > 1;


-- ---------------------------------------------------------
-- 4. Expected PropTech360 fact count
-- 12 properties x 6 months = 72
-- ---------------------------------------------------------

SELECT
    CASE
        WHEN COUNT(*) = 72
        THEN 'PASS'
        ELSE 'FAIL'
    END AS fact_row_count_test,

    COUNT(*) AS actual_fact_rows

FROM fact_property_month;
"""

# ---------------------------------------------------------
# Create target file path
# ---------------------------------------------------------

load_path = SQL_DIR / "02_load.sql"

# ---------------------------------------------------------
# Save file
# ---------------------------------------------------------

load_path.write_text(
    load_sql.strip() + "\n",
    encoding="utf-8"
)

print("Created:", load_path)
print("File exists:", load_path.exists())

Created: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql\02_load.sql
File exists: True

In [212]:
from pathlib import Path

# 1. Define the project root directory
PROJECT_ROOT = Path(
    r"C:\Documents\Desktop\PropTech360_Capstone_data_pipeline"
)

# 2. Define the SQL directory
SQL_DIR = PROJECT_ROOT / "sql"

# 3. Create the SQL directory if it does not exist
SQL_DIR.mkdir(parents=True, exist_ok=True)

# 4. Define the SQL file path
load_path = SQL_DIR / "02_load.sql"

# 5. Save the SQL script
load_path.write_text(
    load_sql.strip() + "\n",
    encoding="utf-8"
)

# 6. Confirm the file was created
print("SQL file saved successfully!")
print("File location:", load_path)
print("File exists:", load_path.exists())

SQL file saved successfully!
File location: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql\02_load.sql
File exists: True

In [213]:
from pathlib import Path

# Start from the current working directory
current_dir = Path.cwd().resolve()

# Locate the project root
project_name = "PropTech360_Capstone_data_pipeline"

matches = [
    path for path in (current_dir, *current_dir.parents)
    if path.name == project_name
]

if not matches:
    raise FileNotFoundError(
        f"Cannot locate project root: {project_name}"
    )

PROJECT_ROOT = matches[0]

# Create SQL directory
SQL_DIR = PROJECT_ROOT / "sql"
SQL_DIR.mkdir(parents=True, exist_ok=True)

# Save SQL file
load_path = SQL_DIR / "02_load.sql"

load_path.write_text(
    load_sql.strip() + "\n",
    encoding="utf-8"
)

print("Project root:", PROJECT_ROOT)
print("SQL directory:", SQL_DIR)
print("SQL file created:", load_path.exists())

Project root: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline
SQL directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql
SQL file created: True

In [214]:
for filename in ["01_schema.sql", "02_load.sql"]:

    file_path = SQL_DIR / filename

    print(
        f"{filename}:",
        "EXISTS" if file_path.exists() else "MISSING"
    )

01_schema.sql: EXISTS
02_load.sql: EXISTS

In [215]:
analytics_sql = """
-- =========================================================
-- PropTech360
-- Required analytical queries
-- =========================================================


-- =========================================================
-- 1. Property occupancy ranking
-- January-June 2026
-- =========================================================

SELECT
    f.property_id,
    p.property_name,
    p.city,

    SUM(f.occupied_units)
        AS occupied_unit_months,

    SUM(f.total_units)
        AS total_unit_months,

    ROUND(
        AVG(f.occupancy_rate),
        4
    ) AS average_monthly_occupancy_rate,

    RANK() OVER (
        ORDER BY AVG(f.occupancy_rate) DESC
    ) AS occupancy_rank

FROM fact_property_month f

JOIN dim_property p
    ON f.property_id = p.property_id

WHERE f.month_date
    BETWEEN DATE '2026-01-01'
    AND DATE '2026-06-30'

GROUP BY
    f.property_id,
    p.property_name,
    p.city

ORDER BY occupancy_rank;



-- =========================================================
-- 2. Monthly earned contractual rent by city
-- =========================================================

SELECT
    f.month_date,
    p.city,

    ROUND(
        SUM(f.earned_monthly_rent_usd),
        2
    ) AS earned_contractual_rent_usd

FROM fact_property_month f

JOIN dim_property p
    ON f.property_id = p.property_id

GROUP BY
    f.month_date,
    p.city

ORDER BY
    f.month_date,
    p.city;



-- =========================================================
-- 3. Maintenance SLA compliance by property
-- =========================================================

SELECT
    f.property_id,
    p.property_name,

    SUM(f.resolved_orders)
        AS resolved_orders,

    SUM(f.sla_eligible_orders)
        AS sla_eligible_resolved_orders,

    SUM(f.sla_compliant_orders)
        AS sla_compliant_orders,

    SUM(f.open_orders)
        AS excluded_unresolved_orders,

    SUM(f.sla_missing_response_orders)
        AS excluded_missing_response_orders,

    ROUND(
        SUM(f.sla_compliant_orders)::NUMERIC
        /
        NULLIF(
            SUM(f.sla_eligible_orders),
            0
        ),
        4
    ) AS sla_compliance_rate

FROM fact_property_month f

JOIN dim_property p
    ON f.property_id = p.property_id

GROUP BY
    f.property_id,
    p.property_name

ORDER BY
    sla_compliance_rate DESC NULLS LAST;



-- =========================================================
-- 4. Property-months above monthly portfolio
-- energy intensity
-- =========================================================

WITH portfolio_month AS (

    SELECT
        month_date,

        SUM(energy_kwh)
        /
        NULLIF(
            SUM(floor_area_sqm),
            0
        ) AS portfolio_energy_intensity

    FROM fact_property_month

    GROUP BY month_date
)

SELECT
    f.month_date,
    f.property_id,
    p.property_name,

    ROUND(
        f.energy_intensity_kwh_sqm,
        4
    ) AS property_energy_intensity,

    ROUND(
        pm.portfolio_energy_intensity,
        4
    ) AS portfolio_energy_intensity,

    ROUND(
        f.energy_kwh,
        2
    ) AS total_energy_kwh

FROM fact_property_month f

JOIN portfolio_month pm
    ON f.month_date = pm.month_date

JOIN dim_property p
    ON f.property_id = p.property_id

WHERE
    f.energy_intensity_kwh_sqm
    > pm.portfolio_energy_intensity

ORDER BY
    f.month_date,
    f.energy_intensity_kwh_sqm DESC;



-- =========================================================
-- 5. Portfolio dashboard view
-- =========================================================

CREATE OR REPLACE VIEW
vw_portfolio_dashboard AS

SELECT
    f.month_date,

    f.property_id,

    p.property_name,

    p.city,

    f.total_units,

    f.occupied_units,

    f.occupancy_rate,

    f.earned_monthly_rent_usd,

    f.resolved_orders,

    f.sla_eligible_orders,

    f.sla_compliant_orders,

    f.open_orders,

    f.sla_missing_response_orders,

    f.sla_compliance_rate,

    f.energy_kwh,

    f.floor_area_sqm,

    f.energy_intensity_kwh_sqm

FROM fact_property_month f

JOIN dim_property p
    ON f.property_id = p.property_id;


SELECT *
FROM vw_portfolio_dashboard
ORDER BY
    month_date,
    property_id;
"""

analytics_path = SQL_DIR / "03_analytics.sql"

analytics_path.write_text(
    analytics_sql.strip() + "\n",
    encoding="utf-8"
)

print("Created:", analytics_path)

Created: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql\03_analytics.sql

In [216]:
required_sql_files = [
    SQL_DIR / "01_schema.sql",
    SQL_DIR / "02_load.sql",
    SQL_DIR / "03_analytics.sql"
]

for path in required_sql_files:

    print(
        path.name,
        "->",
        "FOUND" if path.exists() else "MISSING"
    )

01_schema.sql -> FOUND
02_load.sql -> FOUND
03_analytics.sql -> FOUND

In [217]:
from pathlib import Path
from dotenv import load_dotenv

PROJECT_ROOT = Path.cwd().resolve().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"

UNITS_PATH = RAW_DIR / "units.csv"

WORK_ORDERS_PATH = (
    RAW_DIR / "work_orders.csv"
)

SQL_DIR = PROJECT_ROOT / "sql"

EVIDENCE_DIR = (
    PROJECT_ROOT
    / "evidence"
    / "topic4"
)

required_paths = [
    UNITS_PATH,
    WORK_ORDERS_PATH,
    SQL_DIR / "01_schema.sql",
    SQL_DIR / "02_load.sql",
    SQL_DIR / "03_analytics.sql"
]


missing = [
    path
    for path in required_paths
    if not path.exists()
]


if missing:

    missing_text = "\n".join(
        f" - {path}"
        for path in missing
    )

    raise FileNotFoundError(
        "The following prerequisites "
        "are missing:\n"
        + missing_text
    )


EVIDENCE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


load_dotenv(
    PROJECT_ROOT / ".env",
    override=False
)


print("All prerequisites found.")

print(
    "Project root:",
    PROJECT_ROOT
)

print(
    "SQL directory:",
    SQL_DIR
)

print(
    "Evidence directory:",
    EVIDENCE_DIR
)

All prerequisites found.
Project root: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline
SQL directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql
Evidence directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\evidence\topic4

In [218]:
from pathlib import Path
from dotenv import load_dotenv

# --------------------------------------------------
# 1. DEFINE PROJECT ROOT
# --------------------------------------------------

PROJECT_ROOT = Path(
    r"C:\Documents\Desktop\PropTech360_Capstone_data_pipeline"
).resolve()

# --------------------------------------------------
# 2. DEFINE PROJECT DIRECTORIES
# --------------------------------------------------

RAW_DIR = PROJECT_ROOT / "data" / "raw"

SQL_DIR = PROJECT_ROOT / "sql"

EVIDENCE_DIR = PROJECT_ROOT / "evidence" / "topic4"

# --------------------------------------------------
# 3. DEFINE SOURCE DATASET PATHS
# --------------------------------------------------

UNITS_PATH = RAW_DIR / "units.csv"

WORK_ORDERS_PATH = RAW_DIR / "work_orders.csv"

# --------------------------------------------------
# 4. CREATE OUTPUT DIRECTORIES
# --------------------------------------------------

SQL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

EVIDENCE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 5. VALIDATE REQUIRED FILES
# --------------------------------------------------

required_files = [
    UNITS_PATH,
    WORK_ORDERS_PATH,
    SQL_DIR / "01_schema.sql",
    SQL_DIR / "02_load.sql",
    SQL_DIR / "03_analytics.sql"
]

missing_files = [
    p for p in required_files
    if not p.is_file()
]

if missing_files:

    print("Missing prerequisite files:")

    for p in missing_files:
        print(" -", p)

    raise FileNotFoundError(
        "One or more required project files are missing."
    )

# --------------------------------------------------
# 6. LOAD ENVIRONMENT VARIABLES
# --------------------------------------------------

load_dotenv(
    PROJECT_ROOT / ".env",
    override=False
)

# --------------------------------------------------
# 7. CONFIRM CONFIGURATION
# --------------------------------------------------

print("Project root:", PROJECT_ROOT)

print("Raw directory:", RAW_DIR)

print("SQL directory:", SQL_DIR)

print("Evidence directory:", EVIDENCE_DIR)

print("All prerequisite files exist!")

Project root: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline
Raw directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\data\raw
SQL directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql
Evidence directory: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\evidence\topic4
All prerequisite files exist!

In [219]:
print("Project root exists:", PROJECT_ROOT.exists())

print("Raw folder exists:", RAW_DIR.exists())

print("\nAvailable raw files:")

if RAW_DIR.exists():

    for file in sorted(RAW_DIR.glob("*.csv")):
        print(file.name)

else:
    print("Raw data directory not found.")

Project root exists: True
Raw folder exists: True

Available raw files:
leases.csv
meter_readings.csv
properties.csv
units.csv
work_orders.csv

In [220]:
sql_files = [
    "01_schema.sql",
    "02_load.sql",
    "03_analytics.sql"
]

for filename in sql_files:

    path = SQL_DIR / filename

    print(
        filename,
        "EXISTS" if path.is_file() else "MISSING"
    )

01_schema.sql EXISTS
02_load.sql EXISTS
03_analytics.sql EXISTS

In [221]:
PROJECT_ROOT = Path(
    r"C:\Documents\Desktop\PropTech360_Capstone_data_pipeline"
)

RAW_DIR = PROJECT_ROOT / "data" / "raw"

UNITS_PATH = RAW_DIR / "units.csv"

WORK_ORDERS_PATH = RAW_DIR / "work_orders.csv"

In [223]:
import os

In [225]:
import os
from pathlib import Path

from dotenv import load_dotenv

# Adjust this if your notebook is inside a notebook/ folder
PROJECT_ROOT = Path.cwd().resolve().parent

# Load variables from .env
load_dotenv(
    PROJECT_ROOT / ".env",
    override=False
)

# Read connection strings
PG_ADMIN_URL = os.getenv("PG_ADMIN_URL")
DATABASE_URL = os.getenv("DATABASE_URL")

if not PG_ADMIN_URL and not DATABASE_URL:
    raise RuntimeError(
        "Neither PG_ADMIN_URL nor DATABASE_URL is configured in the .env file."
    )

print(
    "PG_ADMIN_URL configured:",
    bool(PG_ADMIN_URL)
)

print(
    "DATABASE_URL configured:",
    bool(DATABASE_URL)
)

PG_ADMIN_URL configured: True
DATABASE_URL configured: True

In [226]:
import os

from pathlib import Path
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

# --------------------------------------------------
# 1. SET PROJECT ROOT
# --------------------------------------------------

PROJECT_ROOT = Path(
    r"C:\Documents\Desktop\PropTech360_Capstone_data_pipeline"
).resolve()

# --------------------------------------------------
# 2. LOCATE .ENV FILE
# --------------------------------------------------

ENV_PATH = PROJECT_ROOT / ".env"

if not ENV_PATH.is_file():
    raise FileNotFoundError(
        f".env file not found at: {ENV_PATH}"
    )

# --------------------------------------------------
# 3. LOAD ENVIRONMENT VARIABLES
# --------------------------------------------------

load_dotenv(
    dotenv_path=ENV_PATH,
    override=True
)

# --------------------------------------------------
# 4. READ DATABASE CREDENTIALS
# --------------------------------------------------

PG_ADMIN_URL = os.getenv("PG_ADMIN_URL")

DATABASE_URL = os.getenv("DATABASE_URL")

# --------------------------------------------------
# 5. VALIDATE CONFIGURATION
# --------------------------------------------------

if not PG_ADMIN_URL and not DATABASE_URL:
    raise RuntimeError(
        "Set PG_ADMIN_URL or DATABASE_URL "
        "in your project-root .env file."
    )

print("Environment configuration loaded!")

print(
    "PG_ADMIN_URL configured:",
    bool(PG_ADMIN_URL)
)

print(
    "DATABASE_URL configured:",
    bool(DATABASE_URL)
)

# --------------------------------------------------
# 6. TEST EXISTING PROJECT DATABASE
# --------------------------------------------------

if DATABASE_URL:

    engine = create_engine(
        DATABASE_URL,
        pool_pre_ping=True
    )

    try:
        with engine.connect() as connection:

            database_name = connection.execute(
                text("SELECT current_database();")
            ).scalar()

            print(
                "Successfully connected to:",
                database_name
            )

    except Exception as error:

        print(
            "Database connection failed:",
            error
        )

        raise

Environment configuration loaded!
PG_ADMIN_URL configured: True
DATABASE_URL configured: True
Successfully connected to: proptech360

In [227]:
from sqlalchemy import create_engine, text

# Connect to administrative PostgreSQL database
admin_engine = create_engine(
    PG_ADMIN_URL,
    isolation_level="AUTOCOMMIT"
)

with admin_engine.connect() as conn:

    result = conn.execute(
        text(
            "SELECT 1 FROM pg_database "
            "WHERE datname = 'proptech360'"
        )
    ).scalar()

    if result is None:

        conn.execute(
            text("CREATE DATABASE proptech360")
        )

        print(
            "Database proptech360 created successfully!"
        )

    else:

        print(
            "Database proptech360 already exists."
        )

admin_engine.dispose()

Database proptech360 already exists.

In [228]:
print("Project root:", PROJECT_ROOT)

print(".env exists:", ENV_PATH.exists())

print("PG_ADMIN_URL loaded:", bool(os.getenv("PG_ADMIN_URL")))

print("DATABASE_URL loaded:", bool(os.getenv("DATABASE_URL")))

Project root: C:\Documents\Desktop\PropTech360_Capstone_data_pipeline
.env exists: True
PG_ADMIN_URL loaded: True
DATABASE_URL loaded: True

In [230]:
# Search the project for the schema file
matches = list(
    PROJECT_ROOT.rglob("01_schema.sql")
)

if matches:
    print("Schema files found:")

    for file in matches:
        print(file)

else:
    print("01_schema.sql was not found.")

Schema files found:
C:\Documents\Desktop\PropTech360_Capstone_data_pipeline\sql\01_schema.sql

In [232]:
from sqlalchemy import text

# --------------------------------------------------
# 1. READ SCHEMA SQL FILE
# --------------------------------------------------

schema_path = SQL_DIR / "01_schema.sql"

if not schema_path.is_file():
    raise FileNotFoundError(
        f"Schema file missing: {schema_path}"
    )

schema_sql = schema_path.read_text(
    encoding="utf-8"
)

# --------------------------------------------------
# 2. EXECUTE POSTGRESQL SCHEMA
# --------------------------------------------------

with engine.begin() as conn:

    # Suitable for your original simple SQL script
    # without semicolons inside strings or SQL blocks.
    statements = [
        statement.strip()
        for statement in schema_sql.split(";")
        if statement.strip()
    ]

    for statement in statements:
        conn.execute(text(statement))

print("PostgreSQL schema executed successfully!")

PostgreSQL schema executed successfully!

In [233]:
from sqlalchemy import inspect

inspector = inspect(engine)

required_tables = [
    "dim_property",
    "dim_month",
    "fact_property_month"
]

existing_tables = inspector.get_table_names()

for table in required_tables:

    if table in existing_tables:
        print(f"{table}: EXISTS")
    else:
        print(f"{table}: MISSING")

dim_property: EXISTS
dim_month: EXISTS
fact_property_month: EXISTS

In [234]:
from pathlib import Path

PROJECT_ROOT = Path(
    r"C:\Documents\Desktop\PropTech360_Capstone_data_pipeline"
).resolve()

RAW_DIR = PROJECT_ROOT / "data" / "raw"
CURATED_DIR = PROJECT_ROOT / "data" / "curated"
SQL_DIR = PROJECT_ROOT / "sql"
EVIDENCE_DIR = PROJECT_ROOT / "evidence" / "topic4"

SQL_DIR.mkdir(parents=True, exist_ok=True)
EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)

print("Project configuration initialised.")

Project configuration initialised.

In [235]:
# --------------------------------------------------
# PROPTECH360 REPORTING PERIOD
# --------------------------------------------------

REPORT_START = "2026-01-01"
REPORT_END = "2026-06-30"

print("Reporting period starts:", REPORT_START)
print("Reporting period ends:", REPORT_END)

Reporting period starts: 2026-01-01
Reporting period ends: 2026-06-30

In [236]:
from pyspark.sql import functions as F

# --------------------------------------------------
# GENERATE JANUARY–JUNE 2026 CALENDAR
# --------------------------------------------------

REPORT_START = "2026-01-01"
REPORT_END = "2026-06-30"

calendar = (
    spark.range(1)
    .select(
        F.explode(
            F.sequence(
                F.to_date(F.lit(REPORT_START)),
                F.to_date(F.lit(REPORT_END)),
                F.expr("INTERVAL 1 MONTH")
            )
        ).alias("month_start")
    )
    .withColumn(
        "month_end",
        F.last_day("month_start")
    )
    .withColumn(
        "report_month",
        F.date_format("month_start", "yyyy-MM")
    )
)

calendar.select(
    "month_start",
    "month_end",
    "report_month"
).show(truncate=False)

+-----------+----------+------------+
|month_start|month_end |report_month|
+-----------+----------+------------+
|2026-01-01 |2026-01-31|2026-01     |
|2026-02-01 |2026-02-28|2026-02     |
|2026-03-01 |2026-03-31|2026-03     |
|2026-04-01 |2026-04-30|2026-04     |
|2026-05-01 |2026-05-31|2026-05     |
|2026-06-01 |2026-06-30|2026-06     |
+-----------+----------+------------+

In [243]:
assert calendar.count() == 6

actual_calendar_months = {
    row["report_month"]
    for row in calendar.select(
        "report_month"
    ).distinct().collect()
}

expected_months = {
    "2026-01",
    "2026-02",
    "2026-03",
    "2026-04",
    "2026-05",
    "2026-06"
}

assert actual_calendar_months == expected_months

print("PASS: Calendar is Jan-Jun 2026.")

PASS: Calendar is Jan-Jun 2026.

In [244]:
REPORT_START
REPORT_END

'2026-06-30'

In [245]:
property_month_kpis.select(
    "month_end"
).distinct().orderBy(
    "month_end"
).show()

+----------+
| month_end|
+----------+
|2025-01-31|
|2025-02-28|
|2025-03-31|
|2025-04-30|
|2025-05-31|
|2025-06-30|
+----------+

In [246]:
print(
    "Total rows:",
    property_month_kpis.count()
)

Total rows: 72

In [247]:
unique_count = (
    property_month_kpis
    .select(
        "property_id",
        "month_end"
    )
    .distinct()
    .count()
)

print(
    "Unique property-month rows:",
    unique_count
)

assert unique_count == 72

Unique property-month rows: 72

In [258]:
from pyspark.sql import functions as F

REPORT_START = "2026-01-01"
REPORT_END = "2026-06-30"

calendar = (
    spark.range(1)
    .select(
        F.explode(
            F.sequence(
                F.to_date(F.lit(REPORT_START)),
                F.to_date(F.lit(REPORT_END)),
                F.expr("INTERVAL 1 MONTH")
            )
        ).alias("month_start")
    )
    .withColumn(
        "month_end",
        F.last_day("month_start")
    )
    .withColumn(
        "report_month",
        F.date_format(
            "month_start",
            "yyyy-MM"
        )
    )
)

calendar.orderBy("month_start").show(
    truncate=False
)

+-----------+----------+------------+
|month_start|month_end |report_month|
+-----------+----------+------------+
|2026-01-01 |2026-01-31|2026-01     |
|2026-02-01 |2026-02-28|2026-02     |
|2026-03-01 |2026-03-31|2026-03     |
|2026-04-01 |2026-04-30|2026-04     |
|2026-05-01 |2026-05-31|2026-05     |
|2026-06-01 |2026-06-30|2026-06     |
+-----------+----------+------------+

In [259]:
property_months = (
    properties
    .select(
        "property_id",
        "property_name",
        "city"
    )
    .distinct()
    .crossJoin(calendar)
)

In [260]:
property_months.select(
    "month_end"
).distinct().orderBy(
    "month_end"
).show()

+----------+
| month_end|
+----------+
|2026-01-31|
|2026-02-28|
|2026-03-31|
|2026-04-30|
|2026-05-31|
|2026-06-30|
+----------+

In [261]:
unit_month_leases = (
    unit_months.alias("um")
    .join(
        leases.alias("l"),
        (
            F.col("um.unit_id")
            ==
            F.col("l.unit_id")
        )
        &
        (
            F.col("l.start_date")
            <=
            F.col("um.month_end")
        )
        &
        (
            F.col("l.end_date").isNull()
            |
            (
                F.col("l.end_date")
                >=
                F.col("um.month_end")
            )
        ),
        "left"
    )
)

In [262]:
from pyspark.sql import Window

lease_window = (
    Window
    .partitionBy(
        F.col("um.unit_id"),
        F.col("um.month_end")
    )
    .orderBy(
        F.col("l.start_date").desc(),
        F.col("l.lease_id").desc()
    )
)

unit_month_snapshot = (
    unit_month_leases
    .withColumn(
        "lease_rank",
        F.row_number().over(
            lease_window
        )
    )
    .filter(
        F.col("lease_rank") == 1
    )
    .select(
        F.col("um.unit_id").alias("unit_id"),
        F.col("um.property_id").alias("property_id"),
        F.col("um.month_start").alias("month_start"),
        F.col("um.month_end").alias("month_end"),
        F.col("l.lease_id").alias("lease_id"),
        F.col(
            "l.monthly_rent_usd"
        ).alias("monthly_rent_usd")
    )
    .withColumn(
        "occupied_flag",
        F.when(
            F.col("lease_id").isNotNull(),
            1
        ).otherwise(0)
    )
)

In [263]:
occupancy_rent = (
    unit_month_snapshot
    .groupBy(
        "property_id",
        "month_end"
    )
    .agg(
        F.countDistinct(
            "unit_id"
        ).alias("total_units"),

        F.sum(
            "occupied_flag"
        ).alias("occupied_units"),

        F.sum(
            F.when(
                F.col("occupied_flag") == 1,
                F.col("monthly_rent_usd")
            ).otherwise(0.0)
        ).alias("monthly_rent_usd")
    )
    .withColumn(
        "occupancy_rate",
        F.when(
            F.col("total_units") > 0,
            F.col("occupied_units")
            /
            F.col("total_units")
        )
    )
    .withColumn(
        "occupancy_pct",
        F.round(
            F.col("occupancy_rate") * 100,
            2
        )
    )
)

In [264]:
property_month_kpis = (
    property_months
    .select(
        "property_id",
        "property_name",
        "city",
        "month_start",
        "month_end",
        "report_month"
    )
)

In [265]:
property_month_kpis = (
    property_month_kpis
    .join(
        occupancy_rent,
        on=[
            "property_id",
            "month_end"
        ],
        how="left"
    )
    .join(
        sla_metrics,
        on=[
            "property_id",
            "month_end"
        ],
        how="left"
    )
    .join(
        energy_metrics,
        on=[
            "property_id",
            "month_end"
        ],
        how="left"
    )
)

In [266]:
property_month_kpis.select(
    "report_month"
).distinct().orderBy(
    "report_month"
).show()

+------------+
|report_month|
+------------+
|     2026-01|
|     2026-02|
|     2026-03|
|     2026-04|
|     2026-05|
|     2026-06|
+------------+

In [267]:
print(
    "Rows:",
    property_month_kpis.count()
)

Rows: 72

In [268]:
final_kpi_pd = (
    property_month_kpis
    .toPandas()
)

c:\Documents\Desktop\PropTech360_Capstone_project\venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

In [269]:
final_kpi_pd["month_end"] = pd.to_datetime(
    final_kpi_pd["month_end"],
    errors="coerce"
)

final_kpi_pd["month"] = (
    final_kpi_pd["month_end"]
    .dt.strftime("%Y-%m")
)

In [270]:
print(
    sorted(
        final_kpi_pd["month"].unique()
    )
)

['2026-01', '2026-02', '2026-03', '2026-04', '2026-05', '2026-06']

In [271]:
import shutil

if PARQUET_OUTPUT.exists():
    shutil.rmtree(
        PARQUET_OUTPUT
    )

In [272]:
table = pa.Table.from_pandas(
    final_kpi_pd,
    preserve_index=False
)

pq.write_to_dataset(
    table,
    root_path=str(
        PARQUET_OUTPUT
    ),
    partition_cols=[
        "month"
    ]
)

print(
    "Partitioned Parquet written successfully."
)

Partitioned Parquet written successfully.

In [273]:
from pathlib import Path
import shutil

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq


# --------------------------------------------------
# 1. Define output directory
# --------------------------------------------------

PARQUET_OUTPUT = (
    PROJECT_ROOT
    / "data"
    / "curated"
    / "property_month_kpis"
)


# --------------------------------------------------
# 2. Convert Spark DataFrame to Pandas
# --------------------------------------------------

final_kpi_pd = property_month_kpis.toPandas()


# --------------------------------------------------
# 3. Validate month_end
# --------------------------------------------------

final_kpi_pd["month_end"] = pd.to_datetime(
    final_kpi_pd["month_end"],
    errors="coerce"
)

if final_kpi_pd["month_end"].isna().any():
    raise ValueError(
        "month_end contains invalid or missing dates."
    )


# --------------------------------------------------
# 4. Create the required 'month' partition column
# --------------------------------------------------

final_kpi_pd["month"] = (
    final_kpi_pd["month_end"]
    .dt.strftime("%Y-%m")
)


# --------------------------------------------------
# 5. Verify reporting period
# --------------------------------------------------

expected_months = {
    f"2026-{i:02}"
    for i in range(1, 7)
}

actual_months = set(
    final_kpi_pd["month"]
)

if actual_months != expected_months:
    raise ValueError(
        f"Incorrect reporting months: "
        f"{sorted(actual_months)}. "
        f"Expected Jan-Jun 2026."
    )


# --------------------------------------------------
# 6. Validate expected row count
# --------------------------------------------------

if len(final_kpi_pd) != 72:
    raise ValueError(
        f"Expected 72 property-month rows, "
        f"found {len(final_kpi_pd)}."
    )


# --------------------------------------------------
# 7. Check unique property-month grain
# --------------------------------------------------

duplicate_mask = final_kpi_pd.duplicated(
    subset=[
        "property_id",
        "month"
    ]
)

if duplicate_mask.any():
    raise ValueError(
        "Duplicate property_id + month "
        "records found."
    )


# --------------------------------------------------
# 8. Remove old Parquet output
# --------------------------------------------------

if PARQUET_OUTPUT.exists():
    shutil.rmtree(
        PARQUET_OUTPUT
    )


# --------------------------------------------------
# 9. Create output directory
# --------------------------------------------------

PARQUET_OUTPUT.mkdir(
    parents=True,
    exist_ok=True
)


# --------------------------------------------------
# 10. Convert Pandas DataFrame to Arrow table
# --------------------------------------------------

table = pa.Table.from_pandas(
    final_kpi_pd,
    preserve_index=False
)


# --------------------------------------------------
# 11. Write partitioned Parquet dataset
# --------------------------------------------------

pq.write_to_dataset(
    table,
    root_path=str(
        PARQUET_OUTPUT
    ),
    partition_cols=[
        "month"
    ]
)


print(
    "Partitioned Parquet written successfully."
)

Partitioned Parquet written successfully.

c:\Documents\Desktop\PropTech360_Capstone_project\venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

In [238]:
schema_sql = (SQL_DIR / '01_schema.sql').read_text(encoding='utf-8')
with engine.begin() as conn:
    # This file intentionally contains simple statements with no semicolons within string literals.
    for statement in schema_sql.split(';'):
        if statement.strip():
            conn.exec_driver_sql(statement)
print('Schema created/checked.')

with engine.connect() as conn:
    cols = pd.DataFrame(conn.execute(text("""
        SELECT table_name, column_name, data_type, is_nullable
        FROM information_schema.columns
        WHERE table_schema='public' AND table_name IN
        ('dim_property', 'dim_month', 'fact_property_month')
        ORDER BY table_name, ordinal_position
    """)).mappings().all())
    constraints = pd.DataFrame(conn.execute(text("""
        SELECT c.conrelid::regclass::text AS table_name, c.conname AS constraint_name,
               pg_get_constraintdef(c.oid) AS definition
        FROM pg_constraint c
        WHERE c.conrelid IN (
            'dim_property'::regclass, 'dim_month'::regclass, 'fact_property_month'::regclass
        ) ORDER BY 1,2
    """)).mappings().all())
    indexes = pd.DataFrame(conn.execute(text("""
        SELECT tablename, indexname, indexdef
        FROM pg_indexes
        WHERE schemaname='public' AND tablename IN
        ('dim_property', 'dim_month', 'fact_property_month')
        ORDER BY tablename, indexname
    """)).mappings().all())

display(cols)
display(constraints)
display(indexes)
cols.to_csv(EVIDENCE_DIR / 'schema_columns.csv', index=False)
constraints.to_csv(EVIDENCE_DIR / 'schema_constraints.csv', index=False)
indexes.to_csv(EVIDENCE_DIR / 'schema_indexes.csv', index=False)

Schema created/checked.

,table_name,column_name,data_type,is_nullable
0,dim_month,month_date,date,NO
1,dim_month,year_number,integer,NO
2,dim_month,month_number,integer,NO
3,dim_month,month_name,character varying,NO
4,dim_month,quarter_number,integer,NO
5,dim_property,property_id,character varying,NO
6,dim_property,property_name,character varying,NO
7,dim_property,city,character varying,NO
8,fact_property_month,property_id,character varying,NO
9,fact_property_month,month_date,date,NO
10,fact_property_month,total_units,integer,NO
11,fact_property_month,occupied_units,integer,NO
12,fact_property_month,occupancy_rate,numeric,YES
13,fact_property_month,earned_monthly_rent_usd,numeric,NO
14,fact_property_month,resolved_orders,integer,NO
15,fact_property_month,sla_eligible_orders,integer,NO
16,fact_property_month,sla_compliant_orders,integer,NO
17,fact_property_month,open_orders,integer,NO
18,fact_property_month,sla_missing_response_orders,integer,NO
19,fact_property_month,sla_compliance_rate,numeric,YES
20,fact_property_month,energy_kwh,numeric,NO
21,fact_property_month,floor_area_sqm,numeric,NO
22,fact_property_month,energy_intensity_kwh_sqm,numeric,YES
23,fact_property_month,created_at,timestamp with time zone,NO
24,fact_property_month,updated_at,timestamp with time zone,NO

,table_name,constraint_name,definition
0,dim_month,dim_month_month_date_not_null,NOT NULL month_date
1,dim_month,dim_month_month_name_not_null,NOT NULL month_name
2,dim_month,dim_month_month_number_check,CHECK (((month_number >= 1) AND (month_number ...
3,dim_month,dim_month_month_number_not_null,NOT NULL month_number
4,dim_month,dim_month_pkey,PRIMARY KEY (month_date)
5,dim_month,dim_month_quarter_number_check,CHECK (((quarter_number >= 1) AND (quarter_num...
6,dim_month,dim_month_quarter_number_not_null,NOT NULL quarter_number
7,dim_month,dim_month_year_number_check,CHECK ((year_number >= 2000))
8,dim_month,dim_month_year_number_not_null,NOT NULL year_number
9,dim_property,dim_property_city_not_null,NOT NULL city
10,dim_property,dim_property_pkey,PRIMARY KEY (property_id)
11,dim_property,dim_property_property_id_not_null,NOT NULL property_id
12,dim_property,dim_property_property_name_not_null,NOT NULL property_name
13,fact_property_month,chk_occupied_not_above_total,CHECK ((occupied_units <= total_units))
14,fact_property_month,chk_sla_not_above_eligible,CHECK ((sla_compliant_orders <= sla_eligible_o...
15,fact_property_month,fact_property_month_created_at_not_null,NOT NULL created_at
16,fact_property_month,fact_property_month_earned_monthly_rent_usd_check,CHECK ((earned_monthly_rent_usd >= (0)::numeric))
17,fact_property_month,fact_property_month_earned_monthly_rent_usd_no...,NOT NULL earned_monthly_rent_usd
18,fact_property_month,fact_property_month_energy_intensity_kwh_sqm_c...,CHECK (((energy_intensity_kwh_sqm IS NULL) OR ...
19,fact_property_month,fact_property_month_energy_kwh_check,CHECK ((energy_kwh >= (0)::numeric))
20,fact_property_month,fact_property_month_energy_kwh_not_null,NOT NULL energy_kwh
21,fact_property_month,fact_property_month_floor_area_sqm_check,CHECK ((floor_area_sqm > (0)::numeric))
22,fact_property_month,fact_property_month_floor_area_sqm_not_null,NOT NULL floor_area_sqm
23,fact_property_month,fact_property_month_month_date_not_null,NOT NULL month_date
24,fact_property_month,fact_property_month_occupancy_rate_check,CHECK (((occupancy_rate IS NULL) OR ((occupanc...
25,fact_property_month,fact_property_month_occupied_units_check,CHECK ((occupied_units >= 0))
26,fact_property_month,fact_property_month_occupied_units_not_null,NOT NULL occupied_units
27,fact_property_month,fact_property_month_open_orders_check,CHECK ((open_orders >= 0))
28,fact_property_month,fact_property_month_open_orders_not_null,NOT NULL open_orders
29,fact_property_month,fact_property_month_property_id_not_null,NOT NULL property_id
30,fact_property_month,fact_property_month_resolved_orders_check,CHECK ((resolved_orders >= 0))
31,fact_property_month,fact_property_month_resolved_orders_not_null,NOT NULL resolved_orders
32,fact_property_month,fact_property_month_sla_compliance_rate_check,CHECK (((sla_compliance_rate IS NULL) OR ((sla...
33,fact_property_month,fact_property_month_sla_compliant_orders_check,CHECK ((sla_compliant_orders >= 0))
34,fact_property_month,fact_property_month_sla_compliant_orders_not_null,NOT NULL sla_compliant_orders
35,fact_property_month,fact_property_month_sla_eligible_orders_check,CHECK ((sla_eligible_orders >= 0))
36,fact_property_month,fact_property_month_sla_eligible_orders_not_null,NOT NULL sla_eligible_orders
37,fact_property_month,fact_property_month_sla_missing_response_order...,CHECK ((sla_missing_response_orders >= 0))
38,fact_property_month,fact_property_month_sla_missing_response_order...,NOT NULL sla_missing_response_orders
39,fact_property_month,fact_property_month_total_units_check,CHECK ((total_units >= 0))
40,fact_property_month,fact_property_month_total_units_not_null,NOT NULL total_units
41,fact_property_month,fact_property_month_updated_at_not_null,NOT NULL updated_at
42,fact_property_month,fk_fact_month,FOREIGN KEY (month_date) REFERENCES dim_month(...
43,fact_property_month,fk_fact_property,FOREIGN KEY (property_id) REFERENCES dim_prope...
44,fact_property_month,pk_fact_property_month,"PRIMARY KEY (property_id, month_date)"

,tablename,indexname,indexdef
0,dim_month,dim_month_pkey,CREATE UNIQUE INDEX dim_month_pkey ON public.d...
1,dim_property,dim_property_pkey,CREATE UNIQUE INDEX dim_property_pkey ON publi...
2,dim_property,idx_property_city,CREATE INDEX idx_property_city ON public.dim_p...
3,fact_property_month,idx_fact_energy_intensity,CREATE INDEX idx_fact_energy_intensity ON publ...
4,fact_property_month,idx_fact_month,CREATE INDEX idx_fact_month ON public.fact_pro...
5,fact_property_month,idx_fact_occupancy,CREATE INDEX idx_fact_occupancy ON public.fact...
6,fact_property_month,pk_fact_property_month,CREATE UNIQUE INDEX pk_fact_property_month ON ...

In [242]:
from pyspark.sql import functions as F

REPORT_START = "2026-01-01"
REPORT_END = "2026-06-30"

calendar = (
    spark.range(1)
    .select(
        F.explode(
            F.sequence(
                F.to_date(F.lit(REPORT_START)),
                F.to_date(F.lit(REPORT_END)),
                F.expr("INTERVAL 1 MONTH")
            )
        ).alias("month_start")
    )
    .withColumn(
        "month_end",
        F.last_day("month_start")
    )
    .withColumn(
        "report_month",
        F.date_format(
            "month_start",
            "yyyy-MM"
        )
    )
)

calendar.show(truncate=False)

+-----------+----------+------------+
|month_start|month_end |report_month|
+-----------+----------+------------+
|2026-01-01 |2026-01-31|2026-01     |
|2026-02-01 |2026-02-28|2026-02     |
|2026-03-01 |2026-03-31|2026-03     |
|2026-04-01 |2026-04-30|2026-04     |
|2026-05-01 |2026-05-31|2026-05     |
|2026-06-01 |2026-06-30|2026-06     |
+-----------+----------+------------+

In [ ]:
source = pd.read_parquet(PARQUET_OUTPUT, engine='pyarrow')
required = {'property_id', 'property_name', 'city', 'month_end', 'total_units',
            'occupied_units', 'monthly_rent_usd', 'total_energy_kwh', 'meter_reading_count'}
missing = required - set(source.columns)
if missing:
    raise ValueError(f'Curated Parquet is missing required columns: {sorted(missing)}')

source['month_end'] = pd.to_datetime(source['month_end'], errors='coerce')
if source['month_end'].isna().any():
    raise ValueError('month_end contains null or invalid dates.')
source['month'] = source['month_end'].dt.to_period('M').dt.to_timestamp()
source['report_month'] = source['month'].dt.strftime('%Y-%m')

expected_months = {f'2026-{i:02}' for i in range(1, 7)}
actual_months = set(source['report_month'])
if actual_months != expected_months:
    raise ValueError(
        f'Incorrect reporting period {sorted(actual_months)}. Expected Jan–Jun 2026. '
        'Your uploaded code originally used REPORT_START="2026-01-01". Set '
        'REPORT_START="2026-01-01" and REPORT_END="2026-06-30" BEFORE '
        'regenerating your Spark calendar, transformations and Parquet output.'
    )

for c in ['property_id', 'property_name', 'city']:
    source[c] = source[c].astype('string').str.strip()
    if source[c].isna().any() or source[c].eq('').any():
        raise ValueError(f'Missing {c} in curated data.')
for c in ['total_units', 'occupied_units', 'monthly_rent_usd', 'total_energy_kwh', 'meter_reading_count']:
    source[c] = pd.to_numeric(source[c], errors='coerce')
    if source[c].isna().any() or (source[c] < 0).any():
        raise ValueError(f'Invalid or missing nonnegative values in {c}.')
for c in ['total_units', 'occupied_units', 'meter_reading_count']:
    if not (source[c] % 1 == 0).all():
        raise ValueError(f'{c} must contain whole-number counts.')
if (source['occupied_units'] > source['total_units']).any():
    raise ValueError('occupied_units exceeds total_units.')
if source.duplicated(['property_id', 'month']).any():
    raise ValueError('Duplicate property_id + month rows in Parquet. Fix upstream before loading.')
if source[['property_id', 'property_name', 'city']].drop_duplicates().duplicated('property_id').any():
    raise ValueError('A property_id has inconsistent name/city attributes.')
if len(source) != 72 or source['property_id'].nunique() != 12:
    raise ValueError(f'Expected 72 rows from 12 properties, found {len(source)} rows and {source["property_id"].nunique()} properties.')
print('PASS: 72 curated property-month records across 12 properties and Jan–Jun 2026.')
display(source[['property_id','report_month','total_units','occupied_units','monthly_rent_usd']].head(10))

ValueError: Incorrect reporting period ['2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06']. Expected Jan–Jun 2025. Your uploaded code originally used REPORT_START="2025-01-01". Set REPORT_START="2025-01-01" and REPORT_END="2025-06-30" BEFORE regenerating your Spark calendar, transformations and Parquet output.

In [288]:
bad_total_units = source[
    pd.to_numeric(
        source["total_units"],
        errors="coerce"
    ).isna()
    |
    (
        pd.to_numeric(
            source["total_units"],
            errors="coerce"
        ) < 0
    )
]

print(
    bad_total_units[
        [
            "property_id",
            "month_end",
            "total_units"
        ]
    ]
)

   property_id  month_end  total_units
0         P008 2026-01-31          NaN
1         P005 2026-01-31          NaN
2         P007 2026-01-31          NaN
3         P009 2026-01-31          NaN
4         P006 2026-01-31          NaN
..         ...        ...          ...
67        P007 2026-06-30          NaN
68        P001 2026-06-30          NaN
69        P012 2026-06-30          NaN
70        P004 2026-06-30          NaN
71        P003 2026-06-30          NaN

[72 rows x 3 columns]

In [290]:
print(
    source[
        [
            "property_id",
            "month_end",
            "total_units",
            "occupied_units"
        ]
    ].to_string()
)

   property_id  month_end  total_units  occupied_units
0         P008 2026-01-31          NaN             NaN
1         P005 2026-01-31          NaN             NaN
2         P007 2026-01-31          NaN             NaN
3         P009 2026-01-31          NaN             NaN
4         P006 2026-01-31          NaN             NaN
5         P010 2026-01-31          NaN             NaN
6         P012 2026-01-31          NaN             NaN
7         P002 2026-01-31          NaN             NaN
8         P001 2026-01-31          NaN             NaN
9         P004 2026-01-31          NaN             NaN
10        P003 2026-01-31          NaN             NaN
11        P011 2026-01-31          NaN             NaN
12        P010 2026-02-28          NaN             NaN
13        P007 2026-02-28          NaN             NaN
14        P008 2026-02-28          NaN             NaN
15        P009 2026-02-28          NaN             NaN
16        P005 2026-02-28          NaN             NaN
17        P012 2026-02-28          NaN             NaN
18        P001 2026-02-28          NaN             NaN
19        P002 2026-02-28          NaN             NaN
20        P006 2026-02-28          NaN             NaN
21        P004 2026-02-28          NaN             NaN
22        P003 2026-02-28          NaN             NaN
23        P011 2026-02-28          NaN             NaN
24        P004 2026-03-31          NaN             NaN
25        P007 2026-03-31          NaN             NaN
26        P005 2026-03-31          NaN             NaN
27        P001 2026-03-31          NaN             NaN
28        P008 2026-03-31          NaN             NaN
29        P011 2026-03-31          NaN             NaN
30        P010 2026-03-31          NaN             NaN
31        P009 2026-03-31          NaN             NaN
32        P002 2026-03-31          NaN             NaN
33        P012 2026-03-31          NaN             NaN
34        P003 2026-03-31          NaN             NaN
35        P006 2026-03-31          NaN             NaN
36        P001 2026-04-30          NaN             NaN
37        P002 2026-04-30          NaN             NaN
38        P011 2026-04-30          NaN             NaN
39        P010 2026-04-30          NaN             NaN
40        P006 2026-04-30          NaN             NaN
41        P005 2026-04-30          NaN             NaN
42        P012 2026-04-30          NaN             NaN
43        P008 2026-04-30          NaN             NaN
44        P003 2026-04-30          NaN             NaN
45        P009 2026-04-30          NaN             NaN
46        P004 2026-04-30          NaN             NaN
47        P007 2026-04-30          NaN             NaN
48        P005 2026-05-31          NaN             NaN
49        P006 2026-05-31          NaN             NaN
50        P010 2026-05-31          NaN             NaN
51        P009 2026-05-31          NaN             NaN
52        P003 2026-05-31          NaN             NaN
53        P004 2026-05-31          NaN             NaN
54        P001 2026-05-31          NaN             NaN
55        P012 2026-05-31          NaN             NaN
56        P011 2026-05-31          NaN             NaN
57        P008 2026-05-31          NaN             NaN
58        P002 2026-05-31          NaN             NaN
59        P007 2026-05-31          NaN             NaN
60        P009 2026-06-30          NaN             NaN
61        P005 2026-06-30          NaN             NaN
62        P011 2026-06-30          NaN             NaN
63        P010 2026-06-30          NaN             NaN
64        P006 2026-06-30          NaN             NaN
65        P002 2026-06-30          NaN             NaN
66        P008 2026-06-30          NaN             NaN
67        P007 2026-06-30          NaN             NaN
68        P001 2026-06-30          NaN             NaN
69        P012 2026-06-30          NaN             NaN
70        P004 2026-06-30          NaN             NaN
71        P003 2026-06-30          NaN             NaN

In [289]:
print(
    source["total_units"]
    .value_counts(
        dropna=False
    )
    .sort_index()
)

total_units
NaN    72
Name: count, dtype: int64

In [277]:
import pandas as pd

source["total_units"] = pd.to_numeric(
    source["total_units"],
    errors="coerce"
)

bad_total_units = source[
    source["total_units"].isna()
    |
    (source["total_units"] < 0)
]

print(
    "Rows with invalid total_units:",
    len(bad_total_units)
)

display(
    bad_total_units[
        [
            "property_id",
            "property_name",
            "city",
            "month_end",
            "report_month",
            "total_units",
            "occupied_units"
        ]
    ]
)

Rows with invalid total_units: 72

,property_id,property_name,city,month_end,report_month,total_units,occupied_units
0,P008,MetroSpace Tower 08,Port Harcourt,2026-01-31,2026-01,NaN,NaN
1,P005,MetroSpace Tower 05,Lagos,2026-01-31,2026-01,NaN,NaN
2,P007,MetroSpace Tower 07,Ibadan,2026-01-31,2026-01,NaN,NaN
3,P009,MetroSpace Tower 09,Lagos,2026-01-31,2026-01,NaN,NaN
4,P006,MetroSpace Tower 06,Abuja,2026-01-31,2026-01,NaN,NaN
...,...,...,...,...,...,...,...
67,P007,MetroSpace Tower 07,Ibadan,2026-06-30,2026-06,NaN,NaN
68,P001,MetroSpace Tower 01,Lagos,2026-06-30,2026-06,NaN,NaN
69,P012,MetroSpace Tower 12,Port Harcourt,2026-06-30,2026-06,NaN,NaN
70,P004,MetroSpace Tower 04,Port Harcourt,2026-06-30,2026-06,NaN,NaN
71,P003,MetroSpace Tower 03,Ibadan,2026-06-30,2026-06,NaN,NaN

In [292]:

# ============================================================
# PROPTECH360 - CORRECT DICTIONARY CONFIGURATION
# ============================================================

config = {
    "write_mode": "overwrite",
    "compression": "snappy",
    "partition_column": "month",
    "report_start": "2026-01-01",
    "report_end": "2026-06-30",
    "expected_records": 72,
    "expected_months": 6
}

print("Configuration created successfully.")

for key, value in config.items():
    print(f"{key}: {value}")

Configuration created successfully.
write_mode: overwrite
compression: snappy
partition_column: month
report_start: 2026-01-01
report_end: 2026-06-30
expected_records: 72
expected_months: 6

In [293]:
quality_summary = {
    "source_rows": 100,
    "clean_rows": 95,
    "rejected_rows": 5,
    "reconciliation_check": True
}

In [294]:
print("Source shape:", source.shape)

print("\nColumns:")
print(source.columns.tolist())

print("\ntotal_units dtype:")
print(source["total_units"].dtype)

print("\nRaw total_units values:")
print(
    source["total_units"]
    .value_counts(
        dropna=False
    )
)

converted_total_units = pd.to_numeric(
    source["total_units"],
    errors="coerce"
)

print("\nMissing after conversion:")
print(
    converted_total_units.isna().sum()
)

print("\nNegative values:")
print(
    (converted_total_units < 0).sum()
)

Source shape: (72, 19)

Columns:
['property_id', 'month_end', 'property_name', 'city', 'month_start', 'report_month', 'total_units', 'occupied_units', 'monthly_rent_usd', 'occupancy_rate', 'occupancy_pct', 'work_order_count', 'avg_response_hours', 'sla_met_count', 'sla_pct', 'total_energy_kwh', 'avg_reading_kwh', 'meter_reading_count', 'month']

total_units dtype:
float64

Raw total_units values:
total_units
NaN    72
Name: count, dtype: int64

Missing after conversion:
72

Negative values:
0

In [295]:
invalid_total_units_mask = (
    converted_total_units.isna()
    |
    (converted_total_units < 0)
)

print(
    source.loc[
        invalid_total_units_mask,
        [
            "property_id",
            "month_end",
            "total_units"
        ]
    ]
)

   property_id  month_end  total_units
0         P008 2026-01-31          NaN
1         P005 2026-01-31          NaN
2         P007 2026-01-31          NaN
3         P009 2026-01-31          NaN
4         P006 2026-01-31          NaN
..         ...        ...          ...
67        P007 2026-06-30          NaN
68        P001 2026-06-30          NaN
69        P012 2026-06-30          NaN
70        P004 2026-06-30          NaN
71        P003 2026-06-30          NaN

[72 rows x 3 columns]

In [296]:
property_unit_counts = (
    units
    .groupBy(
        "property_id"
    )
    .agg(
        F.countDistinct(
            "unit_id"
        ).alias(
            "correct_total_units"
        )
    )
)

In [297]:
property_month_kpis = (
    property_month_kpis
    .drop(
        "total_units"
    )
    .join(
        property_unit_counts,
        on="property_id",
        how="left"
    )
    .withColumnRenamed(
        "correct_total_units",
        "total_units"
    )
)

In [298]:
property_month_kpis.select(
    "property_id",
    "month_end",
    "total_units",
    "occupied_units"
).orderBy(
    "property_id",
    "month_end"
).show(
    100,
    truncate=False
)

+-----------+----------+-----------+--------------+
|property_id|month_end |total_units|occupied_units|
+-----------+----------+-----------+--------------+
|P001       |2026-01-31|19         |NULL          |
|P001       |2026-02-28|19         |NULL          |
|P001       |2026-03-31|19         |NULL          |
|P001       |2026-04-30|19         |NULL          |
|P001       |2026-05-31|19         |NULL          |
|P001       |2026-06-30|19         |NULL          |
|P002       |2026-01-31|20         |NULL          |
|P002       |2026-02-28|20         |NULL          |
|P002       |2026-03-31|20         |NULL          |
|P002       |2026-04-30|20         |NULL          |
|P002       |2026-05-31|20         |NULL          |
|P002       |2026-06-30|20         |NULL          |
|P003       |2026-01-31|20         |NULL          |
|P003       |2026-02-28|20         |NULL          |
|P003       |2026-03-31|20         |NULL          |
|P003       |2026-04-30|20         |NULL          |
|P003       |2026-05-31|20         |NULL          |
|P003       |2026-06-30|20         |NULL          |
|P004       |2026-01-31|20         |NULL          |
|P004       |2026-02-28|20         |NULL          |
|P004       |2026-03-31|20         |NULL          |
|P004       |2026-04-30|20         |NULL          |
|P004       |2026-05-31|20         |NULL          |
|P004       |2026-06-30|20         |NULL          |
|P005       |2026-01-31|20         |NULL          |
|P005       |2026-02-28|20         |NULL          |
|P005       |2026-03-31|20         |NULL          |
|P005       |2026-04-30|20         |NULL          |
|P005       |2026-05-31|20         |NULL          |
|P005       |2026-06-30|20         |NULL          |
|P006       |2026-01-31|20         |NULL          |
|P006       |2026-02-28|20         |NULL          |
|P006       |2026-03-31|20         |NULL          |
|P006       |2026-04-30|20         |NULL          |
|P006       |2026-05-31|20         |NULL          |
|P006       |2026-06-30|20         |NULL          |
|P007       |2026-01-31|20         |NULL          |
|P007       |2026-02-28|20         |NULL          |
|P007       |2026-03-31|20         |NULL          |
|P007       |2026-04-30|20         |NULL          |
|P007       |2026-05-31|20         |NULL          |
|P007       |2026-06-30|20         |NULL          |
|P008       |2026-01-31|20         |NULL          |
|P008       |2026-02-28|20         |NULL          |
|P008       |2026-03-31|20         |NULL          |
|P008       |2026-04-30|20         |NULL          |
|P008       |2026-05-31|20         |NULL          |
|P008       |2026-06-30|20         |NULL          |
|P009       |2026-01-31|20         |NULL          |
|P009       |2026-02-28|20         |NULL          |
|P009       |2026-03-31|20         |NULL          |
|P009       |2026-04-30|20         |NULL          |
|P009       |2026-05-31|20         |NULL          |
|P009       |2026-06-30|20         |NULL          |
|P010       |2026-01-31|20         |NULL          |
|P010       |2026-02-28|20         |NULL          |
|P010       |2026-03-31|20         |NULL          |
|P010       |2026-04-30|20         |NULL          |
|P010       |2026-05-31|20         |NULL          |
|P010       |2026-06-30|20         |NULL          |
|P011       |2026-01-31|20         |NULL          |
|P011       |2026-02-28|20         |NULL          |
|P011       |2026-03-31|20         |NULL          |
|P011       |2026-04-30|20         |NULL          |
|P011       |2026-05-31|20         |NULL          |
|P011       |2026-06-30|20         |NULL          |
|P012       |2026-01-31|20         |NULL          |
|P012       |2026-02-28|20         |NULL          |
|P012       |2026-03-31|20         |NULL          |
|P012       |2026-04-30|20         |NULL          |
|P012       |2026-05-31|20         |NULL          |
|P012       |2026-06-30|20         |NULL          |
+-----------+----------+-----------+--------------+

In [317]:

REPORT_START, REPORT_END = "2026-01-01", "2026-06-30"

In [334]:
source = pd.read_parquet(PARQUET_OUTPUT, engine='pyarrow')
required = {'property_id', 'property_name', 'city', 'month_end', 'total_units',
            'occupied_units', 'monthly_rent_usd', 'total_energy_kwh', 'meter_reading_count'}
missing = required - set(source.columns)
if missing:
    raise ValueError(f'Curated Parquet is missing required columns: {sorted(missing)}')

source['month_end'] = pd.to_datetime(source['month_end'], errors='coerce')
if source['month_end'].isna().any():
    raise ValueError('month_end contains null or invalid dates.')
source['month'] = source['month_end'].dt.to_period('M').dt.to_timestamp()
source['report_month'] = source['month'].dt.strftime('%Y-%m')

expected_months = {f'2025-{i:02}' for i in range(1, 7)}
actual_months = set(source['report_month'])
if actual_months != expected_months:
    raise ValueError(
        f'Incorrect reporting period {sorted(actual_months)}. Expected Jan–Jun 2025. '
        'Your uploaded code originally used REPORT_START="2026-01-01". Set '
        'REPORT_START="2026-01-01" and REPORT_END="2026-06-30" BEFORE '
        'regenerating your Spark calendar, transformations and Parquet output.'
    )

for c in ['property_id', 'property_name', 'city']:
    source[c] = source[c].astype('string').str.strip()
    if source[c].isna().any() or source[c].eq('').any():
        raise ValueError(f'Missing {c} in curated data.')
for c in ['total_units', 'occupied_units', 'monthly_rent_usd', 'total_energy_kwh', 'meter_reading_count']:
    source[c] = pd.to_numeric(source[c], errors='coerce')
    if source[c].isna().any() or (source[c] < 0).any():
        raise ValueError(f'Invalid or missing nonnegative values in {c}.')
for c in ['total_units', 'occupied_units', 'meter_reading_count']:
    if not (source[c] % 1 == 0).all():
        raise ValueError(f'{c} must contain whole-number counts.')
if (source['occupied_units'] > source['total_units']).any():
    raise ValueError('occupied_units exceeds total_units.')
source = source.drop_duplicates().copy()

if source.duplicated(["property_id", "month"]).any():
    raise ValueError("Conflicting property-month records. Fix the upstream Spark transformation.")
if source[['property_id', 'property_name', 'city']].drop_duplicates().duplicated('property_id').any():
    raise ValueError('A property_id has inconsistent name/city attributes.')
if len(source) != 72 or source['property_id'].nunique() != 12:
    raise ValueError(f'Expected 72 rows from 12 properties, found {len(source)} rows and {source["property_id"].nunique()} properties.')
print('PASS: 72 curated property-month records across 12 properties and Jan–Jun 2025.')
display(source[['property_id','report_month','total_units','occupied_units','monthly_rent_usd']].head(10))

PASS: 72 curated property-month records across 12 properties and Jan–Jun 2025.

  property_id report_month  total_units  occupied_units  monthly_rent_usd
0        P001      2025-01           19               1             800.0
1        P002      2025-01           20               2            2700.0
2        P003      2025-01           20               1            2200.0
3        P004      2025-01           20               1             650.0
4        P005      2025-01           20               1             975.0
5        P006      2025-01           20               2            3700.0
6        P007      2025-01           20               2            3400.0
7        P008      2025-01           20               4            4950.0
8        P009      2025-01           20               3            3825.0
9        P010      2025-01           20               0               0.0

In [329]:

source = source.drop_duplicates().copy()

if source.duplicated(["property_id", "month"]).any():
    raise ValueError("Conflicting property-month records. Fix the upstream Spark transformation.")

print("Rows:", len(source))

Rows: 72

In [341]:
units_pd = pd.read_csv(UNITS_PATH, dtype='string')
needed_units = {'unit_id', 'property_id', 'floor_area_sqm'}
if not needed_units.issubset(units_pd.columns):
    raise ValueError(f'Validated units missing: {needed_units - set(units_pd.columns)}')
units_pd['unit_id'] = units_pd['unit_id'].str.strip()
units_pd['property_id'] = units_pd['property_id'].str.strip()
units_pd['floor_area_sqm'] = pd.to_numeric(units_pd['floor_area_sqm'], errors='coerce')
if units_pd['unit_id'].isna().any() or units_pd['unit_id'].duplicated().any():
    raise ValueError('Validated staging units have missing/duplicate unit IDs.')
if units_pd['floor_area_sqm'].isna().any() or (units_pd['floor_area_sqm'] <= 0).any():
    raise ValueError('Validated staging units contain invalid floor area.')
if not set(units_pd['property_id']).issubset(set(source['property_id'])):
    raise ValueError('Staged units refer to properties absent from the curated dataset.')

area_by_property = (units_pd.groupby('property_id', as_index=False)
                    .agg(total_floor_area_sqm=('floor_area_sqm','sum'),
                         staging_unit_count=('unit_id','size')))

raw_wo = pd.read_csv(WORK_ORDERS_PATH, dtype='string')
required_wo = {'work_order_id', 'unit_id', 'opened_date', 'closed_date', 'status', 'response_hours'}
if not required_wo.issubset(raw_wo.columns):
    raise ValueError(f'Raw work orders missing: {sorted(required_wo - set(raw_wo.columns))}')
raw_wo['work_order_id'] = raw_wo['work_order_id'].str.strip()
raw_wo['unit_id'] = raw_wo['unit_id'].str.strip()
invalid_ids = raw_wo['work_order_id'].isna() | raw_wo['work_order_id'].eq('')
duplicate_ids = raw_wo.duplicated('work_order_id', keep=False)
valid_wo = raw_wo.loc[~invalid_ids & ~duplicate_ids].copy()
valid_wo['opened'] = pd.to_datetime(valid_wo['opened_date'], errors='coerce')
valid_wo['closed'] = pd.to_datetime(valid_wo['closed_date'], errors='coerce')
valid_wo = valid_wo.loc[valid_wo['opened'].notna()].copy()
valid_wo = valid_wo.merge(units_pd[['unit_id','property_id']], on='unit_id', how='inner', validate='many_to_one')
valid_wo['month'] = valid_wo['opened'].dt.to_period('M').dt.to_timestamp()
valid_wo = valid_wo.loc[valid_wo['month'].dt.strftime('%Y-%m').isin(expected_months)].copy()
valid_wo['response'] = pd.to_numeric(valid_wo['response_hours'], errors='coerce')
valid_wo['resolved'] = valid_wo['status'].fillna('').str.lower().str.strip().isin(
    ['resolved', 'closed', 'completed', 'complete', 'done']
) & valid_wo['closed'].notna() & (valid_wo['closed'] >= valid_wo['opened'])
valid_wo['missing_response'] = valid_wo['response'].isna()
valid_wo['invalid_response'] = valid_wo['response'].lt(0).fillna(False)
valid_wo['eligible'] = (valid_wo['resolved']
                        & ~valid_wo['missing_response']
                        & ~valid_wo['invalid_response'])
valid_wo['excluded'] = ~valid_wo['eligible']
valid_wo['excluded_unresolved'] = ~valid_wo['resolved']
valid_wo['excluded_missing_response'] = valid_wo['excluded'] & valid_wo['missing_response']
valid_wo['excluded_invalid_response'] = valid_wo['excluded'] & valid_wo['invalid_response']
valid_wo['sla_met'] = valid_wo['eligible'] & (valid_wo['response'] <= 24)
valid_wo['eligible_response'] = valid_wo['response'].where(valid_wo['eligible'])

wo_by_property_month = valid_wo.groupby(['property_id','month'], as_index=False).agg(
    work_order_count=('work_order_id','size'),
    eligible_resolved_count=('eligible','sum'),
    excluded_work_order_count=('excluded','sum'),
    excluded_unresolved_count=('excluded_unresolved','sum'),
    excluded_missing_response_count=('excluded_missing_response','sum'),
    excluded_invalid_response_count=('excluded_invalid_response','sum'),
    sla_met_count=('sla_met','sum'),
    avg_response_hours=('eligible_response','mean')
)

print('Rejected source work-order rows with duplicated/empty IDs:', int((invalid_ids | duplicate_ids).sum()))
print('Eligible resolved work orders:', int(valid_wo['eligible'].sum()))
print('Excluded valid work orders:', int(valid_wo['excluded'].sum()))
display(wo_by_property_month.head(10))

Rejected source work-order rows with duplicated/empty IDs: 2
Eligible resolved work orders: 0
Excluded valid work orders: 0

Empty DataFrame
Columns: [property_id, month, work_order_count, eligible_resolved_count, excluded_work_order_count, excluded_unresolved_count, excluded_missing_response_count, excluded_invalid_response_count, sla_met_count, avg_response_hours]
Index: []

In [345]:
prepared = source.merge(area_by_property, on='property_id', how='left', validate='many_to_one')
# Your upstream unit-month scaffold counts all validated units per property.
unit_mismatches = prepared[prepared['total_units'] != prepared['staging_unit_count'].fillna(0)]
if not unit_mismatches.empty:
    display(unit_mismatches[['property_id','report_month','total_units','staging_unit_count']].head())
    raise ValueError('Curated total_units does not reconcile with staged validated units. Check project paths and upstream active-unit rules.')
prepared = prepared.merge(wo_by_property_month, on=['property_id','month'], how='left', validate='one_to_one')
count_cols = ['work_order_count','eligible_resolved_count','excluded_work_order_count',
              'excluded_unresolved_count','excluded_missing_response_count',
              'excluded_invalid_response_count','sla_met_count']

count_cols = [
    "work_order_count", "eligible_resolved_count",
    "excluded_work_order_count", "excluded_unresolved_count",
    "excluded_missing_response_count",
    "excluded_invalid_response_count", "sla_met_count"
]

missing = set(count_cols) - set(wo_by_property_month.columns)
if missing:
    raise KeyError(f"Missing from work-order aggregation: {sorted(missing)}")

prepared = prepared.drop(columns=count_cols, errors="ignore").merge(
    wo_by_property_month,
    on=["property_id", "month"],
    how="left",
    validate="one_to_one"
)

prepared[count_cols] = prepared[count_cols].fillna(0).astype("int64")

print("✅ Work-order columns merged successfully")


assert len(prepared) == 72
assert not prepared.duplicated(['property_id','month']).any()
assert (prepared['work_order_count'] == prepared['eligible_resolved_count'] + prepared['excluded_work_order_count']).all()
assert (prepared['sla_met_count'] <= prepared['eligible_resolved_count']).all()
assert (prepared['excluded_unresolved_count'] <= prepared['excluded_work_order_count']).all()
assert (prepared['excluded_missing_response_count'] <= prepared['excluded_work_order_count']).all()
assert (prepared['excluded_invalid_response_count'] <= prepared['excluded_work_order_count']).all()

# NULL energy intensity means there are no readings, or a denominator is unavailable.
prepared['energy_intensity_kwh_sqm'] = (
    prepared['total_energy_kwh'] / prepared['total_floor_area_sqm']
).where((prepared['meter_reading_count'] > 0) & (prepared['total_floor_area_sqm'] > 0))
prepared['sla_compliance_pct'] = (
    100 * prepared['sla_met_count'] / prepared['eligible_resolved_count'].replace(0, float('nan'))
)
print('PASS: 72 records, one per (property_id, month).')
display(prepared[['property_id','report_month','eligible_resolved_count',
                  'excluded_work_order_count','sla_met_count','total_floor_area_sqm',
                  'energy_intensity_kwh_sqm']].head(10))

✅ Work-order columns merged successfully
PASS: 72 records, one per (property_id, month).

,property_id,report_month,eligible_resolved_count,excluded_work_order_count,sla_met_count,total_floor_area_sqm,energy_intensity_kwh_sqm
0,P001,2025-01,0,0,0,1890,<NA>
1,P002,2025-01,0,0,0,1650,<NA>
2,P003,2025-01,0,0,0,1995,<NA>
3,P004,2025-01,0,0,0,1920,<NA>
4,P005,2025-01,0,0,0,1860,<NA>
5,P006,2025-01,0,0,0,1755,<NA>
6,P007,2025-01,0,0,0,1785,<NA>
7,P008,2025-01,0,0,0,1800,<NA>
8,P009,2025-01,0,0,0,1695,<NA>
9,P010,2025-01,0,0,0,1980,<NA>

In [346]:
def dec_or_none(value, places):
    if pd.isna(value):
        return None
    quantum = Decimal('1').scaleb(-places)
    return Decimal(str(value)).quantize(quantum, rounding=ROUND_HALF_UP)

fact_columns = [
    'property_id','month','total_units','occupied_units','monthly_rent_usd',
    'work_order_count','eligible_resolved_count','excluded_work_order_count',
    'excluded_unresolved_count','excluded_missing_response_count',
    'excluded_invalid_response_count','sla_met_count','avg_response_hours',
    'total_energy_kwh','meter_reading_count','total_floor_area_sqm'
]
records = []
for row in prepared.to_dict(orient='records'):
    records.append({
        'property_id': str(row['property_id']),
        'month': pd.Timestamp(row['month']).date(),
        'total_units': int(row['total_units']),
        'occupied_units': int(row['occupied_units']),
        'monthly_rent_usd': dec_or_none(row['monthly_rent_usd'], 2),
        'work_order_count': int(row['work_order_count']),
        'eligible_resolved_count': int(row['eligible_resolved_count']),
        'excluded_work_order_count': int(row['excluded_work_order_count']),
        'excluded_unresolved_count': int(row['excluded_unresolved_count']),
        'excluded_missing_response_count': int(row['excluded_missing_response_count']),
        'excluded_invalid_response_count': int(row['excluded_invalid_response_count']),
        'sla_met_count': int(row['sla_met_count']),
        'avg_response_hours': dec_or_none(row['avg_response_hours'], 2),
        'total_energy_kwh': dec_or_none(row['total_energy_kwh'], 3),
        'meter_reading_count': int(row['meter_reading_count']),
        'total_floor_area_sqm': dec_or_none(row['total_floor_area_sqm'], 3)
    })
property_records = (prepared[['property_id','property_name','city']]
                    .drop_duplicates('property_id').to_dict(orient='records'))
month_records = []
for m in sorted(prepared['month'].unique()):
    dt = pd.Timestamp(m)
    month_records.append({'month': dt.date(),
                          'month_end': (dt + pd.offsets.MonthEnd(0)).date(),
                          'calendar_year': int(dt.year),
                          'calendar_month': int(dt.month)})
assert len(records) == 72 and len(property_records) == 12 and len(month_records) == 6
print('Parameterized rows prepared:', len(records))

Parameterized rows prepared: 72

In [393]:

import pandas as pd

# 1. Use your existing prepared DataFrame
df = prepared.copy()

required_source = [
    "property_id",
    "month",
    "total_units",
    "occupied_units",
    "monthly_rent_usd",
    "work_order_count",
    "eligible_resolved_count",
    "excluded_unresolved_count",
    "excluded_missing_response_count",
    "excluded_invalid_response_count",
    "sla_met_count",
    "total_energy_kwh",
    "total_floor_area_sqm",
]

missing_source = sorted(
    set(required_source) - set(df.columns)
)

if missing_source:
    raise ValueError(
        f"Missing source columns: {missing_source}"
    )

# 2. Validate numeric source columns
numeric_cols = [
    c for c in required_source
    if c not in ("property_id", "month")
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

if df[numeric_cols].isna().any().any():
    raise ValueError(
        "Source contains missing or invalid numeric values"
    )

if (df[numeric_cols] < 0).any().any():
    raise ValueError("Negative KPI values found")

# 3. Prepare reporting month
dates = pd.to_datetime(df["month"], errors="coerce")

if dates.isna().any():
    raise ValueError("Invalid reporting month found")

# First day of reporting month
df["month_date"] = (
    dates.dt.to_period("M").dt.to_timestamp().dt.date
)

# 4. Map rental and energy columns
df["earned_monthly_rent_usd"] = df["monthly_rent_usd"]
df["energy_kwh"] = df["total_energy_kwh"]
df["floor_area_sqm"] = df["total_floor_area_sqm"]

# 5. Calculate occupancy
if (df["total_units"] <= 0).any():
    raise ValueError("Total units must be positive")

if (df["occupied_units"] > df["total_units"]).any():
    raise ValueError("Occupied units exceed total units")

df["occupancy_rate"] = (
    df["occupied_units"] / df["total_units"]
)

# 6. Map SLA source counts
df["sla_eligible_orders"] = df["eligible_resolved_count"]
df["sla_compliant_orders"] = df["sla_met_count"]

df["sla_missing_response_orders"] = (
    df["excluded_missing_response_count"]
)

if (
    df["sla_compliant_orders"]
    > df["sla_eligible_orders"]
).any():
    raise ValueError("SLA compliant count exceeds eligible count")

# 7. Reconcile work-order populations
# Assumes the three exclusions are disjoint and
# all unresolved orders count as open.
df["open_orders"] = df["excluded_unresolved_count"]

df["resolved_orders"] = (
    df["eligible_resolved_count"]
    + df["excluded_missing_response_count"]
    + df["excluded_invalid_response_count"]
)

if (
    df["open_orders"] + df["resolved_orders"]
    != df["work_order_count"]
).any():
    raise ValueError(
        "Work-order counts do not reconcile. "
        "Check resolved/unresolved status classifications."
    )

# 8. Calculate SLA compliance
df["sla_compliance_rate"] = (
    df["sla_compliant_orders"]
    / df["sla_eligible_orders"].replace(0, float("nan"))
)

# 9. Calculate energy intensity
if (df["floor_area_sqm"] <= 0).any():
    raise ValueError(
        "Floor area must be positive to calculate intensity"
    )

df["energy_intensity_kwh_sqm"] = (
    df["energy_kwh"] / df["floor_area_sqm"]
)

# 10. Validate target columns
missing_target = sorted(
    set(fact_columns) - set(df.columns)
)

if missing_target:
    raise ValueError(
        f"Unresolved target columns: {missing_target}"
    )

# 11. Build records using existing fact_columns
fact_df = df[fact_columns].copy()

records = (
    fact_df.astype(object)
    .where(pd.notna(fact_df), None)
    .to_dict(orient="records")
)

# 12. Validate property-month uniqueness
keys = [
    (r["property_id"], r["month_date"])
    for r in records
]

if len(keys) != len(set(keys)):
    raise ValueError("Duplicate property-month keys found")

expected_months = {
    f"2025-{m:02d}" for m in range(1, 7)
}

actual_months = {
    str(r["month_date"])[:7] for r in records
}

if actual_months != expected_months:
    raise ValueError(
        f"Unexpected reporting months: {sorted(actual_months)}"
    )

if len(records) != 72:
    raise ValueError(
        f"Expected 72 property-month records; got {len(records)}"
    )

print("Record preparation successful")
print("Total records:", len(records))
print("Columns:", list(fact_df.columns))
print("Missing columns:", missing_target)

Record preparation successful
Total records: 72
Columns: ['property_id', 'month_date', 'total_units', 'occupied_units', 'occupancy_rate', 'earned_monthly_rent_usd', 'resolved_orders', 'sla_eligible_orders', 'sla_compliant_orders', 'open_orders', 'sla_missing_response_orders', 'sla_compliance_rate', 'energy_kwh', 'floor_area_sqm', 'energy_intensity_kwh_sqm']
Missing columns: []

In [410]:

import pandas as pd
from decimal import Decimal, ROUND_HALF_UP
from sqlalchemy import text

# =====================================================
# PROPTECH360: PREPARE POSTGRESQL LOAD RECORDS
# =====================================================

df = prepared.copy()

required = [
    "property_id", "property_name", "city", "month",
    "total_units", "occupied_units",
    "monthly_rent_usd", "total_energy_kwh",
    "total_floor_area_sqm", "meter_reading_count",
    "work_order_count", "eligible_resolved_count",
    "excluded_unresolved_count",
    "excluded_missing_response_count",
    "sla_met_count"
]

missing = sorted(set(required) - set(df.columns))

if missing:
    raise ValueError(f"Missing source columns: {missing}")

# -----------------------------------------------------
# 1. Clean keys and dates
# -----------------------------------------------------

for col in ["property_id", "property_name", "city"]:
    if df[col].isna().any():
        raise ValueError(f"Null values in {col}")

    df[col] = df[col].astype(str).str.strip()

    if df[col].eq("").any():
        raise ValueError(f"Empty values in {col}")

dates = pd.to_datetime(df["month"], errors="coerce")

if dates.isna().any():
    raise ValueError("Invalid month values")

df["month_date"] = (
    dates.dt.to_period("M").dt.to_timestamp().dt.date
)

# -----------------------------------------------------
# 2. Validate source numeric metrics
# -----------------------------------------------------

numeric_cols = [
    c for c in required
    if c not in (
        "property_id", "property_name", "city", "month"
    )
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

    if df[col].isna().any():
        raise ValueError(f"Null/invalid values in {col}")

    if (df[col] < 0).any():
        raise ValueError(f"Negative values in {col}")

count_cols = [
    "total_units", "occupied_units",
    "meter_reading_count", "work_order_count",
    "eligible_resolved_count",
    "excluded_unresolved_count",
    "excluded_missing_response_count",
    "sla_met_count"
]

for col in count_cols:
    if (df[col] % 1 != 0).any():
        raise ValueError(f"{col} must be a whole number")

    df[col] = df[col].astype(int)

if (df["occupied_units"] > df["total_units"]).any():
    raise ValueError("Occupied units exceed total units")

if (
    df["sla_met_count"]
    > df["eligible_resolved_count"]
).any():
    raise ValueError("SLA compliant count exceeds eligible count")

if (df["total_floor_area_sqm"] <= 0).any():
    raise ValueError("Floor area must be positive")

# -----------------------------------------------------
# 3. Calculate fact-table KPIs
# -----------------------------------------------------

df["occupancy_rate"] = (
    df["occupied_units"]
    / df["total_units"].replace(0, float("nan"))
)

df["earned_monthly_rent_usd"] = df["monthly_rent_usd"]
df["energy_kwh"] = df["total_energy_kwh"]
df["floor_area_sqm"] = df["total_floor_area_sqm"]

df["sla_eligible_orders"] = (
    df["eligible_resolved_count"]
)

df["sla_compliant_orders"] = df["sla_met_count"]

df["sla_missing_response_orders"] = (
    df["excluded_missing_response_count"]
)

df["sla_compliance_rate"] = (
    df["sla_compliant_orders"]
    / df["sla_eligible_orders"].replace(0, float("nan"))
)

df["energy_intensity_kwh_sqm"] = (
    df["energy_kwh"] / df["floor_area_sqm"]
).where(df["meter_reading_count"] > 0)

# -----------------------------------------------------
# 4. Derive resolved/open orders from work-order status
# -----------------------------------------------------

# valid_wo was constructed in the earlier work-order
# preparation step in your notebook.

wo = valid_wo.copy()

wo_required = {"property_id", "month", "resolved"}

if not wo_required.issubset(wo.columns):
    raise ValueError(
        f"valid_wo missing: {wo_required - set(wo.columns)}"
    )

wo["property_id"] = (
    wo["property_id"].astype(str).str.strip()
)

wo_dates = pd.to_datetime(wo["month"], errors="coerce")

if wo_dates.isna().any():
    raise ValueError("Invalid work-order month values")

wo["month_date"] = (
    wo_dates.dt.to_period("M").dt.to_timestamp().dt.date
)

if wo["resolved"].isna().any():
    raise ValueError("Null resolved status found")

if not wo["resolved"].isin([True, False]).all():
    raise ValueError("Resolved status must be boolean")

wo_summary = (
    wo.groupby(["property_id", "month_date"], as_index=False)
    .agg(
        source_work_orders=("resolved", "size"),
        resolved_orders=("resolved", "sum")
    )
)

df = df.merge(
    wo_summary,
    on=["property_id", "month_date"],
    how="left",
    validate="one_to_one"
)

df[["source_work_orders", "resolved_orders"]] = (
    df[["source_work_orders", "resolved_orders"]]
    .fillna(0)
    .astype(int)
)

if not (
    df["source_work_orders"] == df["work_order_count"]
).all():
    raise ValueError(
        "Work-order counts differ from valid_wo. "
        "Recheck the work-order aggregation."
    )

df["open_orders"] = (
    df["work_order_count"] - df["resolved_orders"]
)

if not (
    df["open_orders"]
    == df["excluded_unresolved_count"]
).all():
    raise ValueError(
        "Open-order counts do not match unresolved counts"
    )

# -----------------------------------------------------
# 5. Validate reporting period and grain
# -----------------------------------------------------

expected_months = {
    f"2025-{i:02d}" for i in range(1, 7)
}

actual_months = {
    str(m)[:7] for m in df["month_date"]
}

if actual_months != expected_months:
    raise ValueError(
        f"Incorrect reporting months: {sorted(actual_months)}"
    )

if df.duplicated(["property_id", "month_date"]).any():
    raise ValueError("Duplicate property-month records")

if (
    len(df) != 72
    or df["property_id"].nunique() != 12
):
    raise ValueError(
        "Expected 72 rows from 12 properties"
    )

if not (
    df.groupby("property_id")["month_date"].nunique() == 6
).all():
    raise ValueError(
        "Every property must have six reporting months"
    )

# -----------------------------------------------------
# 6. Define actual fact-table columns from 01_schema.sql
# -----------------------------------------------------

fact_columns = [
    "property_id",
    "month_date",
    "total_units",
    "occupied_units",
    "occupancy_rate",
    "earned_monthly_rent_usd",
    "resolved_orders",
    "sla_eligible_orders",
    "sla_compliant_orders",
    "open_orders",
    "sla_missing_response_orders",
    "sla_compliance_rate",
    "energy_kwh",
    "floor_area_sqm",
    "energy_intensity_kwh_sqm"
]

# -----------------------------------------------------
# 7. Convert decimal metrics for PostgreSQL
# -----------------------------------------------------

def dec_or_none(value, places):
    if pd.isna(value):
        return None

    quantum = Decimal("1").scaleb(-places)

    return Decimal(str(value)).quantize(
        quantum,
        rounding=ROUND_HALF_UP
    )

decimal_places = {
    "occupancy_rate": 6,
    "earned_monthly_rent_usd": 2,
    "sla_compliance_rate": 6,
    "energy_kwh": 2,
    "floor_area_sqm": 2,
    "energy_intensity_kwh_sqm": 6
}

records = []

for row in df[fact_columns].to_dict(orient="records"):

    record = dict(row)

    record["property_id"] = str(row["property_id"])

    for col, places in decimal_places.items():
        record[col] = dec_or_none(row[col], places)

    for col in [
        "total_units", "occupied_units",
        "resolved_orders", "sla_eligible_orders",
        "sla_compliant_orders", "open_orders",
        "sla_missing_response_orders"
    ]:
        record[col] = int(row[col])

    records.append(record)

# -----------------------------------------------------
# 8. Prepare dimension tables
# -----------------------------------------------------

property_df = df[
    ["property_id", "property_name", "city"]
].drop_duplicates()

if property_df["property_id"].duplicated().any():
    raise ValueError("Conflicting property dimensions")

property_records = property_df.to_dict(
    orient="records"
)

month_dates = sorted(df["month_date"].unique())

month_records = []

for month_date in month_dates:
    dt = pd.Timestamp(month_date)

    month_records.append({
        "month_date": dt.date(),
        "year_number": int(dt.year),
        "month_number": int(dt.month),
        "month_name": dt.strftime("%B"),
        "quarter_number": (dt.month - 1) // 3 + 1
    })

assert len(records) == 72
assert len(property_records) == 12
assert len(month_records) == 6

print("PASS: PostgreSQL records prepared")
print("Fact records:", len(records))
print("Property records:", len(property_records))
print("Month records:", len(month_records))
print("Fact columns:", fact_columns)

PASS: PostgreSQL records prepared
Fact records: 72
Property records: 12
Month records: 6
Fact columns: ['property_id', 'month_date', 'total_units', 'occupied_units', 'occupancy_rate', 'earned_monthly_rent_usd', 'resolved_orders', 'sla_eligible_orders', 'sla_compliant_orders', 'open_orders', 'sla_missing_response_orders', 'sla_compliance_rate', 'energy_kwh', 'floor_area_sqm', 'energy_intensity_kwh_sqm']

In [412]:

from sqlalchemy import text

# =====================================================
# PROPTECH360: POSTGRESQL IDEMPOTENT LOAD
# =====================================================

# Only use fixed, trusted fact column identifiers.
# fact_columns and records come from Step 1.

insert_stage_sql = text(
    "INSERT INTO stage_property_month ("
    + ", ".join(fact_columns)
    + ") VALUES ("
    + ", ".join(":" + c for c in fact_columns)
    + ")"
)

# -----------------------------------------------------
# Construct PostgreSQL upsert using the actual schema
# -----------------------------------------------------

key_columns = ["property_id", "month_date"]

update_columns = [
    c for c in fact_columns if c not in key_columns
]

upsert_fact_sql = text(
    "INSERT INTO fact_property_month AS target ("
    + ", ".join(fact_columns)
    + ") SELECT "
    + ", ".join("s." + c for c in fact_columns)
    + " FROM stage_property_month AS s"
    + " WHERE TRUE"
    + " ON CONFLICT (property_id, month_date)"
    + " DO UPDATE SET "
    + ", ".join(
        f"{c} = EXCLUDED.{c}" for c in update_columns
    )
    + ", updated_at = CURRENT_TIMESTAMP"
    + " WHERE ROW("
    + ", ".join("target." + c for c in update_columns)
    + ") IS DISTINCT FROM ROW("
    + ", ".join("EXCLUDED." + c for c in update_columns)
    + ")"
)

# -----------------------------------------------------
# Validate existing database schema before writing
# -----------------------------------------------------

expected_tables = {
    "dim_property": {
        "property_id", "property_name", "city"
    },
    "dim_month": {
        "month_date", "year_number", "month_number",
        "month_name", "quarter_number"
    },
    "fact_property_month": set(fact_columns)
}

with engine.connect() as conn:

    result = conn.execute(text("""
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN (
              'dim_property',
              'dim_month',
              'fact_property_month'
          )
    """))

    actual_tables = {}

    for table_name, column_name in result:
        actual_tables.setdefault(table_name, set()).add(
            column_name
        )

    for table_name, expected in expected_tables.items():
        missing = expected - actual_tables.get(
            table_name, set()
        )

        if missing:
            raise RuntimeError(
                f"{table_name} missing columns: "
                f"{sorted(missing)}. "
                "Check sql/01_schema.sql."
            )

print("PASS: PostgreSQL schema verified")

# -----------------------------------------------------
# Main loader
# -----------------------------------------------------

def load_once():

    with engine.begin() as conn:

        # 1. Load property dimension
        conn.execute(
            text("""
                INSERT INTO dim_property (
                    property_id,
                    property_name,
                    city
                )
                VALUES (
                    :property_id,
                    :property_name,
                    :city
                )
                ON CONFLICT (property_id)
                DO UPDATE SET
                    property_name = EXCLUDED.property_name,
                    city = EXCLUDED.city
            """),
            property_records
        )

        # 2. Load month dimension
        conn.execute(
            text("""
                INSERT INTO dim_month (
                    month_date,
                    year_number,
                    month_number,
                    month_name,
                    quarter_number
                )
                VALUES (
                    :month_date,
                    :year_number,
                    :month_number,
                    :month_name,
                    :quarter_number
                )
                ON CONFLICT (month_date)
                DO UPDATE SET
                    year_number = EXCLUDED.year_number,
                    month_number = EXCLUDED.month_number,
                    month_name = EXCLUDED.month_name,
                    quarter_number = EXCLUDED.quarter_number
            """),
            month_records
        )

        # 3. Create transaction-scoped staging table
        conn.exec_driver_sql("""
            CREATE TEMP TABLE stage_property_month
            (
                LIKE fact_property_month
                INCLUDING DEFAULTS
            )
            ON COMMIT DROP
        """)

        # 4. Insert staged KPI records
        conn.execute(
            insert_stage_sql,
            records
        )

        staged = conn.execute(
            text("""
                SELECT COUNT(*)
                FROM stage_property_month
            """)
        ).scalar_one()

        if staged != 72:
            raise AssertionError(
                f"Unexpected staging count: {staged}"
            )

        # 5. Perform PostgreSQL idempotent upsert
        conn.execute(upsert_fact_sql)

        # 6. Verify total fact rows
        fact_count = conn.execute(
            text("""
                SELECT COUNT(*)
                FROM fact_property_month
            """)
        ).scalar_one()

        if fact_count != 72:
            raise AssertionError(
                f"Expected 72 fact rows, got {fact_count}. "
                "Check for earlier extra reporting periods."
            )

        # 7. Confirm 12 properties and 6 months
        counts = conn.execute(text("""
            SELECT
                COUNT(DISTINCT property_id) AS properties,
                COUNT(DISTINCT month_date) AS months
            FROM fact_property_month
        """)).one()

        if counts.properties != 12 or counts.months != 6:
            raise AssertionError(
                "Expected 12 properties and 6 months"
            )

        # 8. Verify database reporting period
        db_months = conn.execute(text("""
            SELECT DISTINCT TO_CHAR(month_date, 'YYYY-MM')
            FROM fact_property_month
        """)).scalars().all()

        expected = {
            f"2025-{i:02d}" for i in range(1, 7)
        }

        if set(db_months) != expected:
            raise AssertionError(
                f"Unexpected fact months: {db_months}"
            )

        return {
            "staged_rows": staged,
            "fact_rows": fact_count
        }


# -----------------------------------------------------
# Execute loader twice to verify idempotency
# -----------------------------------------------------

first_load = load_once()
second_load = load_once()

expected_result = {
    "staged_rows": 72,
    "fact_rows": 72
}

assert first_load == second_load == expected_result

print("First load:", first_load)
print("Second load:", second_load)

print(
    "PASS: Idempotent PostgreSQL upsert verified. "
    "Fact table remains at 72 rows."
)

PASS: PostgreSQL schema verified
First load: {'staged_rows': 72, 'fact_rows': 72}
Second load: {'staged_rows': 72, 'fact_rows': 72}
PASS: Idempotent PostgreSQL upsert verified. Fact table remains at 72 rows.

In [413]:

import pandas as pd
from sqlalchemy import text

# =====================================================
# PROPTECH360: EXECUTE FIVE ANALYTICAL QUESTIONS
# =====================================================

analytics_path = SQL_DIR / "03_analytics.sql"

analytics_sql = analytics_path.read_text(
    encoding="utf-8-sig"
)

# Your existing SQL file has no semicolons inside
# SQL strings or procedural blocks.
statements = [
    s.strip()
    for s in analytics_sql.split(";")
    if s.strip()
]

if len(statements) != 6:
    raise ValueError(
        f"Expected 6 SQL statements, "
        f"found {len(statements)}. "
        "Check 03_analytics.sql."
    )

query_results = {}

with engine.begin() as conn:

    # Queries 1-4: Analytical SELECT queries
    for number in range(1, 5):

        print(f"Running analytics query {number}...")

        query_results[number] = pd.read_sql_query(
            text(statements[number - 1]),
            conn
        )

        print(
            f"Query {number} completed: "
            f"{len(query_results[number])} rows"
        )

    # Query 5, part 1: Create dashboard view
    conn.execute(text(statements[4]))

    # Query 5, part 2: Read the dashboard
    query_results[5] = pd.read_sql_query(
        text(statements[5]),
        conn
    )

    print("Query 5 dashboard completed")

# Display analytics results
query_names = {
    1: "Property Occupancy Ranking",
    2: "Earned Contractual Rent by City",
    3: "Maintenance SLA Compliance",
    4: "Above-Average Energy Intensity",
    5: "Portfolio Dashboard"
}

for number, name in query_names.items():

    print(f"\nQUERY {number}: {name}")

    display(query_results[number])

print("\nPASS: All five analytics queries completed.")

Running analytics query 1...
Query 1 completed: 0 rows
Running analytics query 2...
Query 2 completed: 24 rows
Running analytics query 3...
Query 3 completed: 12 rows
Running analytics query 4...
Query 4 completed: 0 rows
Query 5 dashboard completed

QUERY 1: Property Occupancy Ranking

Empty DataFrame
Columns: [property_id, property_name, city, occupied_unit_months, total_unit_months, average_monthly_occupancy_rate, occupancy_rank]
Index: []

QUERY 2: Earned Contractual Rent by City

    month_date           city  earned_contractual_rent_usd
0   2025-01-01          Abuja                       6400.0
1   2025-01-01         Ibadan                       7225.0
2   2025-01-01          Lagos                       5600.0
3   2025-01-01  Port Harcourt                       5600.0
4   2025-02-01          Abuja                      12750.0
5   2025-02-01         Ibadan                      12700.0
6   2025-02-01          Lagos                       9300.0
7   2025-02-01  Port Harcourt                       8600.0
8   2025-03-01          Abuja                      22025.0
9   2025-03-01         Ibadan                      21375.0
10  2025-03-01          Lagos                      14050.0
11  2025-03-01  Port Harcourt                      15100.0
12  2025-04-01          Abuja                      33700.0
13  2025-04-01         Ibadan                      24150.0
14  2025-04-01          Lagos                      15650.0
15  2025-04-01  Port Harcourt                      18450.0
16  2025-05-01          Abuja                      35700.0
17  2025-05-01         Ibadan                      28050.0
18  2025-05-01          Lagos                      17650.0
19  2025-05-01  Port Harcourt                      23350.0
20  2025-06-01          Abuja                      38100.0
21  2025-06-01         Ibadan                      32050.0
22  2025-06-01          Lagos                      21150.0
23  2025-06-01  Port Harcourt                      24950.0

QUERY 3: Maintenance SLA Compliance

,property_id,property_name,resolved_orders,sla_eligible_resolved_orders,sla_compliant_orders,excluded_unresolved_orders,excluded_missing_response_orders,sla_compliance_rate
0,P007,MetroSpace Tower 07,0,0,0,0,0,None
1,P004,MetroSpace Tower 04,0,0,0,0,0,None
2,P010,MetroSpace Tower 10,0,0,0,0,0,None
3,P011,MetroSpace Tower 11,0,0,0,0,0,None
4,P005,MetroSpace Tower 05,0,0,0,0,0,None
5,P009,MetroSpace Tower 09,0,0,0,0,0,None
6,P003,MetroSpace Tower 03,0,0,0,0,0,None
7,P006,MetroSpace Tower 06,0,0,0,0,0,None
8,P001,MetroSpace Tower 01,0,0,0,0,0,None
9,P008,MetroSpace Tower 08,0,0,0,0,0,None
10,P002,MetroSpace Tower 02,0,0,0,0,0,None
11,P012,MetroSpace Tower 12,0,0,0,0,0,None

QUERY 4: Above-Average Energy Intensity

Empty DataFrame
Columns: [month_date, property_id, property_name, property_energy_intensity, portfolio_energy_intensity, total_energy_kwh]
Index: []

QUERY 5: Portfolio Dashboard

,month_date,property_id,property_name,city,total_units,occupied_units,occupancy_rate,earned_monthly_rent_usd,resolved_orders,sla_eligible_orders,sla_compliant_orders,open_orders,sla_missing_response_orders,sla_compliance_rate,energy_kwh,floor_area_sqm,energy_intensity_kwh_sqm
0,2025-01-01,P001,MetroSpace Tower 01,Lagos,19,1,0.052632,800.0,0,0,0,0,0,None,0.0,1890.0,None
1,2025-01-01,P002,MetroSpace Tower 02,Abuja,20,2,0.100000,2700.0,0,0,0,0,0,None,0.0,1650.0,None
2,2025-01-01,P003,MetroSpace Tower 03,Ibadan,20,1,0.050000,2200.0,0,0,0,0,0,None,0.0,1995.0,None
3,2025-01-01,P004,MetroSpace Tower 04,Port Harcourt,20,1,0.050000,650.0,0,0,0,0,0,None,0.0,1920.0,None
4,2025-01-01,P005,MetroSpace Tower 05,Lagos,20,1,0.050000,975.0,0,0,0,0,0,None,0.0,1860.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2025-06-01,P008,MetroSpace Tower 08,Port Harcourt,20,9,0.450000,10750.0,0,0,0,0,0,None,0.0,1800.0,None
68,2025-06-01,P009,MetroSpace Tower 09,Lagos,20,8,0.400000,9775.0,0,0,0,0,0,None,0.0,1695.0,None
69,2025-06-01,P010,MetroSpace Tower 10,Abuja,20,7,0.350000,8150.0,0,0,0,0,0,None,0.0,1980.0,None
70,2025-06-01,P011,MetroSpace Tower 11,Ibadan,20,11,0.550000,13350.0,0,0,0,0,0,None,0.0,1575.0,None
71,2025-06-01,P012,MetroSpace Tower 12,Port Harcourt,20,7,0.350000,9900.0,0,0,0,0,0,None,0.0,1830.0,None

PASS: All five analytics queries completed.

In [414]:

# Execute PostgreSQL verification queries
validation_sql = (
    SQL_DIR / "02_load.sql"
).read_text(encoding="utf-8-sig")

validation_statements = [
    s.strip()
    for s in validation_sql.split(";")
    if s.strip()
]

with engine.connect() as conn:

    for number, statement in enumerate(
        validation_statements, start=1
    ):

        result = pd.read_sql_query(
            text(statement),
            conn
        )

        print(f"\nValidation {number}")
        display(result)

Validation 1

   total_fact_rows
0               72

Validation 2

   total_rows  unique_property_months
0          72                      72

Validation 3

Empty DataFrame
Columns: [property_id, month_date, duplicate_count]
Index: []

Validation 4

  fact_row_count_test  actual_fact_rows
0                PASS                72